### ISSUE TITLE
Can't change system settings

### ISSUE THREAD

**Issue by JohnnyB1989** [theyosh/TerrariumPI#100]
Hi,

at first a big up for your tremendous work here. I've tried to set up a system by my own until I found yours.

So now here is my problem regarding to the system settings.
When I try to change the URL for the wheather location, I have to select a language but it says no results found in the dropdown menu.
When I first logged in I could change that to german.

Thanks for your time,

Johnny

**Comment by theyosh** [comment]
Hi, strange.... 

what is the output of the url: `/api/config/system` at your pi? Add it after the :8090 part in the url.

Should look like something as: https://terrarium.theyosh.nl/api/config/system

**Comment by JohnnyB1989** [comment]
This is what it says:

{"temperature_indicator": "C", "power_usage": "5", "language": "de_AT", "title": "TerrariumPI 3.3.0", "admin": "admin", "power_price": "0", "host": "::", "windspeed": "kmh", "version": "3.3.0", "location": "https://www.yr.no/sted/Tyskland/Nordrhein-Westfalen/Bergkamen/", "available_languages": ["de_AT", "it_IT", "nl_NL", "en_US", "fr_BE"], "water_price": "0", "soundcard": "bcm2835 ALSA", "port": "8090", "owfs_port": "4304"}

looks okay so far. But I can't choose any of those languages.

**Comment by JohnnyB1989** [comment]
Had some other issues coming up...

1. The webcam (RPICam) only takes one picture when I implement it as a new one... so there is nothing moving, just the picture.

2. When I try to change something, like the sensor or a switch, sometimes it is changed and sometimes it is not.

I will try to set it up again first and change nothing, because I get an error in the screen because the weather URL is incorrect. Perhaps this destroys everything else.

**Comment by theyosh** [comment]
Webcam is just an image. There is no live streaming. The webcam takes a picture every minute. That is all.

If you change the settings, look at the error messages in the screen session: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi

And clear browser cache to make sure you will get the latest HTML

**Comment by JohnnyB1989** [comment]
Hi,

I don't need to change my local weather, so I've set it up again and now everything works.

Thanks for your support.

Johnny
