### ISSUE TITLE
Interface protection

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#102]
Hi,

is it possible if i'm on the go, for example, and need my interface to install a security. For example: a password before the interface is displayed?

Thank you for your help and your time

**Comment by Barbara1984** [comment]
https://de.wikihow.com/Eine-Webseite-mit-Passwort-sch%C3%BCtzen

Maybe something like that?

**Comment by theyosh** [comment]
Your request is clear. Your provided example as a very bad example. :) Because passwords in javascript is no security. I can just read out the file and know the passwords.

So what I have done is that I added an extra option in the system settings to enable 'full authentication' so that when you open the webinterface, you will have to enter a username and password.

**Comment by theyosh** [comment]
Git pull, restart, clear the browser cache, go to the settings page and test it out :D

**Comment by Barbara1984** [comment]
Hi, no that's not what I mean. I try to explain it differently:
If you open the interface comes a password query and only then you can see the entire interface, as an example of a photo :-)
![username-password-login-log-in-website-homepage-online-screen-screenshot-f4rxmx](https://user-images.githubusercontent.com/34924591/36282645-1ba63970-12a2-11e8-86ed-c95ca677cd6d.jpg)

**Comment by theyosh** [comment]
That is way more work... can't do that. The functionality is the same. Only I will not make that kind of login window.

So, I add the option to completely lock the web interface. And after a login, you can see the interface. That is how far I can go with this.

**Comment by Barbara1984** [comment]
Ok, thanks anyway, but can you give me a tip on how I could protect my interface from strange views in the www?

**Comment by Barbara1984** [comment]
Funny thing is that I have now made git pull and because cache emptied and pi reboot but I'm still not prompted to enter a password I come immediately to the interface

**Comment by Barbara1984** [comment]
Ok, now it works, thank you so much for your help.

**Comment by theyosh** [comment]
If you have authenticate one time it will stay in the browser as long as the browser is running. So after enabling it, to test it, you have to restart your browser. But I guess you have done that, and you see the authentication

**Comment by Barbara1984** [comment]
Yes, I saw it today, which makes me very happy, thank you
