### ISSUE TITLE
German translation update

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#105]
Hi, I worked a bit on the German translation, maybe I can help you with that. Why can not I swap the files myself with your code?

[German.zip](https://github.com/theyosh/TerrariumPI/files/1735188/German.zip)

**Comment by theyosh** [comment]
You should be able to overwrite them at the right location:

`/home/pi/TerrariumPI/locales/de_AT/LC_MESSAGES`

But the right way is described in the Wiki. You should use your own fork of code and send pull requests

**Comment by Barbara1984** [comment]
Ok thanks, then I'll try that next time.
