### ISSUE TITLE
Question for translation

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#110]
Energenie USB
Energenie LAN

What exactly is meant by that?

**Comment by theyosh** [comment]
That are devices: http://energenie.com/item.aspx?id=7556 So it is a product name

**Comment by Barbara1984** [comment]
Ah ok, then I understand I'll send you a pull request afterwards

**Comment by theyosh** [comment]
Updated translation in development branch. Will get add in next release
