### ISSUE TITLE
Memory-Usage in System-Status-View

### ISSUE THREAD

**Issue by kahuwi14** [theyosh/TerrariumPI#117]
Hello there!
I discovered the other day , that the memoryusage-warning appeared in the systemstatus-view.
After a little research it turned out, that there is not a big memory-usage of one or more applications.
The warning depends on the usage of linux itself: the os uses the free memory for buffering/caching.
@theyosh If you got freetime ;) you could perhaps change the warning-trigger into a little difference between total and used memory. 

![memoryusage](https://user-images.githubusercontent.com/36901881/36945613-78cb0bbe-1fb1-11e8-948a-42a5d47b9ada.png)

**Comment by theyosh** [comment]
Actually, there is a memory leak in my code. I have seen this earlier. When you drop the OS caches, a lot of memory is freed. But after a minute it is all taken again. And I do have graphs that does show some memory increment over time with my Python code. But I have no idea how to tackle memory leaks in Python yet :(

In the meantime I can see if this memory calculation can be done better / more real.

**Comment by kahuwi14** [comment]
> Actually, there is a memory leak in my code.

I don't agree with that.. If you have a look on my screenshots, you'll see in the first line of the table behind the "free"-command, that I have 875 MB memory (plus 100 MB Swap), 105 MB are used and 194 MB free available. That meens, there is a "leak" of 576 MB and that's the size of the buff/cache.

> When you drop the OS caches, a lot of memory is freed. But after a minute it is all taken again.

And that fits perfectly to that theory.

I've found a good descripton in German and a less detailed one in English as well:
[https://www.raspberrypi.org/forums/viewtopic.php?f=31&t=26405#p239066](url)

So I think, the one and only fault is the warning-trigger.. ;)

**Comment by theyosh** [comment]
Turns out that there was a better way of doing this: https://psutil.readthedocs.io/en/latest/#memory

**Comment by kahuwi14** [comment]
Thumbs-up!
