### ISSUE TITLE
No temperature display since the update

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#126]
Theyosh, unfortunately it shows me since yesterday no more values in temperature and humidity. Could you help me?

![unbenannt](https://user-images.githubusercontent.com/34924591/37662058-7c62cdb4-2c56-11e8-83ca-f3e665aa068d.png)

**Comment by Aapjes94** [comment]
Did you remember to clear the cache? What does the log file (system -> log) look like?
Next step would be to disconnect and add the sensors again, both the wiring and in the software.

**Comment by Barbara1984** [comment]
Hi, my cache is empty and I have already deleted my sensor and stored again, but he shows me now in the log an error.

![ds](https://user-images.githubusercontent.com/34924591/37671897-03523984-2c6d-11e8-934f-e77265900b32.png)

**Comment by Aapjes94** [comment]
Are you using regular digital sensors on with GPIO? Have you tried shutting down the pi all together? Shut down TerrariumPi with 2 * ctrl-C within a screen session then run `sudo reboot`.  And if you haven't done so already, double check all the wiring and connections.

**Comment by Barbara1984** [comment]
Thanks for your help, but unfortunately it does not work. I have now finished the screen session and restarted, the cable can not have anything because the pi including attachments were not moved. A normal DHT22 sensor is used. Do you have another tip?

![am2302-dht22-temperature-and-humidity-sensor-module-for-arduino-scm-1-149x149](https://user-images.githubusercontent.com/34924591/37674063-3b1c1268-2c72-11e8-857b-f37521dba2fd.jpg)

**Comment by Aapjes94** [comment]
Hmm then I don't really know. If this happened because of the update, you could try running the update again. Maybe something failed during the update which can be fixed by updating again?

**Comment by theyosh** [comment]
It looks a bit strange... But I am missing some engine processes, so I guess something has crashed.

- First, could you see if a reboot would fix this?
- Then look inside the screen what is happening there. There are still some errors not being logged
- Just to be sure, run the installer script again?
- Latest option is to remove the settings.cfg files (make backup) and start a clear system

And could you upload your current config?

**Comment by theyosh** [comment]
And are you are the master branch? Because I though you have tried to test some code... so make sure you are at the master branch when updating to a new version

**Comment by theyosh** [comment]
Euh, your image only shows INFO and no errors. Nor do I see any sensors in the log.

The log is normal. Wrong image maybe??

**Comment by Barbara1984** [comment]
Hi, I have now added my sensor but unfortunately no values ...

![unbenannt](https://user-images.githubusercontent.com/34924591/37732894-ab145efc-2d46-11e8-800b-46fcae2ac729.png)

**Comment by theyosh** [comment]
Could you please try the above options and give feedback? This is not helping.
Again, I do not see any terrariumEngine messages which indicate there are errors in the console. Please login with ssh and use screen -r to see what errors there are.

**Comment by Barbara1984** [comment]
Hi, I have now tried everything, a new settings.cfg, because Pi restarted, because sensor reconnected, the install file again executed, but all this does not help unfortunately. In the SSH, the following is displayed:
![unbenannt](https://user-images.githubusercontent.com/34924591/37791205-e592044a-2e08-11e8-8754-98c3c0ee77bf.png)

**Comment by Barbara1984** [comment]
Hi theyosh, I just looked at the PC and suddenly I have temperature values again although I have not done or changed anything since last night :-)

**Comment by theyosh** [comment]
Strange... but cool! Daylight saving time fix??? :)
