### ISSUE TITLE
Multiple heaters/terrarium

### ISSUE THREAD

**Issue by puyt** [theyosh/TerrariumPI#132]
Hi,

I was wondering if it's possible to use this for multiple terrariums or an option to add a 2nd heater so we can control more than 1 terrarium.

**Comment by theyosh** [comment]
Sorry, that is not possible. My software will only work for one terrarium.

Multiple terrariums means multiple Pi's and my software

**Comment by puyt** [comment]
Would it be easy to add another heater, which would probably fix my issue?

**Comment by puyt** [comment]
Oké np :-) great tool otherwise 👍

**Comment by theyosh** [comment]
Thanks. Then I close this issue
