### ISSUE TITLE
Heater issue in system environment

### ISSUE THREAD

**Issue by nke69** [theyosh/TerrariumPI#140]
Hello,

I have a small concern with the heating in the system environment, indeed I would like my heater is triggered when the values of my sensors are below the values that I determined. that's what happens, but as soon as the sensor arrives in the right range, the heating continues to be on in the environment and I have to cut it manually in the switches.
would I miss something or is it a bad setup on my part?
![capture](https://user-images.githubusercontent.com/2726187/38765976-7686b88c-3fcb-11e8-955d-ee1a7e82ee69.PNG)
![capture2](https://user-images.githubusercontent.com/2726187/38765977-769f8f06-3fcb-11e8-9755-6fe5137acc7e.PNG)

**Comment by nke69** [comment]
I found ;)
The heater stops as soon as it exceeds the range for which I attribute the values.
I just play on a smaller range so that it cuts faster;)

**Comment by theyosh** [comment]
Yes that is correct. Else the switch will toggle to often and jumps around the lower alarm level. This could harm the electronic equipment
