### ISSUE TITLE
Turn off switch if sensor can't collect data

### ISSUE THREAD

**Issue by BashSer** [theyosh/TerrariumPI#142]
![screenshot_20180416-141013_samsung internet](https://user-images.githubusercontent.com/37932617/38805446-7c2a8c28-417e-11e8-9061-a5448e9ba730.jpg)
~22:30-01:30 one sensor disconnected from vcc and environment schedule(heater) continue work and for 3 hours temp up on 10C degrees. If i did not check this before going sleep this can fired...
Can you add check in cycle update ?
If int(last temp/hum data = none) > 20 then Turn off environment and turn off switches else pass
This can save from flood or fire

**Comment by theyosh** [comment]
Hi,

I understand your issue. I need to think about this. There are multiple solutions... so let me think about this for a few days

**Comment by BashSer** [comment]
Nice, thank you !

**Comment by theyosh** [comment]
Ok, then I close this issue.
