### ISSUE TITLE
widget on different value graphics

### ISSUE THREAD

**Issue by nke69** [theyosh/TerrariumPI#143]
Hello yosh,

For the future release, I do not know if this can be part of your vision of it.
I have a small problem reading on the different graphics of the sensors with the widget "current- alarm min - alarm max" it is positioned on the values of the various graphics and it bothers me a little in reading :(

Would it be possible to put this widget higher and online as on the attached image?

Have a good day ;)
nke69
![capture](https://user-images.githubusercontent.com/2726187/39094259-1212412e-462d-11e8-9f85-76d7f6eb9711.PNG)

**Comment by theyosh** [comment]
Ah ok, I will think about it.... and see what we can do

**Comment by theyosh** [comment]
Made an update. You can now select horizontal bars in the settings screen. Make sure you clear the browser cache after update.

**Comment by nke69** [comment]
Yesssssss, very cool :)
