### ISSUE TITLE
German update

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#151]
Hello, I have revised the German file.

[terrariumpi.zip](https://github.com/theyosh/TerrariumPI/files/2019782/terrariumpi.zip)

**Comment by theyosh** [comment]
Cool thanks! I will add in the development version which I hope to release end of this week.

And may I ask you to subscribe at the issue #115 ? And post your new future translation in that issue? So I have all the translation messages in one issue.

**Comment by theyosh** [comment]
But, I have already to admit that the code is currently changing a lot, so a part of the translation will be outdated, and there will be new translations missing.

Sorry for changing that a lot and that translations have to be done again.... But I have to do it also for Dutch... :(

**Comment by Barbara1984** [comment]
Ok, is not a problem as soon as a new version is out I'm doing a new translation.
