### ISSUE TITLE
Automatic watering

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#152]
A question, it is possible with my automatic irrigation, for example, adjust the automatically every 2 days is poured

**Comment by theyosh** [comment]
Hmmm, I think not yet, because I use 24 hours as max interval. So I have to look into this...

**Comment by Barbara1984** [comment]
Ok, thanks for your effort

**Comment by theyosh** [comment]
Does it really have to be at 2 days? What happen if you do it daily, with the half amount of once every 2 days. The amount of water is the same. Not sure if your environment is working with this.

Because when it can be done once every 24 hours, the next version can handle that.

**Comment by Barbara1984** [comment]
Hi, yes for me it would be great if I could go to 48 hours, if that does not work then it is not so bad then I really have to use it with 24 hours. But please let me know, thank you.

**Comment by theyosh** [comment]
Sneak preview: https://terrarium.theyosh.nl/

Go to the Environment part and look at the moisture part. There you could then select an alarm min option based on timer mode. Select the period in which the pump could run. And below that, the amount of minutes that the pump is actual powered on. So this way, the smallest period is 1 minute per 1 day.

Make sure the period that the pump can run, is only one or two minutes bigger then the power on time.

I hope to release this version soon.

**Comment by Barbara1984** [comment]
Hi, I think that's just right. :-)

**Comment by theyosh** [comment]
Ok, new release is out. So I think this issue should be fixed now. Could you try to update and see if it is all working?

**Comment by theyosh** [comment]
Closing due to complete and tested.
