### ISSUE TITLE
Support for MiFlora

### ISSUE THREAD

**Issue by theyosh** [theyosh/TerrariumPI#156]
Maybe [MiFlora](https://xiaomi-mi.com/sockets-and-sensors/xiaomi-huahuacaocao-flower-care-smart-monitor/) is an alternative?
Its a Bluetooth sensor for 11 Euro at Ali, it detects moisture, lux, temperature and ec (conductivity).
Librarys still existing on git.

https://github.com/marcelrv/miflora/blob/master/miflora.py

**Comment by jneumaier** [comment]
Hey! Thanks for your great project, just playing around with it and familiarizing myself with the code. I just ordered two of those to play around with it. Do you wanna have one or did you already order yourself? I would be happy to provide one. I am a developer as well so I would also like to try to help with the implementation. Have not a lot of python experience though.

**Comment by dasolan** [comment]
My order is also on the way, I really appreactiate all your efforts!

**Comment by jneumaier** [comment]
> Maybe when the code is finished I can use someone to test it

Sure.

**Comment by theyosh** [comment]
Delay delivering due out of stock :(

**Comment by theyosh** [comment]
Devices on its way. ETA 10 days :(

**Comment by theyosh** [comment]
Apparently they do not understand English and have canceled the order.....

**Comment by theyosh** [comment]
Re-ordered new ones from difference supplier....

**Comment by theyosh** [comment]
Added first support for MiFlora devices. They will be automatically scanned and added to the system. Only missing now is Light due to different measurement then Chirp light devices.

https://github.com/theyosh/TerrariumPI/commit/61f9178f46ffcd12f1d0a244b99bd05baf029640

**Comment by theyosh** [comment]
I will close this issue, due to the fact the code is released and this issue is solved.
