### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#157]
Hi Theyosh,
unfortunately works for me the update not see photos, it gets stuck and then
comes the red screen.

![rpi](https://user-images.githubusercontent.com/34924591/41055221-efbe854e-69c0-11e8-815f-637fd4d9e00d.jpg)
![rpi2](https://user-images.githubusercontent.com/34924591/41055222-efd8ebfa-69c0-11e8-8454-ac682e22d5ad.jpg)

**Comment by Barbara1984** [comment]
![rpi3](https://user-images.githubusercontent.com/34924591/41057258-ef46edda-69c6-11e8-98e3-05687f5ebd04.jpg)

**Comment by theyosh** [comment]
Installing gevent module will take 5 minutes.... :( So that needs some patients...

The error about the chirp-rpi I have to look into it... Did you update by using `git pull`?

**Comment by theyosh** [comment]
I just run the installer and tested extra about the chirp-pi. But it all works here. Just run the installer.sh again and see what happens

**Comment by Barbara1984** [comment]
Yes, it worked great :-)
