### ISSUE TITLE
Screen support?

### ISSUE THREAD

**Issue by kaju666** [theyosh/TerrariumPI#164]
Is there any possibility for a i2c OLED or LCM1602 screen support?
It will be a nice feature to have a small screen with temp/humidity on the box with raspberry and relays inside.

**Comment by theyosh** [comment]
Yes! That is a nice idea. And they are very cheap so I will buy some and do some testing.

I estimate at least two to three weeks for a first release with support for I2C driven LCD screens. Either 16x2 as 20x4 LCD will be supported

**Comment by kaju666** [comment]
Maybe the better way is to try with I2C Oled(goo.gl/BWiUEM)?
They are also very cheap and you can set more information on it even with graphic.

**Comment by theyosh** [comment]
To late :P Just bought the LCD versions :D But I expect that they all work the same way. So I think when one is supported, a hole range will work

**Comment by kaju666** [comment]
i'm not sure :) LCD and OLED have different libraries

**Comment by theyosh** [comment]
Code is released in version 3.8.0

**Comment by rikdingus** [comment]
nice work! are you planning to add graphic displays?
I am currently building a terrarium with this great software, but i would love to add some fancy e-ink white black and red display :)

**Comment by theyosh** [comment]
Hmm, yeah I think I will. But the problem will be more what to show. Because I am a programmer, not a UX designer :).

It will be based on https://github.com/adafruit/Adafruit_Python_SSD1306 

I need to think what to show and how to do it. Because it can also show images. And color stuff. So maybe that should be all options. Not sure yet.

**Comment by theyosh** [comment]
Added Oled, but do not expect to much of it. It just do the same as the LCD screens. Will show an image during startup on the Oled.

**Comment by theyosh** [comment]
For now, I am closing this issue, as basic support is provided.

**Comment by theyosh** [comment]
Nope there is currently only a summary. But again, I did implement basic connection. I will show the average of all sensor types. So you will see average temperature, average humidity etc.

What to show is a different question, on which I do not have any idea's yet.

**Comment by theyosh** [comment]
Example: https://theyosh.nl/speeltuin/TerrariumPI_LCD_Demo.mp4

**Comment by kaju666** [comment]
ok thanks it's a good start but avarage temp is useless for me becouse i have 4 temperature spots and need to know how is cold place and how is hot place.
Will be nice if will be option to choose what to see.

**Comment by theyosh** [comment]
And that is my problem with this feature. It is impossible to give valued information within max 80 chars. There you have the web interface for.

So therefore I think it is nice to have display, but what to show is the big question. And I am not going to make a full webbased text editor system for a 80 chars display. You have to think how to squeeze all that text in it. And how about more lines then fit on the display.

And I just made a small update, which could give you your feature. You can now enable showing messages on the display. You can select to show high or low sensor alarms on the display. Still you cannot pick a single sensor, but when a sensor goes out of range, a notification can be sent to you by four different methods now, so you can be notified if needed.
