### ISSUE TITLE
Can not hide graph legend

### ISSUE THREAD

**Issue by TuxujPes** [theyosh/TerrariumPI#176]
Not able to switch "Horizontal graph legend" in the settings.

Also, tried, blindly,  add `horizontal_graph_legend=false` to `defaults.cfg` but with no results.

<img width="343" alt="screen shot 2018-07-29 at 11 20 04 am" src="https://user-images.githubusercontent.com/1205052/43364357-5ea36f90-9321-11e8-8e31-724df8eca968.png">

P.S Legend on the right is annoying since it covers the most recent values :)

**Comment by theyosh** [comment]
Legend can not be hidden. But, if yo change it to Yes, save the settings and reload the hole page, it should be better.

This setting will only work after reloading the hole web page. It is a cached value.

**Comment by TuxujPes** [comment]
It worked!
Damn... I thought that blue means "selected".
And that switcher didn't work.

Very off topic but not sure what I read on forums corresponds to what I did.

Can you blow raspberry by touching 5v and 3.3v pins together?
Generalized question is, can you fry raspberry by the means it gives you without any other external sources.

One of my rasps went on "red" led only :(

**Comment by theyosh** [comment]
Hmm, not sure. I have had shortage in some sensors and start smelling burning plastic. And the wires did get warm. But after disconnecting, everything is stil working. But I am not a big hardware technician.
I do not think that you are able to blow it up with wrong cabling.

Only a red led is mostly a boot issue with the SD card. Only way to know is to hook it up to a monitor. HDMI to the television will work.

**Comment by TuxujPes** [comment]
The SD card works just fine on another raspberry :(
That's a pity it lasted so short, but whatever.

Thanks for the help!
