### ISSUE TITLE
profile description not saved to settings.cfg

### ISSUE THREAD

**Issue by penzoiders** [theyosh/TerrariumPI#18]
Profile description is not saved to the settings file.

**Comment by theyosh** [comment]
This is correct. First attempt results in a config file which is not working well with very long lines. So I have to find a other solution. Maybe creating s small html file.
For me it is not a huge issue, so it has a low priority for me right now

**Comment by penzoiders** [comment]
Yes, absolutely no priority. I was just keeping track of testing.

**Comment by theyosh** [comment]
Just write to a text file will do.
