### ISSUE TITLE
Add light state option to the webcam archive configuration

### ISSUE THREAD

**Issue by h1kkan** [theyosh/TerrariumPI#184]
Hi @theyosh !
Could you please add "light state" param to the webcam archiving function? 
It would be nice to be able to configure camera archiving depending on light/day state. Thanks!

**Comment by theyosh** [comment]
Just made. If you pull the latest master branch, restart and clear you browser cache, there are two new options in the webcam settings page under archive.

**Comment by h1kkan** [comment]
Could it be also added to the timer options (currently it is available only for motion)? So it will be possible to take shots with interval only when light is on.

**Comment by theyosh** [comment]
Ah crap... I thought that this would be a smart fix... but your right... I will change to add an extra option for light on and of option

**Comment by h1kkan** [comment]
Tested it last night - all seems to be ok. Images are taken in configured interval and depend on env lights state. No errors occurred during tests. Thanks!
