### ISSUE TITLE
Night temperature difference keeps replying

### ISSUE THREAD

**Issue by ericmcgomes** [theyosh/TerrariumPI#189]
Hi, I have set temperature between 30 and 35°C at day and a difference to night temperature of - 5°C, so it is between 25 and 30°C.

The problem is, if I reboot the system or change an environment parameter during the night, the difference is reapplied, changing to 20-25, 15-20, 10-15°C...

After this, I have to change temperature sensor settings again to return to 25~30°C at night.

There is a way to avoid this behavior?

**Comment by theyosh** [comment]
Sorry for the late reply, but this has been discussed over here: #183 

So in my opinion this is a duplicate issue with #183
