### ISSUE TITLE
remote Dimmer - which kind of does it support

### ISSUE THREAD

**Issue by funware84** [theyosh/TerrariumPI#190]
Hi,
i'm looking for a Dimmer which support 12v led dimming.
i have got 3 LED lights, 2 for day time an 1 for Night.
have u any suggestions?

thanks

**Comment by theyosh** [comment]
Euh, I have actually no idea. Could this be a solution: http://www.takaitra.com/posts/503

Then we have to wait for issue #159

**Comment by theyosh** [comment]
Closing due to no response
