### ISSUE TITLE
USB Webcam doesnt Work

### ISSUE THREAD

**Issue by Marvv90** [theyosh/TerrariumPI#192]
The USB Webcam „dev/video0“ work‘s only for seconds on the startup from the Raspberry PI 3 !

After the Startup the Image from the Webcam doesnt Refresh or the Webcam work ! 

Log-File:

2018-10-10 21:17:04,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server at location: http://192.168.0.116:8090 ...
2018-10-10 21:17:25,000 - INFO    - terrariumWebserver   - Running webserver at :::8090
libv4l2: error setting pixformat: Device or resource busy
HIGHGUI ERROR: libv4l unable to ioctl S_FMT
libv4l2: error setting pixformat: Device or resource busy
libv4l1: error setting pixformat: Device or resource busy
HIGHGUI ERROR: libv4l unable to ioctl VIDIOCSPICT

I have tried different Webcams ! All the same!

After every Reboot / Shutdown the same failure! 

Sorry for my broken english!

Best Regards 

Marvv

**Comment by theyosh** [comment]
Hi @Marvv90 

I also have those errors, but did not pay that much attention to it. I was thinking it was a webcam issue and expected to work correctly. But as you have tried multiple webcams, it sounds like a software issue.

So I will investigate this and see what I can find

**Comment by theyosh** [comment]
Should be working now. Downside is that the webcam is continuously running (red light on) and therefore a bit more power consuming.

Opening and closing/releasing the webcam did not work properly.

**Comment by Marvv90** [comment]
And when i try to Change the Settings from the Camera then crash the Webcam with this Code:

libv4l2: error setting pixformat: Device or resource busy
HIGHGUI ERROR: libv4l unable to ioctl S_FMT
libv4l2: error setting pixformat: Device or resource busy
libv4l1: error setting pixformat: Device or resource busy
HIGHGUI ERROR: libv4l unable to ioctl VIDIOCSPICT

And Only a Restart from the System helps.

Only a Info: This Webcams works properly with "Motion"

**Comment by theyosh** [comment]
Damm, you are right. I also see the delay here. Did not test that.... And changing settings could also be an issue now. So I have to rethink this over.... :( Will unfortunately take some more time

**Comment by theyosh** [comment]
Yes! found the bug. It should now working like expected. Due to threading to run more processes in parallel the usb webcam got stuck. Now the threading is at a higher level and that works much better.

You can change settings without issues and the camera will take proper shots.

**Comment by Marvv90** [comment]
i test it tomorrow early, and report to you !

**Comment by Marvv90** [comment]
Yeah it work properly !!!! Good Job ! 👍
