### ISSUE TITLE
EnerGenie PG-PM2 New ID "15"

### ISSUE THREAD

**Issue by Marvv90** [theyosh/TerrariumPI#195]
Hi theyosh,

**EnerGenie PG-PM2 USB have a New ID "fd15"** ,please insert to install.sh:

`echo 'SUBSYSTEM=="usb", ATTR{idVendor}=="04b4", ATTR{idProduct}=="fd15", GROUP="sispmctl", MODE="660"' >> /etc/udev/rules.d/60-sispmctl.rules`

**I am affected?** 

`lsusb`

Output:
**Bus 001 Device 004: ID 04b4:fd15 Cypress Semiconductor Corp.  <---- the EnerGenie PG-PM2** 
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Workaround for User's with this Power Switch to get it Work:**

Run the Command's:
`screen -r` & Hit 2 x `Ctrl+C` to Terminate the Screen
`sudo apt-get remove sispmctl`
Hit `Y`
`sudo apt-get install libusb-dev`
`wget -O sispmctl.tar.gz https://downloads.sourceforge.net/project/sispmctl/sispmctl/sispmctl-4.0/sispmctl-4.0.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fsispmctl%2Ffiles%2Flatest%2Fdownload&ts=1540205121`
Hit `Enter`
`tar xvzf sispmctl.tar.gz`
`sudo rm sispmctl.tar.gz`
`cd sispmctl-4.0`
`sudo nano src/sispm_ctl.h`

Change Line from:
**#define PRODUCT_ID_SISPM_FLASH_NEW      0xFD13**
To:
**#define PRODUCT_ID_SISPM_FLASH_NEW      0xFD15**

`Ctrl+X` and `Y` and `Enter`
`./configure --prefix=/usr`
`make`
`sudo make install`
`sudo ldconfig`
`cd`
`sudo reboot`

Now you can use normally the EnerGenie USB from Webserver.

Only one or two things @theyosh ,

The Screen show me on or two Messages:

/usr/local/lib/python2.7/dist-packages/pywemo/ssdp.py:142: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  if tree:

But all work's fine , as far as I could test it !

**Comment by theyosh** [comment]
Thanks for the update. I think I will fix this in a different way (more generic). But this will certainly help.

The two messages you see:
- FutureWarning: This is due to a new external library to control WeMo switches #187 
- Found malformed XML is new to me. Could it be that the IP is from your EnerGenie power switch? Cause the WeMo switches are found through UPnP calls. Could be that EnerGenie also supports UPnP

**Comment by Marvv90** [comment]
Issue wait of a Update from sispmctl for ID 15, Problem sides theyosh solved !

**Comment by theyosh** [comment]
Yeah... will do that... I see the code is already updated. So I will just wait till the debian packages are updated.
