### ISSUE TITLE
Energenie Pi-mote socket board

### ISSUE THREAD

**Issue by EoinH** [theyosh/TerrariumPI#199]
Hi,

Would it be possible to add support for the Energenie pi-mote & 4-way RF extension lead?
https://energenie4u.co.uk/catalogue/product/ENER010-PI

The GPIO Zero library  added built-in support for Energenie sockets so hopefully it's easy to incorporate into your code!

Thanks,
H.

**Comment by theyosh** [comment]
I think this is possible. Only I cannot test it. So if you have the hardware, I can add code and you have to test it. Is this possible?

Also, the code is never possible to readout the state or listen to the RF remote for signals.

**Comment by EoinH** [comment]
I have the hardware already so I would be happy to test for you!  And checking the state or that is not necessary, just switching the sockets.

Much thanks,
H.

**Comment by theyosh** [comment]
Ok done :)

Just chose for Energenie Pi-Mote and enter the number os the socket. That should do the trick

**Comment by EoinH** [comment]
Great news - the switches work perfectly!  
I've been able to set up all 4 switches and put two of them on timers.
I had some suggestions for improvements to the software also - is that something you are interested in? and if so should I start a new thread?

Thanks again for the updates!
H.

**Comment by theyosh** [comment]
Cool! For new features please open an issue per feature. That makes the communication a lot easier.
