### ISSUE TITLE
TerrariumPI not starting after update

### ISSUE THREAD

**Issue by Natrixz** [theyosh/TerrariumPI#209]
As the tile already say's;
TerrariumPI is not starting anymore after the update.
is just sticks with "starting terrariumpi server at location"

**Comment by Natrixz** [comment]
I stand corrected, it does start.
However it does take ages before it starts.
About 3 to 5 minutes before anything happens at all.

**Comment by theyosh** [comment]
Ah yesh! That is the database cleanup.... Mine is 20+ minutes :)

Every update it will clear the database in order to make sure there is no wasted space. Maybe I should make some kind of notification that that is happening on the screen. It is mentioned in the logfile though

**Comment by theyosh** [comment]
Closing this now. As there is now a warning when the cleanup is taking place. Also add it to the know issues. https://github.com/theyosh/TerrariumPI/wiki/Known-issues#slow--hanging-restart-after-upgrade
