### ISSUE TITLE
Wunderground url?

### ISSUE THREAD

**Issue by Swiftnesses** [theyosh/TerrariumPI#216]
I provide data to Wunderground.

I'm trying to add my station URL to the settings, which format does it need to be, I've tried many without luck...

**Comment by theyosh** [comment]
It should be in the format: https://api.wunderground.com/api/[YOUR_API_KEY]/geolookup/astronomy/hourly10day/q/[COUNTRY]/[CITY].json

You can find that in the 'help' section on the settings page.

I have not tested it that much, so could be that you have a different part in country/city.json part.

**Comment by Swiftnesses** [comment]
Works :)
