### ISSUE TITLE
New Install on Rpi

### ISSUE THREAD

**Issue by Marvv90** [theyosh/TerrariumPI#220]
Hi theyosh,

i have full reinstalled my PI with a fresh Image and a fresh Install from Terrarium PI , two things I noted.

the Installer hangs extrem on 95 % install E-Mails ( 20 -30 min )& the second is the Adafruit DHT Test Folder in the Home/pi directory is missing !

**Comment by theyosh** [comment]
I switched to more pip install of modules. That way I have newer libraries. Unfortunally, the emails module does need lxml. And the os version is old, so during installation the lxml module is also upgrade.

The problem with lxml and gevent is that they work with native C code that needs to be compiled. And that takes time. But this way we have the newest modules which having features I need.

The missing folder for the Adafruit DHT is correct. That is now also installed with pip and therefore the folder is not there. I need to see if the pip modules does install the test scripts also and will update the FAQ

**Comment by theyosh** [comment]
In the mean time... https://github.com/theyosh/TerrariumPI/issues/210 :)

**Comment by theyosh** [comment]
Hmm, I had again an installer problem. Only solution is to rerun. So it is a known issue, and will keep it that way. Therefore I close this issue. Thanks for notifying.
