### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Swiftnesses** [theyosh/TerrariumPI#225]
Hey @theyosh,

To use the calendar, do we need to make it completely public? Any reason why the public url will not work instead? (tried it, but it seems I also need to click the public link, which exposes it to Google search etc).

**Comment by theyosh** [comment]
Hmm, I have no idea. Just created this as a feature for someone. I do not use it.

So I am afraid that is the only way. https://support.google.com/calendar/answer/41207
