### ISSUE TITLE
How can I buy you a beer?

### ISSUE THREAD

**Issue by Benjin** [theyosh/TerrariumPI#233]
Got a PayPal address or something?  This GitHub project is keeping my plants alive while both my roommate and I are out on vacation.

**Comment by theyosh** [comment]
Hi, that is cool! For sending donations look at: https://github.com/theyosh/TerrariumPI/wiki/Donations

Any amount is fine and will be used for new hardware.

**Comment by AndrejWeber** [comment]
Today is a good day for donations 🤓🎁
Merry Christmas to all
Thank you for your great work @theyosh
