### ISSUE TITLE
Error after update to 3.9.3

### ISSUE THREAD

**Issue by Kollimat** [theyosh/TerrariumPI#236]
Hello i get this error after updating to version 3.9.3. 

![terrariumpi_error](https://user-images.githubusercontent.com/31453382/50515280-f6519700-0aa3-11e9-94fe-818562ce44c7.PNG)

I already tried install 3 times.
Thanks.

**Comment by theyosh** [comment]
Hi, that is a bug. It should now be fixed. Thanks for finding.

Do a `git pull` and restart. It should be running normal again

**Comment by theyosh** [comment]
When it is running please look at: #210

**Comment by Kollimat** [comment]
Thank you, now it is working. :)

**Comment by theyosh** [comment]
Nice!
