### ISSUE TITLE
Temperature number the same, no matter the units

### ISSUE THREAD

**Issue by grantlarouere** [theyosh/TerrariumPI#238]
When I change the temperature units on my DHT22 sensor from C to F or K, the number stays identical. The value is not translating correctly.  Also, thank you so much for sharing this great project and I'm really looking forward to setting everything up, once this issue is figured out.

**Comment by grantlarouere** [comment]
I've done some minor troubleshooting and the temperature number displayed is always in C, even if I select F or K, the letter next to the number will state F or K, but the number value is always that of C.

**Comment by grantlarouere** [comment]
It's displaying correctly now. Thank you for the fast fix!

**Comment by theyosh** [comment]
Closing due to fixed.

**Comment by theyosh** [comment]
@grantlarouere Can I ask you to look at #210 ?
