### ISSUE TITLE
Cant change language

### ISSUE THREAD

**Issue by pewi81** [theyosh/TerrariumPI#24]
I installed the latest update and now I can't change language to English.
There is no options pin the Settings page to change language.

**Comment by theyosh** [comment]
Euh, could it be browser cache? Clear it and try again. Also make sure you have restarted the software after the update.

Else I need more information, because I can not reproduce.

**Comment by penzoiders** [comment]
It's 99% cache issue. I had similar issue when switching to Italian. Even after restarting the software (screen -r and CTRL+C) the new language wasn't showing. I had to completely clear browser cache. Probably best option is to set "disable cache" at the application level to avoid these UX issues.

**Comment by theyosh** [comment]
Closing this. As we are able to add and change languages. Probable cause is browser caching
