### ISSUE TITLE
Can't access via webinterface

### ISSUE THREAD

**Issue by HarcourtA** [theyosh/TerrariumPI#244]
Hi,
I can't access the webinterface today despite having success yesterday. I've set a static IP today and ensure that I'm using the current address but to no avail. This is the script I get:

login as: pi
pi@192.168.1.7's password:
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Jan 23 16:36:35 2019 from 192.168.1.6
pi@raspberrypi:~ $ cd ~/TerrariumPI
pi@raspberrypi:~/TerrariumPI $  sudo ./start.sh
2019-01-23 16:51:56,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server running as user 'pi' at location: http://192.168.1.7:8090

**Comment by theyosh** [comment]
Please try: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi
Without that I cannot help. Paste the screen information here.

**Comment by HarcourtA** [comment]
That just gives me: pi@raspberrypi:~/TerrariumPI $ screen -r
There is no screen to be resumed.

**Comment by theyosh** [comment]
Hmmm that is strange. Then could you try the following at the location /home/pi/TerrariumPI

`python terrariumPI.py`

That should then give more information

**Comment by HarcourtA** [comment]
Apologies it has taken so long for me to reply- it's been a manic week.
I get the following feedback:

pi@raspberrypi:~ $ /home/pi/TerrariumPI
-bash: /home/pi/TerrariumPI: Is a directory
pi@raspberrypi:~ $ python terrariumPI.py
python: can't open file 'terrariumPI.py': [Errno 2] No such file or directory

**Comment by Kargha** [comment]
@HarcourtA You have to type 

`cd /home/pi/TerrariumPI`

to go to the /home/pi/TerrariumPI folder, and then do the 

`python terrariumPI.py`

The reason you are getting the "No such file or directory" error is because you are not in the folder where the file is located.

**Comment by HarcourtA** [comment]
Thank you very much Kargha- output as follows:

Traceback (most recent call last):
  File "terrariumPI.py", line 26, in <module>
    terrariumEngine = terrariumEngine()
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 127, in __init__
    self.get_weather)
  File "/home/pi/TerrariumPI/terrariumWeather.py", line 425, in __new__
    return weather_source(source, temperature_indicator, windspeed_indicator, callback)
  File "/home/pi/TerrariumPI/terrariumWeather.py", line 40, in __init__
    self.set_source(source,True)
  File "/home/pi/TerrariumPI/terrariumWeather.py", line 189, in set_source
    self.update(refresh)
  File "/home/pi/TerrariumPI/terrariumWeather.py", line 137, in update
    self.callback(socket=True)
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 598, in get_weather
    data = self.weather.get_data()
AttributeError: 'terrariumEngine' object has no attribute 'weather'

**Comment by HarcourtA** [comment]
It's a 3 model B+
Oh no! Hope it can be sorted!!

**Comment by theyosh** [comment]
@HarcourtA could you subscribe to #246 ? Because there I explained a temporary solution. You have both the same error....

**Comment by HarcourtA** [comment]
I did a git pull and that has seemingly fixed my issue, just connecting up the energenie pi mote now

Thanks a lot for your help!!

**Comment by theyosh** [comment]
Cool closing this issue
