### ISSUE TITLE
Cant access web dashboard

### ISSUE THREAD

**Issue by kronnofatal1ty** [theyosh/TerrariumPI#250]
Hi, i'm new to this projects and i followed your tutorial step by step and when i'm trying to access the web dashboard always keep saying connection refused and i'm kinda stuck here.
Can someone say what RPI version your using and which linux distro?
I'm frying my head for 3 days and can't get any answers. Thank you and btw great project ;)

**Comment by kronnofatal1ty** [comment]
![51544751_240133996877322_4811318490642251776_n](https://user-images.githubusercontent.com/47385570/52342691-faab9100-2a0d-11e9-85ef-e4d380b87783.jpg)
![51604595_245352126352245_2072736450952036352_n](https://user-images.githubusercontent.com/47385570/52342693-fb442780-2a0d-11e9-9cc8-57e9516b6c47.jpg)

**Comment by kronnofatal1ty** [comment]
im using Raspbian Strecht too. I've tested with RPI 3 and 3B+ same result as i posted

**Comment by theyosh** [comment]
Please rerun the installer. The python module emails is missing, so the installer did not run fully.

**Comment by Kargha** [comment]
That's really odd. I mean, it's clearly missing the python email module... Are you using regular Stretch or Stretch Lite? Apparently the regular stretch (with desktop and recommended software) doesn't seem to work.

**Comment by kronnofatal1ty** [comment]
The oddest thing is during the installation. When trying to install the required software (with stretch lite and desktop version) the errors are the same. ssl errors and no matching distribution found errors.
I know that he keeps trying till the modules are installed. Im going to try to install manually the packages to check if it makes any difference. And going to portforwarding on my router.

**Comment by kronnofatal1ty** [comment]
![51844983_751595355226687_7479200403658113024_n](https://user-images.githubusercontent.com/47385570/52360085-183f2180-2a33-11e9-93aa-484791e5ad36.jpg)

**Comment by kronnofatal1ty** [comment]
with the stretch lite is the same errors

**Comment by theyosh** [comment]
Hmmm it is a bit small, but I can see something like that python 2.7 is somewhere depricated.

So could you try the following: `sudo ./install.sh 3` the 3 will install it as python 3. But, then you also need to install the software either manual with: `sudo ./start.sh 3` or change the `/etc/rc.local` file by adding the 3 to the startup command.

**Comment by kronnofatal1ty** [comment]
i did what you said with the command ./install.sh 3
Everything was running smoothly till the last 3 packages.
Again SSL errors

**Comment by kronnofatal1ty** [comment]
Bad handshake: SysCallError(104, 'ECONNRESET')

**Comment by kronnofatal1ty** [comment]
Im going to test that with strecht lite. ill keep u up

**Comment by kronnofatal1ty** [comment]
![problem](https://user-images.githubusercontent.com/47385570/52364366-f0ed5200-2a3c-11e9-918a-0f373edb3b75.jpg)

Now i'm dealing with this. Any help?

**Comment by theyosh** [comment]
Yes, this is somewhat a known issue: https://github.com/theyosh/TerrariumPI/wiki/Known-issues#python3-numpy-import-error

In short run: `sudo pip3 uninstall -y numpy`

But the installer should take care of that....

**Comment by kronnofatal1ty** [comment]
When you solve a problem more appear lol
ImportError: cannot import name 'PiCamera'

**Comment by kronnofatal1ty** [comment]
solved. just deleted the imports from camera

**Comment by theyosh** [comment]
Again, you are missing modules. Please read: https://github.com/theyosh/TerrariumPI/issues/246#issuecomment-457920167

I can not fix this, as somehow the installation is failing. I have installed more then 100 times now, and it is always working. So the issue is somewhat outside my control

**Comment by Kargha** [comment]
@theyosh Could it potentially be connected to lack of power? I know I've had problems with my PI sometimes when doing CPU and read/write intensive tasks if I haven't had a stable enough power source (it loved to turn off my wi-fi mid-downloads and such sometimes).

**Comment by theyosh** [comment]
@Kargha I do not have enough knowledge about that. It sounds reasonable that heavy CPU usage will use more power. And the installation of the python packages is all compile work. So that could be an issue.

But at the same time there are lot of people having issues due to a 'broken' SD card. And swapping to a new SD card fix the issues. So I am more tending to a broken SD card than a power issue. Even when there are not yet SD card errors in the OS.

**Comment by theyosh** [comment]
@kronnofatal1ty is your issue fixed? Then this issue can be closed?
