### ISSUE TITLE
Exclude sensor from average calculation

### ISSUE THREAD

**Issue by jornobe** [theyosh/TerrariumPI#251]
Is it possible to somehow exclude sensors from the average calculated values shown on the dashboard?
In my case there is one in the pool which is not relevant to the average temperature calculation.

**Comment by theyosh** [comment]
Technically this can be made. But I am struggling with the interface. The sensor settings page is rather full already. So adding more settings, will not fit well.

So for now I am thinking of that this has to be setup outside my web interface. So it has to be a manual config change. I will make this first, as this is the easiest to do right now. And add a FAQ item explaining how to setup

**Comment by AndrejWeber** [comment]
That sounds great!
But then it should also not shown on display.
For me: I have a DHT22 near the raspi, just to know the temperature of electronics cabinet. In the moment it is calculated to average of terrarium.

**Comment by theyosh** [comment]
Yesh! Will add an badge to the graph that is excluded...

**Comment by theyosh** [comment]
Ok, just added new code that make this possible... So here are the install instructions.

- `git pull` (on the master branch)
- `sudo ./install.sh` ( add 3 if running python 3) (New oled library is used, so new python modules needs to be installed)
- In the settings file, you can add the following line to a sensor below `[sensor_SOME_ID]`
`exclude_avg = true`
- restart Terrariumpi
- clear browser cache and reload

This will add a blue badge above the graph of the sensor is excluded. It will not show a badge on the average graphs.

**Comment by theyosh** [comment]
And here is the Wiki: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-exclude-a-sensor-from-average-calculation

**Comment by jornobe** [comment]
Nice! Highly appreciated!

**Comment by Natrixz** [comment]
I noticed the badged don't always show up on the sensor page, I excluded two (well now just one) sensor but it doesn't have the badge

**Comment by theyosh** [comment]
For me it is working like expected. The badge is there when the sensor is excluded from average.

What does the following url shows at your system: `http://[pi]:8090/api/sensors` . There it should also say exclude_avg = true

**Comment by Natrixz** [comment]
That does show the badge as it should be, actually it appears to be fixed after the latest git pull and restart =)
So ignore my observation

**Comment by theyosh** [comment]
No problem.

**Comment by stuartabrown** [comment]
Just a note to say that the `excl. avg` badge seems to be permentant for me too in the latest release:
![screen shot 2019-02-17 at 20 34 05](https://user-images.githubusercontent.com/44773993/52918826-9339ef00-32f3-11e9-92b7-f9dbf5d0aa4b.png)
Badge appears but config says it shouldn't because sensor isn't excluded
![screen shot 2019-02-17 at 16 34 37](https://user-images.githubusercontent.com/44773993/52918825-8cab7780-32f3-11e9-95df-7123fdf30f76.png)

**Comment by Raerion** [comment]
Nice feature, immediately started using it!
For me only one of three temperatures is really relevant and now I can see this temperature diectly on the dashboard.

_Some ideas:_
Maybe if you ever decide to rework the dashboard one could think about a configurable approach (enable disable items like water consumpiton/power consumption/environment pane/audio) and add sensors to groups which will be averaged (sensor settings like: `show_on_dash = True` and `average_group = Temperature1`). I'm thinking about cases where you have something like three air temperatures, two water temperatures and maybe a cabinet tempearure one could make three groups and have three dashboard displays for this groups.

**Comment by theyosh** [comment]
> _Some ideas:_
> Maybe if you ever decide to rework the dashboard (like #260 ...?) one could think about a configurable approach (enable disable items like water consumpiton/power consumption/environment pane/audio) and add sensors to groups which will be averaged (sensor settings like: `show_on_dash = True` and `average_group = Temperature1`). I'm thinking about cases where you have something like three air temperatures, two water temperatures and maybe a cabinet tempearure one could make three groups and have three dashboard displays for this groups.

Nice idea, but I am a very bad UX designer... so I think this will not happen soon or maybe never.. To make it that flexible, is a lot of programming... So I am sorry, for now, do not get your hopes that up...

**Comment by theyosh** [comment]
@stuartabrown Just to be sure. After manual changing settings, you have to restart. Did you do so? Settings file only be read during startup. When changing the settings in the UI, I will reload it in code. But this exclude setting is a manual setting change and requires a restart

**Comment by theyosh** [comment]
Found some scenarios where the badge would not hide properly. That is fixed now

**Comment by stuartabrown** [comment]
@theyosh have pulled the latest release.  Behaviour was aas per before but if i set `exclude_avg`  to `True`, restart, then set to `false` and restart everything is ok :)

**Comment by theyosh** [comment]
Closing as it is working like expected
