### ISSUE TITLE
Fahrenheit/Celsius issue

### ISSUE THREAD

**Issue by Janson777** [theyosh/TerrariumPI#252]
Big thanks for TerrariumPi.  Will upload pics when I get my system finished.  I am having an issue with 1-wire temp sensors reporting results in Celsius when the system is set to Fahrenheit (refer to sys_log_errors.jpg).  The first value highlighted is actually about 79F-80F.  Not sure if I am missing something or it is a bug.

![sys_log_errors](https://user-images.githubusercontent.com/25240705/52507655-c673d400-2bb7-11e9-9731-974f02790148.jpg)
![sensor settings](https://user-images.githubusercontent.com/25240705/52507704-f02cfb00-2bb7-11e9-95f4-341d7245dfc4.JPG)
![sensor temps](https://user-images.githubusercontent.com/25240705/52507708-f327eb80-2bb7-11e9-85b8-a7c67cb4df5d.JPG)
![sys_settings](https://user-images.githubusercontent.com/25240705/52507724-ffac4400-2bb7-11e9-83f3-cf90993a6bc0.JPG)

**Comment by theyosh** [comment]
Ah, this looks like a bug. But could you try one more thing? When you put it to Fahrenheit and save the system setting. Then restart the software. If that will give the right value, then I have a clue where to look

**Comment by Janson777** [comment]
Went through the log-out and restart process.  The errors still appear to still be there.

![sys_log](https://user-images.githubusercontent.com/25240705/52509446-c8409600-2bbd-11e9-816f-e72fbde03352.JPG)
![sensor temps](https://user-images.githubusercontent.com/25240705/52509441-c545a580-2bbd-11e9-852b-2db17862e9dc.JPG)

**Comment by theyosh** [comment]
Crap, found the problem.. I had this fixed before, but in a different branch. Forgot to merge. But the fix is already there.

So you can now do a `git pull` and it should work. If you have then new errors, then please rerun the installer `sudo ./install.sh`

**Comment by theyosh** [comment]
So, I can confirm that the latest code has fixed this. The only thing is that you have to reload the hole page after changing the temperature indicator.
