### ISSUE TITLE
Notifications and category

### ISSUE THREAD

**Issue by Natrixz** [theyosh/TerrariumPI#258]
Hi Yosh,

You recently added the failed login for me, which is awesome!

However it's noted under System Warning. When I enable this, everytime my misting system turns on it will send me a dozen or so messages because of erratic readings....
Is it possible to create some category for the failed login?

With kind regards,
Natrixz

**Comment by theyosh** [comment]
Done, do a `git pull`, restart and clear browser cache. You should have a new authentication notification type. It does what is says ;)

**Comment by Natrixz** [comment]
It works perfectly! =)

Thank you Yosh!

**Comment by theyosh** [comment]
Thanks for the feedback
