### ISSUE TITLE
After latest 'pull', door status not posting webhook

### ISSUE THREAD

**Issue by Swiftnesses** [theyosh/TerrariumPI#261]
Hi @theyosh,

Did a pull and reinstall last night, all went well.

I noticed that my webhooks are no longer firing on door open / closed, could this be related to the refactor?

**Comment by Swiftnesses** [comment]
Sorted it, there was a session in my Node Red, cleared the session file and it's working!

**Comment by theyosh** [comment]
Thanks for the feedback
