### ISSUE TITLE
Power_Switch referenced before assignment - TerrariumPI won't start

### ISSUE THREAD

**Issue by Natrixz** [theyosh/TerrariumPI#262]
Traceback (most recent call last):
  File "/home/nick/TerrariumPI/terrariumPI.py", line 26, in <module>
    terrariumEngine = terrariumEngine()
  File "/home/nick/TerrariumPI/terrariumEngine.py", line 135, in __init__
    self.__load_power_switches()
  File "/home/nick/TerrariumPI/terrariumEngine.py", line 285, in __load_power_switches
    if power_switch.get_id() in prev_state:
UnboundLocalError: local variable 'power_switch' referenced before assignment

After the latest pull it won't start anymore :(
(wanted to test the new notifications haha)

Edit: Rolling back 1 change will fix the startup. so it's commit 239
(https://github.com/theyosh/TerrariumPI/commit/f7a339c061b066602257fc0bc2bfefa2a5fa85fc) messing it up =)

**Comment by theyosh** [comment]
Damm, thanks! I do like the remark about the rollback. That makes it indeed clear where the fuckup it :D
Should work again

**Comment by Natrixz** [comment]
Your welcome! =)

Fix is confirmed ;)
