### ISSUE TITLE
SHT31-D incorrect readings

### ISSUE THREAD

**Issue by GeneralTso0219** [theyosh/TerrariumPI#263]
Hi, I've been putting together a TerrariumPI build and have been having problems with getting it to report anything other than about -46 degrees for temperature and -6 degrees for humidity with my SHT31-D.

**Comment by GeneralTso0219** [comment]
Despite the board documentation stating it can support 5v, you need to have it on the 3v to get it to read properly.

This was my hardware error.

**Comment by theyosh** [comment]
Thanks for the feedback
