### ISSUE TITLE
Chirp address format? 

### ISSUE THREAD

**Issue by grantlarouere** [theyosh/TerrariumPI#265]
@theyosh , I've bought a Chirp sensor and can use i2cdetect and i2cdump to see that the sensor is connected correctly, but I'm still getting "null" as the current value.  What is the address supposed to be?  0x20, the hardware address, or 3,5 the GPIO pins of SDA and SCL?  I want to make sure that I'm configuring it correctly so I can troubleshoot better.

**Comment by theyosh** [comment]
The address should be just 20.

As you see your sensor with i2cdetect on 0x20, the address is just the last numer

**Comment by grantlarouere** [comment]
Great. It's working perfectly now, thanks.

**Comment by theyosh** [comment]
Closing now and updated the Hardware wiki with more information
