### ISSUE TITLE
Denkovi V2

### ISSUE THREAD

**Issue by Natrixz** [theyosh/TerrariumPI#275]
Right, so I have reinstalled my entire PI.
Testing now =)

**Comment by Natrixz** [comment]
PS. I have to run the java -jar Denkovi.jar as sudo or it won't do as instructed and give a weird error

**Comment by Natrixz** [comment]
It doesn't switch the relay yet, nothing happens so far.
Any logs you want me to show?

**Comment by theyosh** [comment]
Hmm,

first make sure the modules ftdi_sio and usbserial are unloaded. `sudo rmmod usbserial` and `sudo rmmod ftdi_sio`.

Then try: java -jar DenkoviRelayCommandLineTool.jar [DEVICE SERIAL NUMBER or ID] [RELAY COUNT] [RELAY NUMBER] status

Where [DEVICE SERIAL NUMBER or ID] is 0
Where [RELAY COUNT] is 4 8 or 16
Where [RELAY NUMBER] is 1 for testing

And I have created new switch types. So make sure you use the right denkovi power switch type when adding to terrariumpi. And I also add some extra debug. So could you do a `git pull` and see what that does?

**Comment by Natrixz** [comment]
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ java -jar DenkoviRelayCommandLineTool.jar 0
Error: One or more parameters misssing...
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ java -jar DenkoviRelayCommandLineTool.jar 0 status
Error: One or more parameters misssing...
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ java -jar DenkoviRelayCommandLineTool.jar 0 4v2 status
Error: One or more parameters misssing...
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ java -jar DenkoviRelayCommandLineTool.jar 0 4v2 status 0
Error: This serial number is too short. MCP Relay Boards serial numbers are 10 symbols!
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ java -jar DenkoviRelayCommandLineTool.jar 0 4v2 0 status
Error: This serial number is too short. MCP Relay Boards serial numbers are 10 symbols!
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ java -jar DenkoviRelayCommandLineTool.jar 0001691995 4v2 0 status
Error: Relay Board with this serial number or ID is not found!
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ java -jar DenkoviRelayCommandLineTool.jar 0001691995 4v2 status
Error: One or more parameters misssing...
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ sudo java -jar DenkoviRelayCommandLineTool.jar 0001691995 4v2 status
Error: One or more parameters misssing...
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ sudo java -jar DenkoviRelayCommandLineTool.jar 0001691995 4v2 status 0
Error: Invalid command type!
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ sudo java -jar DenkoviRelayCommandLineTool.jar 0001691995 4v2 0 status
0
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ sudo java -jar DenkoviRelayCommandLineTool.jar 0 4v2 0 status
Error: This serial number is too short. MCP Relay Boards serial numbers are 10 symbols!
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ sudo java -jar DenkoviRelayCommandLineTool.jar 0001691995 4v2 0 status

**Comment by theyosh** [comment]
Not sure how to read all this..  So then I need to know what the working command is for you. So could you just try according this page to get it working: http://denkovi.com/denkovi-relay-command-line-tool

So that you can pass the right command to me, and then I try to incorperate it.

**Comment by Natrixz** [comment]
The working command for me is;
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ sudo java -jar DenkoviRelayCommandLineTool.jar 0001691995 4v2 0 status
0
That returns the status as 0 when it's off and as 1 when it's one

Using;
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ sudo java -jar DenkoviRelayCommandLineTool.jar 0001691995 4v2 0 1
Will turn switch 1 on
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ sudo java -jar DenkoviRelayCommandLineTool.jar 0001691995 4v2 0 0
will turn switch 1 off

**Comment by theyosh** [comment]
could you also paste the output of the status where you can read out the serial id? Would help me for parsing the right data

**Comment by Natrixz** [comment]
sudo java -jar DenkoviRelayCommandLineTool.jar list
Serial number [Description] [ID]
FTDI devices:
MCP devices:
0001691995 [Microchip Technology Inc. MCP2200 USB Serial Port Emulator null] [id=0]

**Comment by theyosh** [comment]
Thanks a lot. And is sudo always needed :( ?

**Comment by Natrixz** [comment]
Sadly; yes :(
Otherwise it gives some weird error

**Comment by theyosh** [comment]
And I see that you also enter '4v2' where the documentation says that '4' should be enough. Could you check this?

**Comment by Natrixz** [comment]
Natrixz@terrarium02:~/TerrariumPI/DenkoviRelayCommandLineTool $ sudo java -jar DenkoviRelayCommandLineTool.jar 0001691995 4 0 status
Error: FTDI Relay Boards serial numbers are exact 8 symbols. Please check if this serial number is MCP relay board!

4v2 is always needed for the v2's is appears

**Comment by theyosh** [comment]
New code, new round, new bugs :P

**Comment by Natrixz** [comment]
2019-03-09 16:19:31,458 - WARNING - terrariumBluetoothSensor - Bluetooth scanning is not enabled for normal users or there are zero Bluetooth LE devices available.... bluetooth is disabled!
Set power switch state cmd:
['sudo', 'java', '-jar', 'DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar', '0', '4', '1', '0']
[sudo] password for natrixz:
Set state done!
Set power switch state cmd:
['sudo', 'java', '-jar', 'DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar', '0', '4', '2', '0']
Set state done!
Set power switch state cmd:
['sudo', 'java', '-jar', 'DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar', '0', '4', '3', '0']
Set state done!
Set power switch state cmd:
['sudo', 'java', '-jar', 'DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar', '0', '4', '4', '0']
Set state done!
2019-03-09 18:47:33,000 - INFO    - terrariumWebserver   - Running webserver at :::8090
global name 'address' is not defined
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/nick/TerrariumPI/terrariumEngine.py", line 561, in __engine_loop
    display_message = ['%s %s' % (_('Uptime'),terrariumUtils.format_uptime(system_data['uptime']),),
UnboundLocalError: local variable 'system_data' referenced before assignment
2019-03-09T18:47:33Z <Greenlet at 0x6c2d0a48: <bound method terrariumEngine.__engine_loop of <terrariumEngine.terrariumEngine object at 0x76a1b9d0>>> failed with UnboundLocalError


I had to fill in my sudo password but it still throws the errors

**Comment by theyosh** [comment]
Ok, what will happen when you add the following line to: `/etc/sudoers.d/terrariumpi`

`pi ALL=(ALL) NOPASSWD: java -jar DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar`

And reboot. I hope this will make it run with sudo without password

**Comment by Natrixz** [comment]
Crap, I pasted it in too quickly and didn't notice the full path missing...have to fix my sudoers.d file now lol

**Comment by theyosh** [comment]
Sorry, I had not tested it. So I fixed in my installer now. And it seems that my old hardware is also supported. So I can do some testing my self... but as you said that it is already working when sudo password is added, then I expect that with the fixed sudoers file, that it should work.

**Comment by Natrixz** [comment]
Yeh it will take me a bit to fix it, damnit haha
(I never set a root password so it's impossible to login with root -,-)
Need to boot it on my linux system and fix the sudo'ers file by hand lol

**Comment by Natrixz** [comment]
Alright; it's fixed, let's see if it works with the correct line in the file =)

**Comment by Natrixz** [comment]
It's still asking for a password lol

**Comment by Natrixz** [comment]
Alright, I see the issue;
It's calling it as root, so can you remove the sudo from the commandline? =)
Let's try that

**Comment by theyosh** [comment]
Ok, this will take some more time then... strange.. and my device is not supported. But I also saw this:

Error: Invalid relay board type! Currently supported types are: 4 - for USB 4 Relay FT245RL chipset, 8 - for USB 8 Relay FT245RL chipset, 16 - for USB 16 Relay FT232RL chipset, 4v2 - for USB 4 Relay MCP2200 chipset and 4v8 for USB 8 Relay MCP2200 chipset!

That explains the 4v2 value

**Comment by Natrixz** [comment]
Yeh indeed, i stumbled across that too :P 
Weird it still asks for the password tho...let's see if I can figure out why

**Comment by theyosh** [comment]
I have an idea.... but again... playing with sudoers is tricky.

1. You need to start the java tool with root rights, therefore sudo.
2. The terrariumpi software is running as normal user (pi).
3. So pi needs to do a sudo command without a password. Then I will get to:

`/usr/bin/sudo /usr/bin/java -jar DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar`

And in my code, I have to add a full path to sudo. And then I am wondering if more parameters on the command line will work...

**Comment by Natrixz** [comment]
Nope that doesn't work, I tried it lol

**Comment by theyosh** [comment]
Add '*' to the command line after .jar. That worked for me

**Comment by theyosh** [comment]
`pi  ALL=(ALL) NOPASSWD: /usr/bin/java -jar DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar *`

**Comment by Natrixz** [comment]
Yep that works.
just adding /usr/bin/java works too but is very open in case the Pi does ever get compromised

**Comment by theyosh** [comment]
So, another update. The installer will add new lines to the sudoers file. So that should be fixed.

And it should also see the different boards using v2 if needed. Could you test that? Just update the code with git pull and restart.

**Comment by Natrixz** [comment]
Pulled the latest update and restarted; so far so good and it appears to work fine!

**Comment by Natrixz** [comment]
Quick question; isn't it faster/easier to do denkovi.jar all status
so you get all the status back at once and then take out the correct reading per switch?
(Then you don't have to do 4/8/16 individual status pulls)

**Comment by theyosh** [comment]
It is faster to read out once, but the problem then rises that I have to cache and share the data between different objects in code. I am currently doing that for sensors, but that is something I can test. And adding caching without testing is hard. But of course, it is way more efficient to do that. Main goal is now to get it working on the most easiest way to implement.

So I just did another code update. Could you do a git pull once more and restart?

**Comment by Natrixz** [comment]
Still works fine =)

**Comment by theyosh** [comment]
yes :). But that will not be today I think. I would like to think a bit more about how to do that.

**Comment by Natrixz** [comment]
No worries!
I will leave it hooked up to one of my test Pi's =)

Already happy that it works like it does now ;)

**Comment by theyosh** [comment]
Added status caching... untested :)

**Comment by Natrixz** [comment]
It's currently not switching the relay's anymore, so appears broken :P

**Comment by theyosh** [comment]
I added some debug code again. But you should see some errors....?

**Comment by Natrixz** [comment]
Running set hardware state cmd: ['/usr/bin/sudo', '/usr/bin/java', '-jar', 'DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar', '0001691995', '4v2', '0', '1']
Get hardware state cache data
Get cache key 09b28e73b518f69edbb275674f0b230a
None
Get cache key 09b28e73b518f69edbb275674f0b230a
IS running: False
Get cache key 09b28e73b518f69edbb275674f0b230a
Get cache key 09b28e73b518f69edbb275674f0b230a
Running cmd: ['/usr/bin/sudo', '/usr/bin/java', '-jar', 'DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar', '0001691995', '4v2', 'all', 'status']
Clear caching
Get cache key 09b28e73b518f69edbb275674f0b230a
Clear caching DONE!
Got data: *0000*

**Comment by Natrixz** [comment]
Get cache key 09b28e73b518f69edbb275674f0b230a
Get cache key 09b28e73b518f69edbb275674f0b230a
Final state data at address : 1
Running set hardware state cmd: ['/usr/bin/sudo', '/usr/bin/java', '-jar', 'DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar', '0001691995', '4v2', '0', '1']
Clear caching
Get cache key 09b28e73b518f69edbb275674f0b230a
Clear caching DONE!
Get hardware state cache data
Get cache key 09b28e73b518f69edbb275674f0b230a
None
Get cache key 09b28e73b518f69edbb275674f0b230a
IS running: False
Get cache key 09b28e73b518f69edbb275674f0b230a
Get cache key 09b28e73b518f69edbb275674f0b230a
Running cmd: ['/usr/bin/sudo', '/usr/bin/java', '-jar', 'DenkoviRelayCommandLineTool/DenkoviRelayCommandLineTool.jar', '0001691995', '4v2', 'all', 'status']
Got data: *1000*

**Comment by theyosh** [comment]
Euh, I did change that the entered address is lowered by one. I expect that values from 1 till 4 including is entered. And the code uses 0 for first switch. At least that is the documentation saying... you experience differently?

**Comment by Natrixz** [comment]
Well for some reason the address layout is all messed up....
I thought it was caching but clearing the cache didn't help.
Switching address 
0 will switch 3
1 will switch 1
2 will switch 1
3 will switch 2

**Comment by theyosh** [comment]
Ok, changed some back. And saw some strange issue with printing. So could be that it will work now again.

I am looking for the line: 'Final state data at address' and then some numbers.

**Comment by theyosh** [comment]
But, could you use the numbers 1 till 4? And not starting at zero? Because starting at 1 is more human and more understandable for non tech people

**Comment by Natrixz** [comment]
Order is correct now, BUT it's still switching off after a few seconds

**Comment by theyosh** [comment]
Could you please post a full run debug? Like a screenshot? Because all this small pieces off info is confusing... And I need the debug code to see what is happening.

**Comment by Natrixz** [comment]
![Screenshot (86)](https://user-images.githubusercontent.com/7376057/54154126-76e82880-4441-11e9-8581-3335b9dd2e93.png)
![Screenshot (85)](https://user-images.githubusercontent.com/7376057/54154127-7780bf00-4441-11e9-964e-0b5e047e1ea2.png)
Im not clicking switch number 2

**Comment by theyosh** [comment]
YESH! En we doen het lekker in NL :P Alleen de eerste power switch gaf de juiste status terug. Switch 2 t/m 4 dus niet, en dat geeft rare effecten. Heb dat nu aangepast en dat zou nu beter moeten werken.

**Comment by Natrixz** [comment]
Oke is ff kijken wat er gebeurt na een git pull =)

**Comment by Natrixz** [comment]
Alle schakelaars functioneren nu zoals het hoort en ze blijven ingeschakeld =)

**Comment by theyosh** [comment]
Mooi.... en er zit nu dus ook caching in van de statussen... 1 keer per 30 seconden worden deze opgehaald tenzij er geklikt wordt. Extern schakelen duurt 30 seconden voordat dat opgepakt wordt nu

**Comment by theyosh** [comment]
Ah, ik weet niet hoe veel tijd het kost om dat java te starten.... ik zal ff wat timer code toevoegen

**Comment by Natrixz** [comment]
Als ik extern schakel zie ik dat de software ook nog een keer 2 0, 1 0, etc uitvoert.
Kun je om tijd te besparen niet gewoon de cache leeg gooien en invullen met de huidige waarde?
(of een optie om het gewoon keihard te overrulen en terug te zetten naar de value zoals in de cache?)

**Comment by theyosh** [comment]
Ok, er zit nu een update timer in... bij mij duurt het 5 sec voordat ik een error krijg dat mijn board niet ondersteund is.... maar dat is wel stevig... 5 sec

**Comment by Natrixz** [comment]
Java meuk....ik git pull nu :)

**Comment by Natrixz** [comment]
Krijg overigens een hele berg errors na een restart
2019-03-11 20:42:05,108 - ERROR   - terrariumSwitch      - Error setting hardware state for switch type denkovi_v2_4, with error: 'terrariumPowerSwitchDenkoviV2_4' object has no attribute '_terrariumPowerSwitchDenkoviV2__cache'
2019-03-11 20:42:11,258 - ERROR   - terrariumSwitch      - Error setting hardware state for switch type denkovi_v2_4, with error: 'terrariumPowerSwitchDenkoviV2_4' object has no attribute '_terrariumPowerSwitchDenkoviV2__cache'
2019-03-11 20:42:17,408 - ERROR   - terrariumSwitch      - Error setting hardware state for switch type denkovi_v2_4, with error: 'terrariumPowerSwitchDenkoviV2_4' object has no attribute '_terrariumPowerSwitchDenkoviV2__cache'
2019-03-11 20:42:23,619 - ERROR   - terrariumSwitch      - Error setting hardware state for switch type denkovi_v2_4, with error: 'terrariumPowerSwitchDenkoviV2_4' object has no attribute '_terrariumPowerSwitchDenkoviV2__cache'
2019-03-11 20:42:29,698 - ERROR   - terrariumSwitch      - Error setting hardware state for switch type denkovi_v2_4, with error: 'terrariumPowerSwitchDenkoviV2_4' object has no attribute '_terrariumPowerSwitchDenkoviV2__cache'
2019-03-11 20:42:29,000 - INFO    - terrariumWebserver   - Running webserver at :::8090

**Comment by theyosh** [comment]
hmmm... nieuwe pull

**Comment by Natrixz** [comment]
Errors zijn weg, na een reboot gaan alle switches terug naar "uit" status

**Comment by theyosh** [comment]
Dat is default... bij het opstarten gaat alles uit. En dan moeten ze de status aannemen op basis van de instellingen. Maar het werkt nu toch nog steeds?

**Comment by Natrixz** [comment]
Oke dan heb ik niets gezegd xD
Jep alles werkt nu prima! =)

**Comment by theyosh** [comment]
Goed, dan laat ik het eerst nog ff zo. Want eigenlijk moeten we nu nog ff zien of ze ook schakelen als ze gebruikt worden voor lampen of verwarming.. Als je nog zoiets kunt testen dan heel graag. Ik ga ervan uit dat het wel goed gaat... maar meten is weten :)

**Comment by theyosh** [comment]
En hoe veel tijd kost het nu om ze uit te lezen?

**Comment by Natrixz** [comment]
Gemiddeld 4 seconden, valt reuze mee dus =)
Ik ga wel even een lamp en verwarming aansluiten als valide load om te testen ;)

**Comment by theyosh** [comment]
dan scheelt het wel om ze allemaal in 1 keer uit lezen... 16 * 4 sec is wel erg lang...

**Comment by Natrixz** [comment]
Eh ja....dan ben je ruim een minuut verder :P

**Comment by Natrixz** [comment]
Tot nu toe gaat het schakelen prima, heb er afwisselend 2 aan en uit staan.
Blijven ook netjes aan staan =)

**Comment by theyosh** [comment]
mooi... dan ga ik de code samenvoegen....

**Comment by Natrixz** [comment]
Top! =)
Goed bezig ;)

**Comment by Natrixz** [comment]
Werkt prima!
