### ISSUE TITLE
Capacitive Soil Moisture Sensor - wish

### ISSUE THREAD

**Issue by Rushmonk** [theyosh/TerrariumPI#294]
Hello @theyosh 

if you got a little spare time, is it possible to add this Sensor to TerrariumPi?

https://www.aliexpress.com/item/32882371718.html?spm=a2g0s.9042311.0.0.418a4c4dYbhA1i

Capacitive Soil Moisture Sensor Module v1.2

Greetings

**Comment by vacuumboots** [comment]
That sensor is analog, so it requires an addon to be read: https://github.com/theyosh/TerrariumPI/wiki/Hardware#analog-sensors
