### ISSUE TITLE
TerrariumPi autofilling out switches for Wemo devices

### ISSUE THREAD

**Issue by furiousg3orge** [theyosh/TerrariumPI#298]
I am configuring all my devices but I'm noticing that when I reboot the PI that it will pull and populate my wemo switches (for my home) into the switches fields. I haven't set these up or have ever pointed terrariumPI to these switches. Can anyone help me figure this out or, if there is a fix, point me in that direction? My search came up empty.

**Comment by theyosh** [comment]
Hi,

this is standard behaviour. My software will scan for certain powerswitches and will add them when found. There is an option to exclude those power switches AFTER you have saved them once: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-exclude-a-power-switch

**Comment by theyosh** [comment]
Closing due to no response. So I expect that the excluding option is working
