### ISSUE TITLE
Reboot pi from dashboard

### ISSUE THREAD

**Issue by funware84** [theyosh/TerrariumPI#306]
Is there a posibility to add an option to reboot the pi using the ui?

**Comment by theyosh** [comment]
Ok, done! Do a `git pull` and then rerun the installer according to the https://github.com/theyosh/TerrariumPI#updating .

This will give you a reboot button on the system settings page. You will have to confirm the action, and you need to be authenticated to make the call to the backend.

This is an early version. The next version will have some kind of overlay, which will try to reconnect to the server while it is rebooting. And reload when the server is back again.

In the meantime, could you look at: #210 :)

**Comment by theyosh** [comment]
Update, rerun the installer after the update!! Else it will not start

**Comment by tvStatic** [comment]
Would it be possible to add an option to shutdown the Pi in the same place?

**Comment by theyosh** [comment]
Done! And we have a fancy reboot screen ;)

**Comment by theyosh** [comment]
Closing due to implemented
