### ISSUE TITLE
Syntax error while updating to 3.9.7

### ISSUE THREAD

**Issue by prcdslnc13** [theyosh/TerrariumPI#316]
I started the update and things were running fine until my terminal went red and froze. I exited out and restarted the ssh session and tried to re-run the update and now get this every time. I even tried a fresh git-clone

Current default time zone: 'America/Chicago'
Local time is now:      Sun Jul 28 11:25:27 CDT 2019.
Universal Time is now:  Sun Jul 28 16:25:27 UTC 2019.

./install.sh: 225: ./install.sh: Syntax error: "(" unexpected (expecting ")")

**Comment by theyosh** [comment]
Hmm looks like a corrupted file.... here it is working fine. Try:

```
rm install.sh
git checkout install.sh
```
And retry to run the installer.

**Comment by theyosh** [comment]
Hmmm, if a fresh clone is not working.... Then I am afraid that the SD card is corrupt. The installer is working for me on python 2 and 3.

**Comment by prcdslnc13** [comment]
yea, the checkout didn't work either. Is there an easy way to port all my settings and configuration to a fresh Rasbian install?

**Comment by theyosh** [comment]
Yesh! https://github.com/theyosh/TerrariumPI/wiki/FAQ#which-files-to-backup

Basically, backup those files, and put them in the new install and should be good to go

**Comment by prcdslnc13** [comment]
Bah How did I miss that. Thanks so much man.
