### ISSUE TITLE
Time is displayed incorrectly

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#33]
Hi, why is always an incorrect time displayed I do something wrong, can you fix it? Thank you very much
![unbenannt](https://user-images.githubusercontent.com/31970192/31738453-0e138688-b44b-11e7-9ab5-946859f6a63d.png)

**Comment by theyosh** [comment]
Quick fix and test. Use on time: 05:59 and off time 23:59.

It is a bug, and I guess it has to do with the time 00:00. So try my suggested times, and see if it is then correct. This will also help solving this bug.

I think 1 minute shift should not be a big problem for now

**Comment by vanessa2013** [comment]
Hi, I have sent you a mail with an update to the German language.
