### ISSUE TITLE
start_x=1 after install (372mb mem available instead of 480mb)

### ISSUE THREAD

**Issue by kr15uk** [theyosh/TerrariumPI#341]
Long story short...
rpi1 with 512mb total
1. Clean flash of raspbian lite + updates
2. git clone and sh install script
3. Hence it's raspbian-lite there's no desktop environment so no thanks on file deletion..
4. 2h later bingo, install done and reboot
5. free -m reports 372mb memory (looks like it upped vram to 128mb)
6. rasps-config memory split to 16 for GPU, reboot - still 372mb
7. nano /boot/config.txt set start_x=0 and it's all good now, back to available 480mb

Not sure if that's a glitch in install script or any dependencies enable x during the install, don't know.
It took good 2h on good old rpi1 so not sure if I'm keen to give another go straight away.
Known case or rpi1 specific?!

If glitch then someone might find this useful - start_x=0 in config.txt

**Comment by theyosh** [comment]
Hi,

yes that is correct. My installer script does add that line: https://github.com/theyosh/TerrariumPI/blob/master/install.sh#L104

I was in the assumption that that is needed to enable the RPI webcam together with the GPU memory. Not sure doh, have not fully tested that. So it could be that now you are not able to use a RPI webcam.

**Comment by theyosh** [comment]
But cool that it works on an old device. As far as I know RPI1 did have some issues in the past

**Comment by theyosh** [comment]
I just tested it and start_x=1 is needed in order to use the Rpi camera. So therefore, I have it enabled by default so it would work out of the box. 

So for now, I leave it as is. This also means, that after an update/re-run of the installer script, it will be put back to start_x=1. I cannot detect changes there and ignore them.
