### ISSUE TITLE
Installer throws error

### ISSUE THREAD

**Issue by Died115** [theyosh/TerrariumPI#347]
Hello,

A lot of times the installer throws :
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
And then hangs.

This could be fixed by aborting everything and then re-running the installer.

A more elegant solution was upgrading the setuptools before installation:

sudo pip install --upgrade setuptools

At least this worked for me :) 

Kind Regards,

**Comment by theyosh** [comment]
Added to the installer so it will upgraded when you install or update my software
