### ISSUE TITLE
Geeni Smart Plug Support?

### ISSUE THREAD

**Issue by xagesz** [theyosh/TerrariumPI#349]
I love that I can use Wemo Switches. Can we get support for Geeni? You can get a smart strip from them with 4outlets and 2 usb plugs that I think would work great with lights, misters, foggers. They are very inexpensive and use them alot in my house.

https://mygeeni.com/products/geeni-surge-smart-wi-fi-4-outlet-2-usb-surge-protector-1

Geeni products are based on TUYA. I have integrated tuya into my house with a homebridge setup and it works perfect with geeni. Would love the option for the strip so that there is only 1 smart device

**Comment by theyosh** [comment]
Hi,

I have looked into this, but I am afraid that supporting those is not an option. As Wemo switches can controlled locally without any user interaction, the  Geeni needs all kind of special software to get secret keys to interact: https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md and https://github.com/clach04/python-tuya/wiki

Also, the TUYA API is not that easy to work with, as it made for resellers. And not end users... :( And I have not seen any easy to implement code.

So sorry, those power switches will not be supported at this moment.
