### ISSUE TITLE
DS18B20 Temp Probes Error After Short Time

### ISSUE THREAD

**Issue by ItsCaptainMorgan** [theyosh/TerrariumPI#361]
I have been trying make my own PI controlled environment for my Royal Python for way too long and have lost the motivation unfortunately.   I love the layout of this project and decided to throw it on my PI with a 5in touch screen.  3 DS18B20 temp probes to get a gradient.  2 GPIO relays: one timer for lighting one controlled by single temp probe.  

While trying to get temperature controlled relays to work I discovered that my temp probes go into error after a short period of time and the sensor displays get stuck.  I also have to have my gpio controlled relay board set to gpio inverse.   Any advise on getting this to work???  See images.
![Log](https://user-images.githubusercontent.com/61852087/76033426-df0d0580-5f01-11ea-9e30-690e114fd0ac.PNG)
![Sensor Settings](https://user-images.githubusercontent.com/61852087/76033430-e2a08c80-5f01-11ea-9fe3-0434bd6e775c.PNG)
![Sensors](https://user-images.githubusercontent.com/61852087/76033431-e46a5000-5f01-11ea-80da-371d437362c1.PNG)
![Switches](https://user-images.githubusercontent.com/61852087/76033433-e59b7d00-5f01-11ea-84bb-b080151a5f50.PNG)

**Comment by Ultameciia** [comment]
If your temp probes aren't reporting it's most likely due to your limit mins and maxes. Your limits are between 20-45c but the probes are reporting 12c so since those values are outside the limit min and max they're being discarded. Open up those limits to say 5-50c and see if they start reporting properly.

**Comment by theyosh** [comment]
@ItsCaptainMorgan this is correct. As @Ultameciia is explaining. Your measured values of 12 degrees are lower than the limits values.

The limits values are there to make sure that measurements are correct. Sometimes some sensors are broken, and give to low or to high values. Then they will be ignored by the limit fields.

The alarm fields are the values where actions needs to be done. Either manual or through the environment system.

so increase you limit values as @Ultameciia suggested and it should work.

@Ultameciia thanks for answering.

**Comment by theyosh** [comment]
@ItsCaptainMorgan Have you solved this? Is this still an issue?

**Comment by ItsCaptainMorgan** [comment]
@Ultameciia @theyosh    This seems to work!   Is there a way to enlarge the temperature reading font size?   I would like to hook this into my 7in touchscreen for the PI but the temp readings are almost impossible to read.

**Comment by theyosh** [comment]
Could you make a screenshot and add some markers of what text you are mention? Most of the design is a template that has fixed font sizes. So it depends on what you want if I can add that.

Mostly I would say, make you own web interface with API calls. So you can create you own kind of dashboard.

**Comment by ItsCaptainMorgan** [comment]
I thought it would be a template but worth the question.  Here are the main text(s) I am referring to.
![Sensors](https://user-images.githubusercontent.com/61852087/76902256-9e01e300-6869-11ea-9b6b-300c6c68cd0a.PNG)

**Comment by theyosh** [comment]
Hmm, that would be creating another hack. I rather do not do that. As I am not a UX designer, I use a predefined template.

So, for now, I am afraid that I cannot make a variable font size for the graphs.

Also, I think if you are handy enough, to make your own interface with the API data that is available. https://github.com/theyosh/TerrariumPI/wiki/API

**Comment by ItsCaptainMorgan** [comment]
Okay!   Thanks for the help!!  Seems to be working how I need for now.  Now for electronics enclosure.
