### ISSUE TITLE
4-Channel 5V Relay Module

### ISSUE THREAD

**Issue by nastea1** [theyosh/TerrariumPI#368]
I saw this wasn't listed on hardware, it's a simple four-channel relay. If it's already supported, let me know but I didn't see anything for it. Currently used in a python script setup that fires a 5v pump to fill a smaller reservoir when it's determined it is low. I'd like to expand it, to control my lights since it can support AC circuits. In the python script, the relay is triggered as a simple LED on/off to trigger the relay when it meets conditions. Each channel has a single pin IN.

http://wiki.sunfounder.cc/index.php?title=4_Channel_5V_Relay_Module

**Comment by theyosh** [comment]
Hi,

this is supported using a GPIO Power switch. Or use GPIO Inverse. I am not sure which one will work for you. So, just hook ik up like any other GPIO switch. https://tutorials-raspberrypi.com/raspberry-pi-control-relay-switch-via-gpio/

**Comment by nastea1** [comment]
Thanks!
