### ISSUE TITLE
Sorry next probem

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#37]
![unbenannt](https://user-images.githubusercontent.com/31970192/32147044-cd936bc0-bce0-11e7-8d65-5a25328bb1b2.png)

**Comment by theyosh** [comment]
Ok, this is explained in the release notes. Here are the needed steps:

Login in to your PI and stop the software.
`screen -r` and then press two times Ctrl+C
First update the dependencies:
`cd ~/TerrariumPI`
`sudo ./install.sh`
Now clear the old switch data:
`sqlite3 history.db "drop table switch_data;VACUUM"`
`sudo ./start.sh`

Clear your browser cache to get the latest version.

**Comment by vanessa2013** [comment]
Does your program work with a DS18S20?

**Comment by theyosh** [comment]
Test your DHT22 according to: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-test-a-dht11-dht22-or-am2303-sensor
This is not a problem caused by my software.
