### ISSUE TITLE
Cannot connect since update 3.9.8

### ISSUE THREAD

**Issue by jeff26300** [theyosh/TerrariumPI#370]
Hi theyosh,

I have just updated my TerrariumPi with version 3.9.8, by following your procedure, and I cannot connect to the TerrariumPi webpage anymore. I can still communicate with the raspberry via the terminal and after reboot I get the screen attached with the text "version 3.9.7". I reinstalled a second time and the same screen is shown, with the impossibility to connect to the webpage.
Am I missing something?

![Capture d’écran 2020-04-06 à 21 53 42](https://user-images.githubusercontent.com/57871568/78599463-7642e100-7851-11ea-88dd-b6a2c9c63803.png)

Thanks,

Jeff

**Comment by theyosh** [comment]
Hi @jeff26300 
normally you have to do:
- stop terrariumpi: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-stop-terrariumpi
- do a `git pull`
- rerun the installer: `sudo ./install`
- reboot just to be sure.

If that does not work, try debugging: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi and make a screenshot of what you see.

**Comment by jeff26300** [comment]
Indeed it now works better :)

Thank you again for your great work!!

I can close the issue
