### ISSUE TITLE
password change not being saved across a reboot

### ISSUE THREAD

**Issue by martynwheeler** [theyosh/TerrariumPI#374]
Hi,

When I change the admin password it does not appear to be saved once the system has been rebooted.  I am putting in a new password and the existing password into the two fields.  Where is the hashed password saved in the system?

Thanks

Martyn

**Comment by theyosh** [comment]
ah, that is wrong :P

You need to enter your CURRENT password and a NEW password in the fields. You can only change the existing password when you know it.

Password is stored in PLAIN TEXT in settings.cfg file. So it is not that secure. If you want more security, add a NGINX caching proxy in front.

**Comment by martynwheeler** [comment]
That fixed it.  The input boxes are labelled the wrong way around in the gui! It asks for new password first and then the current password.  I could fix for you if you don't have time?

**Comment by theyosh** [comment]
I do not understand? You think the fields are in an unlogic order? I think it does not matter that much. Nobody remarked it the last 4 years....

**Comment by martynwheeler** [comment]
![image](https://user-images.githubusercontent.com/5069333/80535140-3bd3ec00-8998-11ea-9fe7-6844786f05bd.png)


I think the boxes are wrongly labelled.  I think the first one is the current password and the second is the new password.  When I entered the values like that it all seemed to work.

**Comment by theyosh** [comment]
Nope, fields are correct. Just tested. Closing issue.
