### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by AndrejM73** [theyosh/TerrariumPI#38]
Hi,
i installed TerrariumPi few days ago. Everything worked perfect, but after several restarts i recieved offline status and cant switch to online. Can you help me pls? thank you
![image](https://user-images.githubusercontent.com/28634834/32148298-ff2588d0-bcf4-11e7-8237-d650ea23756f.png)

**Comment by theyosh** [comment]
Ok, this is explained in the release notes. Here are the needed steps:

Login in to your PI and stop the software.
`screen -r` and then press two times Ctrl+C
First update the dependencies:
`cd ~/TerrariumPI`
`sudo ./install.sh`
Now clear the old switch data:
`sqlite3 history.db "drop table switch_data;VACUUM"`
`sudo ./start.sh`

Clear your browser cache to get the latest version.

**Comment by AndrejM73** [comment]
Thank you for hint, but it is still offline. I tried it wit chrome, edge and IE. Any idea whats wrong pls? Here is my log.
[LOG.txt](https://github.com/theyosh/TerrariumPI/files/1428476/LOG.txt)

**Comment by theyosh** [comment]
Could you try: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi

If something is not working, it will be shown there. Also, make sure you have the latest version using `git pull`

The log file is only from the installation. That does not show the problem

**Comment by AndrejM73** [comment]
here is log, but i dont know what can i do with it.

pi@raspberrypi:~/TerrariumPI $ screen -r
    rv = callback(*a, **ka)
  File "/home/pi/TerrariumPI/terrariumWebserver.py", line 40, in webserver_headers
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle_websocket/plugin.py", line 5, in wrapper
    callback(request.environ.get('wsgi.websocket'), *args, **kwargs)
  File "/home/pi/TerrariumPI/terrariumWebserver.py", line 296, in handle_websocket
    terrariumWebserver.app.terrarium.get_environment(socket=True)
  File "/home/pi/TerrariumPI/terrariumEngine.py", line 595, in get_environment
    data = self.environment.get_average()
  File "/home/pi/TerrariumPI/terrariumEnvironment.py", line 374, in get_average
    sensor = self.sensors[sensorid]
KeyError: 'c58072c38341700885f66ce8898498be'

**Comment by theyosh** [comment]
Hmmm, sounds like some issues with the configuration.

Could you rename the file settings.cfg to settings.cfg.temp and restart the software? You will have an empty system again, but that is the only way now to get it running again. If that does work, then edit the old settings.cfg.temp file in such a way that all configs regarding sensors is deleted.

These settings should start with [sensor_ID] and remove all the lines below it till the next [] part.

It should like something:

[sensor_ID]
some
settings
and
more settings

[switch_ID]
new settings etc

**Comment by theyosh** [comment]
Do another `git pull` and restart with original config. It should now work, and give an error message witch sensors is causing the problem

**Comment by theyosh** [comment]
No response, expect to be fixed now

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/32316061-eec6cb4a-bfae-11e7-9e8f-e4df83d7d5e8.png)

Sorry, I have the same problem and all the tips so far have not helped
