### ISSUE TITLE
Install help with DS1820

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#39]
Hi, people can someone help me as I install the DS1820 on the raspberry, my Rasp does not recognize them.

**Comment by theyosh** [comment]
Does this help? https://terrarium.theyosh.nl/static/images/documentation/ds1820-Raspberry-pi.png
Also enable 1-wire on your Pi. This can be done with: `sudo raspi-config` and go to option 5 and there P7 and select yes to enable 1wire. To be sure it is enabled, reboot your pi.

If you have wired your DS1820 correctly, it should work. Use normal pin numbering

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/32293823-a62faaa6-bf44-11e7-8654-6c52d2b61d83.png)


Do you have any idea what could happen again?

**Comment by theyosh** [comment]
run as normal user:
`python terrariumPI.py` in the folder TerrariumPI.

And see what it will say then

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/32299597-7575c668-bf56-11e7-8c99-52ec68563e70.png)

**Comment by theyosh** [comment]
Strange. Looks like you have run it with a different user. But the fix is simple:

run 'sudo chown pi.pi * -R' in the folder TerrariumPI.

Then start it with 'sudo ./start.sh' again

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/32300596-9403a38a-bf5a-11e7-8ee1-a32d04de9f12.png)

Hmm, somehow there is a problem

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/32300633-b8c0211c-bf5a-11e7-8823-104b4be76cbb.png)

**Comment by theyosh** [comment]
You did it wrong! Now you have to create a fully new Raspberry pi image. You have changed the rights on the root partition and not in my software folder.

Sorry, but all these problems are not related to my software. So I will close this issue now, and advise to start completely over again. And you should try to get more understanding of Linux in general and what commands do. I cannot give support on general Linux issues.

**Comment by vanessa2013** [comment]
Ok, thanks anyway
