### ISSUE TITLE
No sound card in settings drop down - unable to modify settings

### ISSUE THREAD

**Issue by se7en9057** [theyosh/TerrariumPI#399]
No sound card shows up in the drop down in settings causing me to not be able to modify settings. 
Fresh install
installed as sudo ./install.sh 3
reboot
cleared browser cache
reboot
added ip to java exceptions in java config
added ip to exceptions in browser
still no settings

**Comment by theyosh** [comment]
Is this on a Pi3 or Pi4? I just saw this also today. I have also issues with mu I2C. And there is a new kernel and some changes in hardware... :(

Also, there are some alsamixer issues... which could be case of this. So I will have to look into this.

**Comment by theyosh** [comment]
It is an issue with my software. So not your browser or java settings....

**Comment by se7en9057** [comment]
brand new Pi 3b+ on fresh install. 
sensors seem to work relays seem to work so far DHT11's just for update off my other issue with the zero. 
thanks for the quick responce. i'll keep tinkering with the GPIO and accessories till i get an update from you.

**Comment by justin1977justin** [comment]
I'm having the same issue. I was getting a 500 error and having i2c issues so I did a clean install and now i can't update settings saved because there is no sound card. At least it's not just me.

**Comment by theyosh** [comment]
Do a `git pull` and restart. It should work again.

**Comment by luke5sky** [comment]
worked for me, thank you!

**Comment by se7en9057** [comment]
awesome. seeing sound cards now!
