### ISSUE TITLE
Cannot add switches

### ISSUE THREAD

**Issue by 50915091Mica** [theyosh/TerrariumPI#40]
Hi, my system collapsed and I decided to reinstall.
So there is a new lite version and fresh install. Through the webinterface I can add sensors, use the system, but the switch doesn´t save. GPIO is ok, just doesnt save..

debug shows error - terrariumswitch - pigpiod process is not running...

could it be the problem?

thanks a lot!

**Comment by theyosh** [comment]
That error message can/should only be shown when you try to add a PWM dimmer switch. Any other switch should not give a problem and that error. So that is strange.

Could you try:  https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi and see what you get on screen?

**Comment by 50915091Mica** [comment]
Well, I managed to solve the not running pigpiod, however the problem lasts.

the debug screen mentions terrariumswitch.py, line 314 valueerror: could not convert string to float:

any sugestions? thank you

**Comment by 50915091Mica** [comment]
![img_20171101_194534](https://user-images.githubusercontent.com/30893672/32291491-7d101702-bf3d-11e7-8800-453dc66e2d0e.jpg)

**Comment by 50915091Mica** [comment]
the full log is above - sorry for the way I post it, at the moment I run on a projector - improvising...


thanks in advance for your help. my iguana is getting cold:-D

**Comment by theyosh** [comment]
Please update with git pull and restart it. Should work again.
