### ISSUE TITLE
Unable to set and save humidity environment

### ISSUE THREAD

**Issue by se7en9057** [theyosh/TerrariumPI#405]
I'm trying to set a sensor driven humidity condition only using the high mark to turn on a switch. i click save and nothing happens. no errors.

**Comment by theyosh** [comment]
Hi,

your right, and that is wrong :D So I updated the code to make sure the settings on the environment part are forced to the correct settings based on the modes. So if you do a `git pull` and clear your browser cache, it should work again.

**Comment by se7en9057** [comment]
your awesome! seems to be working at least on save. waiting for trigger to confirm it does what i'm telling it to actuate.

**Comment by se7en9057** [comment]
:D it did the thing!
