### ISSUE TITLE
Restore Backup Problem

### ISSUE THREAD

**Issue by kaju666** [theyosh/TerrariumPI#407]
Hi

My SD broke.
After install on Buster with python 3 i have problem with restoring settings.cfg
When i copy it to the folder TerrariumPi won't start giving me this error
[settings.txt](https://github.com/theyosh/TerrariumPI/files/4795282/settings.txt)
![2020-06-17_23h55_15](https://user-images.githubusercontent.com/12675680/84954984-b1397e80-b0f6-11ea-89f6-4311b3dd7163.png)

**Comment by theyosh** [comment]
This looks like a missing of corrupt logging.cfg. Or did you made a 'logging.custom.cfg' file? Change that name so it would not be used and try again.

Else, remove the logging.cfg and download the original once more: https://github.com/theyosh/TerrariumPI/raw/master/logging.cfg

**Comment by theyosh** [comment]
Any updates? Found the issue? As I cannot think of something else

**Comment by kaju666** [comment]
Hi

sorry for late reply i didint have logging.custom.cfg. 
logging.cfg was stock.
Finally i made full config from scratch so can't now check what more could be wrong.
