### ISSUE TITLE
Offline part 2

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#41]
![32316061-eec6cb4a-bfae-11e7-9e8f-e4df83d7d5e8](https://user-images.githubusercontent.com/31970192/32329088-3d45edd2-bfdc-11e7-8021-3d73c41c7b39.png)

Sorry, I have the same problem and all the tips so far have not helped. Can you fix this?

**Comment by JoshGr33n** [comment]
I'm having the same issue. I just tried the solution you suggested at [issue#38](https://github.com/theyosh/TerrariumPI/issues/38)

pics:
![pic1](https://user-images.githubusercontent.com/11662027/32348126-1b80ec10-c013-11e7-84c1-f7311ec4f3ec.JPG)
![pic2](https://user-images.githubusercontent.com/11662027/32348127-1b9bd50c-c013-11e7-826f-2fade9e0b48c.JPG)

Thank you

**Comment by vanessa2013** [comment]
and has it helped?

**Comment by theyosh** [comment]
Do a `git pull` and restart. Should be fixed

**Comment by vanessa2013** [comment]
Thx

**Comment by JoshGr33n** [comment]
works great, thanks!
