### ISSUE TITLE
Drop support for yr.no AND Wunderground as weather source.

### ISSUE THREAD

**Issue by theyosh** [theyosh/TerrariumPI#417]
As the Norwegian weather service is changing their API, it is becoming not useful anymore. The API is much more complicated and will not give the information I need for my software.

https://developer.yr.no/doc/guides/getting-started-from-forecast-xml/

They removed the sunrise and sunset values. Which is HUGH important for my software. So that will involve more API calls to different endpoints https://api.met.no/weatherapi/sunrise/2.0/documentation#!/data/get

And you need to fill in lat and long values, which is not user friendly. And for sunrise and sunset values even a timezone is required. So that means a lot of headache with locations and time zones which an API should solve. And not by the developer.

So, after 4 years of using as a very nice and stable weather source I have to say good by to YR.no.

For use with Openweathermap.org you need to register. So create a free account to use either of them as source.
For Openweathermap.org the url would be: `https://api.openweathermap.org/data/2.5/weather?q=[CITY],[COUNTRY_2LETTER]&units=metric&appid=[YOUR_API_KEY]`

UPDATE
It looks also that Wunderground is terminated their API! So, there is now only one weather source available. Use openweatermap!!!

**Comment by theyosh** [comment]
If there is somebody that does know a different source, post it here. As I would not rely on only one service.

I will also try to look into new weather sources

**Comment by cyber-shifter** [comment]
I was looking into this on the OpenWeather Map Site. Digging through their FAQ (I was looking for a list of cities, with corresponding ID's) I found that their URL differed from the one you posted by a bit. They have:

api.openweathermap.org/data/2.5/weather?id=CITY_ID&appid=YOUR_API_KEY

Is this a recent change? I've tried inputting both your URL and mine, and neither seem to work.

**Comment by theyosh** [comment]
No change. But I use the City name option: https://openweathermap.org/current#name

**Comment by cyber-shifter** [comment]
Cool. I think maybe it isn't calling my city by the city name, but by the parish name. I'll take a look again when I get home.

**Comment by cyber-shifter** [comment]
I figured it out, it is indeed calling my city by parish instead of city, but it works so that's all that matters. Thanks!

**Comment by Jakewinkel91** [comment]
I need help with this lol, I had it working last night and then messed up my pi and had to start over, cant for the life of me figure out what i put in that worked!    https://api.openweathermap.org/data/2.5/weather?q=Manaus&APPID=  is what i have now thats not working, it says its not valid!

**Comment by josh5555s** [comment]
> For TP3: `https://api.openweathermap.org/data/2.5/weather?q=[CITY],[COUNTRY_2LETTER]&units=metric&appid=[YOUR_API_KEY]`
> 
> For TP4: `https://api.openweathermap.org/data/2.5/weather?q=[CITY],[COUNTRY_2LETTER]&appid=[YOUR_API_KEY]`

TP4 url works for me, but not if I want to use &units=imperial. Changing the temperature type in the settings menu adds &units=imperial to the url, which results in the "not valid url" error, even though it was working before making the change in settings.
