### ISSUE TITLE
[BUG]: Error aftrer reinstalling

### ISSUE THREAD

**Issue by Kollimat** [theyosh/TerrariumPI#427]
Hello I reinstalled TerrariumPI after my power goes down in middle of update and now i have this error every time.
![TerrariumPI_Error](https://user-images.githubusercontent.com/31453382/87244188-c080c300-c43b-11ea-8e2b-f5d842819e7d.PNG)

**Comment by theyosh** [comment]
My mistake. Do a new `git pull` and it should work again.

But if you did a re-install, I suggest to switch to Python3. Which is more supported and has more sensors. https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-use-python-35

**Comment by Kollimat** [comment]
Perfect, Thank you, all is now function. Is there a way i can support you, like buy you a beer or coffe ?? :)

**Comment by theyosh** [comment]
Yes you can! :P https://github.com/theyosh/TerrariumPI/wiki/Donations

But also, if you did not post pictures at #210 then that is also an option :)

**Comment by theyosh** [comment]
Closing as it is working again...
