### ISSUE TITLE
[BUG]: AM2302 Humidity sensor 'null' / Temperature sensor works fine.  

### ISSUE THREAD

**Issue by danlawless** [theyosh/TerrariumPI#429]
I have just done a clean install of Raspbian (2020-05-27-raspios-buster-full-armhf.img) on a Raspberry Pi 3 Model B Rev 1.2 running TerrariumPI 3.9.8

<img width="644" alt="Screen Shot 2020-07-13 at 10 02 54 AM" src="https://user-images.githubusercontent.com/4893051/87313581-11ea8a00-c4f0-11ea-938f-eb1ef124a6e1.png">

I am having trouble getting a AM2302 sensor to return humidity properly from the dashboard.  I have got the temperature returning properly and see it registering.  

I have tested it in the terminal and it returns the temperature as well as the humidity.  

`root@raspberrypi:/home/pi/TerrariumPI/Adafruit_Python_DHT/examples# python3 AdafruitDHT.py 2302 4`
`Temp=28.2*  Humidity=62.6%`

Attached is a screenshot of the config.  

<img width="1671" alt="Screen Shot 2020-07-13 at 9 58 59 AM" src="https://user-images.githubusercontent.com/4893051/87313170-7d802780-c4ef-11ea-85f2-5d4527c39df1.png">

I am looking or some guidance on how to further test the functionality.  

Am I inputting something incorrectly?  Any advice is appreciated.  Thank you.

**Comment by theyosh** [comment]
Hmm, not sure, but your address values are not correct. You should enter the physical pin number. So it should be a number between 1 and 40.

According to: https://pinout.xyz/ you are using physical pin 7 or BCM pin 4. That pin is reserved for 1-wire (https://pinout.xyz/pinout/1_wire#) . So I suggest to use a different GPIO. I use pin number 16 or 18 (BCM 23 / 24)

Then enter only the physical number of the pin as address

**Comment by theyosh** [comment]
Any updates?

**Comment by theyosh** [comment]
Closing due to no response....
