### ISSUE TITLE
Which humid sensor should I use?

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#43]
theyosh, which sensor do you use to measure the humidity?

**Comment by theyosh** [comment]
I use the following hardware:
On the PI: http://www.sheepwalkelectronics.co.uk/product_info.php?cPath=22&products_id=30 or http://www.sheepwalkelectronics.co.uk/product_info.php?cPath=22&products_id=73

Use for multiple sensors: http://www.sheepwalkelectronics.co.uk/product_info.php?cPath=23&products_id=64

For humidity: http://www.sheepwalkelectronics.co.uk/product_info.php?cPath=23&products_id=55

This is then used through OWFS and not 1-Wire self on the PI. But keep in mind, I cannot give support on how to install the hardware. If you decide to use this kind of hardware, make your self you understand it well. It is also not the cheapest hardware

**Comment by vanessa2013** [comment]
Ok thx for infos. I just want something reliable.

**Comment by vanessa2013** [comment]
You hava a email for Translate update.

**Comment by theyosh** [comment]
Got the translation.
