### ISSUE TITLE
[BUG]: New installation

### ISSUE THREAD

**Issue by tetref** [theyosh/TerrariumPI#430]
I can't install the latest TerrariumPI. I followed the instructions exactly.

I have RaspberryPi 3B, latest Raspbian Buster Lite, Python 3, I also tested an older Stretch.

Only the following is displayed:

 sudo ./start.sh 3
2020-07-14 23:06:57,000 - INFO    - terrariumWrapper     - Starting TerrariumPI server running as user 'pi' at location: http://10.0.0.26:8090 ...

And it doesn't even work as a service:

sudo_ service terriumpi restart
Failed to restart terriumpi.service: Unit terriumpi.service not found.

![2020-07-14](https://user-images.githubusercontent.com/11065044/87477535-8de7ed80-c628-11ea-833b-1829e4608f16.png)

**Comment by theyosh** [comment]
Hi, my mistake. Do a `git pull` and restart. It should work. You still get an error about no 'No GEMBIRD SiS-PM found. Check USB connections, please!' but that is just a message. It should start again.

Sorry

**Comment by tetref** [comment]
Yes, it finally works, one file was changed (terrariumSwitch.py), yesterday it didn't work for git pull yet !!!

thx

**Comment by blatogera** [comment]
> Hi, my mistake. Do a `git pull` and restart. It should work. You still get an error about no 'No GEMBIRD SiS-PM found. Check USB connections, please!' but that is just a message. It should start again.
> 
> Sorry

HI, I have the same error today, 

as well DHT sesors stopped responding which was good befrore the fresh install, 
also some erreor preventing apt-get update and upgrade

![1](https://user-images.githubusercontent.com/67389525/88225337-9c5a8880-cc6a-11ea-9f12-e3751056fd82.JPG)
![2](https://user-images.githubusercontent.com/67389525/88225342-9f557900-cc6a-11ea-97c3-3580a717f22f.JPG)

**Comment by blatogera** [comment]
I may found the issue, however no idea how to solve it, as I just replacem my raspberry Pi 1, to Pi 4 :D 
![image](https://user-images.githubusercontent.com/67389525/88260034-d441ea00-ccc3-11ea-979c-f71035bc9485.png)

**Comment by tetref** [comment]
When I see what the problems are with DHT sensors, I switch to 1-wire and I2C.

**Comment by blatogera** [comment]
> When I see what the problems are with DHT sensors, I switch to 1-wire and I2C.

Can I do that with the same sensor? Do i need any kind of extra hardware? Sorry, I'm new to this...

**Comment by tetref** [comment]
I use a thermometer 18DS20 (1-wire) and I ordered BME280 and HDC1080 (I2C). No extra hw needed. And throw DHTxx in the trash ....

**Comment by blatogera** [comment]
> I use a thermometer 18DS20 (1-wire) and I ordered BME280 and HDC1080 (I2C). No extra hw needed. And throw DHTxx in the trash ....

Not the solution I was expected :D but it may happen if i need to struggle a fewe more days.

**Comment by theyosh** [comment]
Yeah, the owserver has changed there install a bit, and now my changes are not working.... I will write a FAQ for it to fix is.

For your DHT... throw it away :P Look at the closed issues with DHT. They work for a few days and then they start failing.

So now I use a lot of BME280 though I2C. Works nicely. You should be able to have two BME280 on 1 bus. Also some SHT2X SHT3X or HTU21D, si7021 could work with I2C. So you could use different type of hardware for humidity.

**Comment by blatogera** [comment]
Thank you all for your replies! I'll replace the sensors then.
One final question if you dont mind, 

the display is showing the profile picture all the time, the system information and average readings dissapeared and i dont know how to get them back.

I will also have a read about custom display messages, on which file which section I should edit the display information?

thanks a lot again!

**Comment by theyosh** [comment]
Sorry, but the display part is not really well developed or tested... Have you selected the messages you want to display. Per message you can tick where to send the message to. And the newspaper icon is display.

But again, I am currently not able to test if it is still working as should.

Custom display messages is not supported. If you want to do that, I suggest to make your own piece of code that uses my API to get the information, and make your own display setup. Then you have all the freedom you need. That is to hard to make dynamically in a web interface. So much different options and choices.

**Comment by tetref** [comment]
A few more words about DHTxx .. Adafruit has stopped supporting the Adafruit_Python_DHT library and changed it to Adafruit_CircuitPython_DHT. Is it worth changing the code? DHT are terrible sensors, especially DHT22 from China ...

**Comment by theyosh** [comment]
Hi, I am working an a new version, which will have the new DHT library. But I still think DHT should not be used...

**Comment by blatogera** [comment]
Right, changed to BME280P and HTU21D, they both works great, threw the DHT away....
