### ISSUE TITLE
[FEATURE]: MH-Z16 co2 sensor support.

### ISSUE THREAD

**Issue by jawnpeezy** [theyosh/TerrariumPI#436]
Feature/device support request. 

**Describe the solution you'd like**
 Ability for users to be able to easily select sensor on menu, and set parameters for controlling a CO2 tank regulator via use of the MH-Z19 co2 sensors reading, and a 5v /120v relay. This would include settings for CO2 PPM level low trigger and high trigger. Code would also need to use a light dependent resistor, or use the light timer, to sense when lights are on so that, only during "light hours", The CO2 control is active. During nightime hours control would need to be in "off" state.

**Comment by theyosh** [comment]
Hm, this is possible in the environment setup. There you have a CO2 section. Select the CO2 sensor and use mode 'sensor'

Add some power switches controlling the CO2 equipment. Then you select the switches at low alarm when CO2 is to low. And if you have a different device for reducing CO2, you use that in the high alarm section.

Or do I miss something?
