### ISSUE TITLE
[FEATURE]: Enclosure temperature control triggered by CPU temp

### ISSUE THREAD

**Issue by blatogera** [theyosh/TerrariumPI#447]
Hello, 
I have the lower enclosure for electronics, lamps, water tank etc... and looking to set temperature in there.
Things gets heated up in pretty quick if lamps going on, causing the Pi to overheat.
I installed a fan and right now its controlled by the Terrarium top BME280 temp sensor HIGH alarm ( as a temorary solution)

**Describe the solution you'd like**
Would be great to trigger a switch/GPIO with fan controlled by CPU temerature.

**Additional context**
![20200808_122349](https://user-images.githubusercontent.com/67389525/89708193-20a05180-d975-11ea-84d4-b4d121b38295.jpg)

**Comment by bggangel** [comment]
I realize that you are requesting this to be part of the TerrariumPi, but this link describes exactly what you want in a pretty clear way.
[https://howchoo.com/g/ote2mjkzzta/control-raspberry-pi-fan-temperature-python]
Maybe it can help you out in the mean time.

**Comment by blatogera** [comment]
@bggangel Thank you, yes i tried that one first, but after installing and rebooting, the Pi could not boot up. Tried several times, i had to recover from a backup image to have it work again.
Not sure why or how it interfere with terrariumPi, as i have zero programming experience :) - Thats why i opened the request

**Comment by theyosh** [comment]
Hi,

this is possible in multiple ways. I the easiest is to add a new remote temperature sensor. Use as address:

`http://localhost:8090/api/system#temperature`

This will load the CPU temperature from the system status page. As I already measure the CPU temperature. Then you can use this in the heater environment and in the high value part.

Then add a GPIO (inverse) switch for the fan.

If you are already using the heater environment, then I think it is not possible directly.

Then you could also 'abuse' a moisture environment. As the logic is the same.

**Comment by theyosh** [comment]
But maybe using some cooling on the Pi: https://magpi.raspberrypi.org/articles/group-test-best-raspberry-pi-4-thermal-cases-tested-and-ranked

**Comment by blatogera** [comment]
> But maybe using some cooling on the Pi: https://magpi.raspberrypi.org/articles/group-test-best-raspberry-pi-4-thermal-cases-tested-and-ranked

thanks, I'm currently using this passive cooling house, which is working good, but as the air is not circulating in the enclosure it cant discipate,

I'll try the mositure section tu use the cpu as remote sensor, 

![image](https://user-images.githubusercontent.com/67389525/89729969-b6ea7b00-da3a-11ea-8f75-c8aeabc51f71.png)

**Comment by blatogera** [comment]
> http://localhost:8090/api/system#temperature

I can't use the moisute section as I cant select temperature sernsors from the dropdown menu, 
![image](https://user-images.githubusercontent.com/67389525/89730040-7808f500-da3b-11ea-87ec-a94284223f34.png)

![image](https://user-images.githubusercontent.com/67389525/89730053-9111a600-da3b-11ea-9dca-24c94cbd8b85.png)

**Comment by blatogera** [comment]
Never mind, if i set the type to moisture sensor, i can select :) 
Thank you'
works great!

**Comment by theyosh** [comment]
Oh crap, that is true... Only one heater is available. In my new version there will be an option to have multiple heating environments. And then it would be easier to do.

But for now, this is also a solution.

**Comment by theyosh** [comment]
Ok, can we close this issue? This feature will be possible in my new version that is currently being developed....

**Comment by blatogera** [comment]
yes, thank you!
