### ISSUE TITLE
AM2302 question

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#46]
Hi, you have in your interface the selection DHT22 and AM2302, are not they both the same types?

**Comment by theyosh** [comment]
For my software they are the same. The difference is that an AM2302 should already have a resistor so that you can directly connect to a Pi.

In order to make it easy for people I have added both to my interface.

**Comment by vanessa2013** [comment]
Ok, thanks for your info.

**Comment by vanessa2013** [comment]
Can I change the timing of the DHT22 query on your interface?

**Comment by theyosh** [comment]
What do you mean with timing?

**Comment by vanessa2013** [comment]
Thanks but done
