### ISSUE TITLE
webserver closes after 1 hour

### ISSUE THREAD

**Issue by yevgenishohat** [theyosh/TerrariumPI#461]
Hello, I can access the web server but after 1 hour when I refresh the page, I can't access the page what can be the reason for that.

**Comment by theyosh** [comment]
Is there an error in the screen session: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi

**Comment by theyosh** [comment]
Any updates?

**Comment by theyosh** [comment]
Closing due to no updates
