### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by martynwheeler** [theyosh/TerrariumPI#463]
- Python version: [3]
 - Raspberry PI: [3B]

**Describe the bug**
Having just upgraded using git pull and update the motd no longer appears in the console when I log in.  Everything seems to be working okay.

Thanks in advance,

Martyn

**Comment by theyosh** [comment]
Is this still the case? I can take some time (1:30) before the first MOTD is generated.

And there are no errors in the screen session: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi

**Comment by martynwheeler** [comment]
Thanks,

I will check later when I get home (I can't access from work).

**Comment by martynwheeler** [comment]
No, it is still missing.  There are some errors in the screen session, does this help??

</pre>
<h2>Traceback:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 960, in wsgi
    out = self._cast(self._handle(environ))
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 913, in _cast
    out = self.error_handler.get(out.status_code, self.default_error_handler)(out)
  File &quot;/home/pi/TerrariumPI/terrariumWebserver.py&quot;, line 512, in error404
    return template(&#039;404&#039;,**variables)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3630, in template
    return TEMPLATES[tplid].render(kwargs)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3419, in render
    self.execute(stdout, env)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3406, in execute
    eval(self.co, env)
  File &quot;/home/pi/TerrariumPI/views/404.tpl&quot;, line 12, in &lt;module&gt;
    % include(&#039;inc/page_footer.tpl&#039;)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3396, in _include
    return self.cache[_name].execute(env[&#039;_stdout&#039;], env)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3406, in execute
    eval(self.co, env)
  File &quot;/home/pi/TerrariumPI/views/inc/page_footer.tpl&quot;, line 2, in &lt;module&gt;
    document.title = &#039;{{page_title}} | {{title}} ({{version}})&#039;;
NameError: name &#039;version&#039; is not defined

</pre>
<h1>Critical error while processing request: /webcam//a94df035fc91a158c1f9d7a1c769ca66/stream.m3u8</h1><h2>Error:</h2>
<pre>
NameError(&quot;name &#039;version&#039; is not defined&quot;)
</pre>
<h2>Traceback:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 960, in wsgi
    out = self._cast(self._handle(environ))
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 913, in _cast
    out = self.error_handler.get(out.status_code, self.default_error_handler)(out)
  File &quot;/home/pi/TerrariumPI/terrariumWebserver.py&quot;, line 512, in error404
    return template(&#039;404&#039;,**variables)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3630, in template
    return TEMPLATES[tplid].render(kwargs)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3419, in render
    self.execute(stdout, env)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3406, in execute
    eval(self.co, env)
  File &quot;/home/pi/TerrariumPI/views/404.tpl&quot;, line 12, in &lt;module&gt;
    % include(&#039;inc/page_footer.tpl&#039;)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3396, in _include
    return self.cache[_name].execute(env[&#039;_stdout&#039;], env)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3406, in execute
    eval(self.co, env)
  File &quot;/home/pi/TerrariumPI/views/inc/page_footer.tpl&quot;, line 2, in &lt;module&gt;
    document.title = &#039;{{page_title}} | {{title}} ({{version}})&#039;;
NameError: name &#039;version&#039; is not defined

</pre>

**Comment by theyosh** [comment]
This is a strange error. It looks like you settings.cfg file is missing the version setting in the [terrariumpi] section.

Could you post the first 20 lines of settings.cfg? Make sure you do not past passwords

**Comment by martynwheeler** [comment]
Hi, 

Here it is:

[terrariumpi]
host = ::
port = 8090
version = 3.9.8
title = TerrariumPI %(version)s
power_usage = 5
owfs_port = 4304
admin = ***********
password = **************
language = en_US
temperature_indicator = C
distance_indicator = cm
power_price = 0
water_price = 0
soundcard = bcm2835 ALSA
always_authenticate = false
windspeed_indicator = kmh
volume_indicator = L
sensor_gauge_overview = false
hide_environment_on_dashboard = false
graph_smooth_value = 0
external_calendar_url =
graph_show_min_max_gauge = true
horizontal_graph_legend = true
meross_password =
meross_username =

**Comment by theyosh** [comment]
Have you restarted it already? Because I have no clue at the moment....

**Comment by martynwheeler** [comment]
I have restarted it and still the same.  All I did was to follow the instructions on updating the installation.  I also note that the version is not displayed on the webpage?  All the sensors and timers are working though.

![image](https://user-images.githubusercontent.com/5069333/95257259-f4da0480-081b-11eb-87db-38c53d944942.png)

Any suggestions would be welcomed?
Thanks
Martyn

**Comment by theyosh** [comment]
Ok, then for now, edit the settings.cfg and remove the %(version)s part from the title setting and restart... if that does not solve it... then I need a good night sleep to figure this out..

**Comment by martynwheeler** [comment]
Thanks, that has fixed the motd.  Still getting the error in screen -r

you can see the name on the tab is not quite right either?

![image](https://user-images.githubusercontent.com/5069333/95491155-21fbf380-0991-11eb-8286-99977b482d7a.png)


`NameError(&quot;name &#039;version&#039; is not defined&quot;)
</pre>
<h2>Traceback:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 960, in wsgi
    out = self._cast(self._handle(environ))
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 913, in _cast
    out = self.error_handler.get(out.status_code, self.default_error_handler)(out)
  File &quot;/home/pi/TerrariumPI/terrariumWebserver.py&quot;, line 512, in error404
    return template(&#039;404&#039;,**variables)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3630, in template
    return TEMPLATES[tplid].render(kwargs)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3419, in render
    self.execute(stdout, env)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3406, in execute
    eval(self.co, env)
  File &quot;/home/pi/TerrariumPI/views/404.tpl&quot;, line 12, in &lt;module&gt;
    % include(&#039;inc/page_footer.tpl&#039;)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3396, in _include
    return self.cache[_name].execute(env[&#039;_stdout&#039;], env)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3406, in execute
    eval(self.co, env)
  File &quot;/home/pi/TerrariumPI/views/inc/page_footer.tpl&quot;, line 2, in &lt;module&gt;
    document.title = &#039;{{page_title}} | {{title}} ({{version}})&#039;;
NameError: name &#039;version&#039; is not defined

</pre>
<h1>Critical error while processing request: /webcam//a94df035fc91a158c1f9d7a1c769ca66/stream.m3u8</h1><h2>Error:</h2>
<pre>
NameError(&quot;name &#039;version&#039; is not defined&quot;)
</pre>
<h2>Traceback:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 960, in wsgi
    out = self._cast(self._handle(environ))
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 913, in _cast
    out = self.error_handler.get(out.status_code, self.default_error_handler)(out)
  File &quot;/home/pi/TerrariumPI/terrariumWebserver.py&quot;, line 512, in error404
    return template(&#039;404&#039;,**variables)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3630, in template
    return TEMPLATES[tplid].render(kwargs)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3419, in render
    self.execute(stdout, env)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3406, in execute
    eval(self.co, env)
  File &quot;/home/pi/TerrariumPI/views/404.tpl&quot;, line 12, in &lt;module&gt;
    % include(&#039;inc/page_footer.tpl&#039;)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3396, in _include
    return self.cache[_name].execute(env[&#039;_stdout&#039;], env)
  File &quot;/usr/local/lib/python3.7/dist-packages/bottle.py&quot;, line 3406, in execute
    eval(self.co, env)
  File &quot;/home/pi/TerrariumPI/views/inc/page_footer.tpl&quot;, line 2, in &lt;module&gt;
    document.title = &#039;{{page_title}} | {{title}} ({{version}})&#039;;
NameError: name &#039;version&#039; is not defined

</pre>
`

**Comment by martynwheeler** [comment]
Do you think that it would be worth running the update again?  I'd rather not reinstall as I have everything set up.  However, if there is a way to reinstall and keep all my configuration that would be okay.

Thanks

**Comment by theyosh** [comment]
Hmm, you could always do a `git pull` and rerun the installer. In case of a reinstall: https://github.com/theyosh/TerrariumPI/wiki/FAQ#which-files-to-backup

**Comment by martynwheeler** [comment]
I will give it a try

**Comment by martynwheeler** [comment]
Hmm, an update has not solved it.  Okay, so if I want to reinstall, I save the files you pointed to and remover the Terrariumpi directory and then reinstall by following the installation procedure?  Just want to clarify before I start.

Thanks again for your help

**Comment by theyosh** [comment]
Do not remove, but just rename the older directory ;) Makes it easier to copy the files over

**Comment by martynwheeler** [comment]
I don't know if this is related in any way but I am also seeing this error:

● owserver.service - Backend server for 1-wire control
   Loaded: loaded (/lib/systemd/system/owserver.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-10-09 19:33:10 BST; 45s ago
     Docs: man:owserver(1)
  Process: 481 ExecStart=/usr/bin/owserver -c /etc/owfs.conf (code=exited, status=1/FAILURE)
 Main PID: 481 (code=exited, status=1/FAILURE)

Oct 09 19:33:10 terrariumpi systemd[1]: owserver.service: Service RestartSec=100ms expired, scheduling restart.
Oct 09 19:33:10 terrariumpi systemd[1]: owserver.service: Scheduled restart job, restart counter is at 5.
Oct 09 19:33:10 terrariumpi systemd[1]: Stopped Backend server for 1-wire control.
Oct 09 19:33:10 terrariumpi systemd[1]: owserver.service: Start request repeated too quickly.
Oct 09 19:33:10 terrariumpi systemd[1]: owserver.service: Failed with result 'exit-code'.
Oct 09 19:33:10 terrariumpi systemd[1]: Failed to start Backend server for 1-wire control.

**Comment by theyosh** [comment]
No this is not related. But this can be solved by editing:

edit `/etc/owfs.conf` and enable the line `server: FAKE = DS2405` around line 16. My installed does remove this, but apparently this does not work with the newer versions.

**Comment by martynwheeler** [comment]
Mine says,
#server: FAKE = DS18S20,DS2405
Should I remove the DS18S20 as I am using two DS18S20 sensors in my setup

**Comment by theyosh** [comment]
No, as this is a fake sensor, it will just generate random values. Only the DS2405 is needed. This will make OWFS work again, and fix the systemd status issue. So remove DS18S20 and remove the '#' in front of the line.

Then test it with service owfs restart and that should then work

**Comment by martynwheeler** [comment]
Okay, I have done a new installation and I seem to have got rid of the error.  Thank you for all of your help!

**Comment by theyosh** [comment]
Nice and enjoy the new version!

**Comment by theyosh** [comment]
He, I found the bug. It has to do when you zoom in with the webcam or loading the favicon.ico file. That give a 404 error, which was missing the version number. So it should now be fixed for ever!

**Comment by martynwheeler** [comment]
Thanks
