### ISSUE TITLE
[FEATURE]: Deactivate color conversion for webcam image

### ISSUE THREAD

**Issue by npinter** [theyosh/TerrariumPI#467]
I'm using Pi Camera IR-Cut (Sensor OV5647), connected via the RPiCam port. 
![image](https://user-images.githubusercontent.com/34959927/95835404-77902180-0d3e-11eb-9344-2cc2c00aa485.png)

Location is `/dev/video0`. I had some strange color conversion issues (color inversion, pinkish colors..) until I removed the color conversion part from the code (https://github.com/npinter/TerrariumPI/commit/962d2c99024799225b45d9aff84ebf5b1f03679c).

Feature: Adding a dropdown to webcam settings with the choice of activate/deactivate color conversion.

**Comment by theyosh** [comment]
Hmm, I am also using such a camera. For me, the color is fixed by using the 'grey world' option in the webcam settings. This will produce nice pictures. Have you tried that?

Because I am not sure what the impact will be for other Pi camera's.

**Comment by npinter** [comment]
"greywold" in white balance? This does not fix the issue in my case:

![image](https://user-images.githubusercontent.com/34959927/95910180-f23d5900-0d9f-11eb-832d-85ea15aedb12.png)

Removing the color conversion part of the code:

![image](https://user-images.githubusercontent.com/34959927/95910438-5cee9480-0da0-11eb-988f-4cd010800034.png)

**Comment by theyosh** [comment]
Ok, then you are not using the camera as an RPI cam? Because the color change only happens on a USB camera. Not a RPI camera.

So what is the address you enter for your camera?

**Comment by npinter** [comment]
I tried that before, but the camera will not be recognized anymore:

![image](https://user-images.githubusercontent.com/34959927/95967721-db811b80-0e0c-11eb-9e71-aa6c2548c41a.png)

It only works with `/dev/video0`.

**Comment by npinter** [comment]
*facepalm*.. entered the `rpicam` and did the restart as you suggested:

![image](https://user-images.githubusercontent.com/34959927/96100057-3893d480-0ed4-11eb-8c6c-35fa54b41699.png)

I guess this can be closed now. Thanks for all the effort you've put into TerrariumPi, it's really nice :)
