### ISSUE TITLE
[FEATURE]: TDS sensor graph

### ISSUE THREAD

**Issue by se7en9057** [theyosh/TerrariumPI#474]
**Is your feature request related to a problem? Please describe.**
a way to use a TDS sensor to measure total dissolved solids inside TPi

**Describe the solution you'd like**
Sensor compatibility

**Additional context**
TDS is important for certain types of plants such as orchids and carnivorous plants. TDS must remain low. adding it to the sensor dashboard with thresholds would allow for more granular automation or at least monitoring.

**Comment by theyosh** [comment]
Hmm, this is an analog sensor, and therefore not directly supported on the Pi directly.

So either use https://github.com/theyosh/TerrariumPI/wiki/Hardware#analog-sensors 

Or make your own Arduino that does the measurements and has a webserver so you could add this sensor through a 'remote sensor'
