### ISSUE TITLE
TerrariumPI not starting after update

### ISSUE THREAD

**Issue by darrynl** [theyosh/TerrariumPI#475]
Hi All,

After doing an update to TerrariumPI, it no longer starts.
I tried doing an update on my running V3.9.8 installation just to make sure that I had the latest and greatest, but it looks like I broke something ...

What I did:

Logged into Raspberry Pi as user pi
cd TerrariumPI
git pull
sudo ./install.sh 3
When the installer as done I chose to reboot.
When the Pi came up, the web interface was not reachable and the system is not listening on port 8090.

Trying to start TerrariumPI manually:
![image](https://user-images.githubusercontent.com/19905416/97812975-c66e0e80-1c8d-11eb-8d32-cffa3343617b.png)

**Comment by theyosh** [comment]
Hmm, somehow you luma.oled package is outdated... try:

`sudo pip3 install -U luma.oled`

Or, rerun the installer. Maybe some packages did not install correctly...

**Comment by darrynl** [comment]
Thank you.

![image](https://user-images.githubusercontent.com/19905416/97815177-02f13880-1c95-11eb-94bd-41f34757b99f.png)

I already tried re-installing and got the same result. :-)

**Comment by theyosh** [comment]
And it is running again?

**Comment by darrynl** [comment]
No,  it is still not running.

**Comment by theyosh** [comment]
But with the same error still? Because when I open the file: /usr/local/lib/python3.7/dist-packages/luma/core/bitmap_font.py there is no reference to import UnidentifiedImageError. 

```
# -*- coding: utf-8 -*-
# Copyright (c) 2020 Richard Hull and contributors
# See LICENSE.rst for details.

from pathlib import Path
from math import ceil
from copy import deepcopy
from PIL import Image, ImageFont
import cbor2
from luma.core.util import from_16_to_8, from_8_to_16
```

And I see that I have a higher luma.core version. So could it be that running `sudo pip3 install -U luma.core` will save this? Then it looks like a dependency issue with the luma modules...

**Comment by darrynl** [comment]
I ran a sudo pip3 install -U luma.core this morning and now it seems to be working.

Thank you for your help.
