### ISSUE TITLE
Need advice for temperature setting.

### ISSUE THREAD

**Issue by nukenook** [theyosh/TerrariumPI#477]
Hi,

I use DS1820 to monitor temp. and control relay board for ceramic heater. But I really confuse about the setting.

 - My day time temp. is about 30 and I want to control night temp. to 25. How can I config the sensor and environment setting?

I try to set it as

      - sensor 
                 Alarm min=25 , max=30  / Limit min=0 , max=50 / Max diff=1
      - Temperature 
                 mode=sensor / Day/night difference= -5 
      - Low alarm
                 Power on=0 / Settle timeout=120 

Is it correct?

Thank You

**Comment by theyosh** [comment]
Hi,

hmm, you are close, but you should not have a Temperature difference in the environment page. As your lower limit is already 25. So with the difference of -5, it will be 20 as low limit (before the heater turns on). You should also see the alarm lines on the graph of the sensor. It should show 20 degrees as low limit during the night with the current settings.

But, what have you select for light source and light state.

I have the current setup. And I think you want the same (ignore the day/night difference)
![image](https://user-images.githubusercontent.com/8080177/99365499-abb7ae80-28b7-11eb-8d57-6f7d8a83733f.png)


Also, make sure you have the latest version. There was a logic error in the environment controlling.

**Comment by nukenook** [comment]
Thanks for reply. So, if I change the setting to

  - sensor 
             Alarm min=25 , max=30  / Limit min=0 , max=50 / Max diff=1
  - Temperature 
             mode=sensor / **Day/night difference= 0** / **Day/night source=lights**
  - Low alarm
             Power on=0 / Settle timeout=120 / **light state=off**

Does it means that in night time (light off} if the temp. drop lower than 25 the heater will start and off after raise to 25? or off at 30?

**Comment by theyosh** [comment]
The heater should kick in when it gets colder then 25 and stops when it hits 30 degrees. You should get a temperature graph that looks like:
![image](https://user-images.githubusercontent.com/8080177/99505209-d1f55100-2980-11eb-9980-9c0a6a1ad583.png)

**Comment by nukenook** [comment]
OK. I got it. Thank you ^^
