### ISSUE TITLE
Telegram, Temperate, Password Setting need help !

### ISSUE THREAD

**Issue by captianboat** [theyosh/TerrariumPI#480]
Hi, i'm live in warm temperate zone saw in the screenshot Help menu have Cooling and Spray but can't find in the Environment

i need Set up turn on Cooling Fan

if Temperature >26 
turn off <24 

i try to set Temperature Settings

High alarm = turn power switch on
but i don't need the switch run by Duration in seconds :( 
how to setting this rule ?

Thank you :)

**Comment by captianboat** [comment]
May i set up base on Temperature Settings https://github.com/theyosh/TerrariumPI/issues/153#issuecomment-393231536
Turn on Fan for 4 minutes, and see after 2 Seconds  if the alarm is still there. loop Turn on Fan again. 

![image](https://user-images.githubusercontent.com/74257775/99352063-88e7c300-28d4-11eb-8a54-88ec76006965.png)

and Spray can i setup like this pic Turn on by timer 1 time at 08:00 AM run 10 Seconds ? (it's work with Seconds?) 

this setup https://github.com/theyosh/TerrariumPI/issues/391#issuecomment-628081043 i will use for Fog maker 👍 


![image](https://user-images.githubusercontent.com/74257775/99353952-1e388680-28d8-11eb-8e97-63b586cc9ce0.png)

Thank you :)

**Comment by captianboat** [comment]
I just setting Telegram Notifications 
in Chat bot command /start
receiver message : Sorry, you are not a valid user for this TerrariumPI
but my Telegram username is correct maybe it's Bug ? 

![image](https://user-images.githubusercontent.com/74257775/99509480-63cc8080-29b8-11eb-863f-68f1070f27b4.png)

with Admin name, i change log in name but can't change password the systems show setting SAVE 
when log it still old password with new username how can i fix that ?_?

Thank you

**Comment by theyosh** [comment]
Hi, sorry for the late reply.

But please one issue at a time. For your temperature settings, the screenshot looks ok. But it has now that the door needs to be open to turn the fan on. That is not handy I guess.

Basically, you need to setup the Temperature environment. And in your case only the high alarm. (You want cooling). So setup the senor(s) in such a way, that they give the wanted min and max values.

Then the amount of power on field, is in seconds. And will tell to run for that amount of seconds. Leave it zero to keep it running until it is to cool.
The settle timeout is also in seconds. That it the time the new temperature can settle before a new action is taken on this alarm. If you have a power on value, then the switch will toggle on for that amount of time, and then wait for the settle time. If it is then still to hot, it will turn on the fan again.

That should fix you cooling setup

**Comment by theyosh** [comment]
Did the above explanation help?

**Comment by theyosh** [comment]
Any updates?

**Comment by captianboat** [comment]
Sorry, i just saw comment. I'll run system test maybe tomorrow my tank just finish i will update yo soon as possible

**Comment by captianboat** [comment]
Hi, i start the systems today cooling systems work like a charm.
Thank you so much i will try Telegram bot with Version 3.9.9 agian 👍
