### ISSUE TITLE
[FEATURE]: VEML6070 support

### ISSUE THREAD

**Issue by danimalia2017** [theyosh/TerrariumPI#484]
I can't source the VEML6075, but can get the VEML6070. Is there support for this sensor? I can't find any documentation or issues on it here. 

Thanks
Dan

**Comment by theyosh** [comment]
I have no clue. As I buy hardware on somekind of board, I can just hook it to the GPIO. And then I would just use it as a VEML6075 but then only for UVA. There is no UVB and therefore also no UVI.

Else I would not know. Then we need to find some python code that is able to readout the sensor.

**Comment by danimalia2017** [comment]
thanks for the response. I managed to find a VEML6075 on amazon, so it's all good. can close this now :)
