### ISSUE TITLE
PH connect 

### ISSUE THREAD

**Issue by yevgenishohat** [theyosh/TerrariumPI#489]
Hello, I have 2 type of Ph sensors ph-4502c and ph sen0161, I tried to connect both but It didnt worked, how I make the connection.

**Comment by theyosh** [comment]
Hi, the PH-sens0161 can be added. That is supported trough https://github.com/theyosh/TerrariumPI/wiki/Hardware#analog-sensors

But that means, you have to add an extra analog shield to the Pi. The other sensor is not supported.

**Comment by theyosh** [comment]
Any updates?

**Comment by theyosh** [comment]
Any updates?

**Comment by theyosh** [comment]
Closing due to no response
