### ISSUE TITLE
[WIKI/README] Wiring scheme combination of BME280 and DS18B20

### ISSUE THREAD

**Issue by TheCrafft** [theyosh/TerrariumPI#492]
Hello!

It might be useful to add a wiring scheme to either the wiki or the readme. The combination of a BME280 and a DS18B20 will probably become the most common, so here is my scheme.

```
RPi   [VCC 3V3 Pin 17] --------------------------- [VIN]  BME280
RPi   [GPIO.2 Pin 3] ----------------------------- [SDA]  BME280
RPi   [GPIO.3 Pin 5] ----------------------------- [SCL]  BME280
RPi   [GND - Pin 14] ----------------------------- [GND]  BME280
```

```
RPi   [VCC 3V3 Pin 1] -----------------------------  [VCC]    DS18B20
                                               |
                                               \
                                               /   R1 = 4k7
                                               \
                                               |
RPi  [GPIO.4 - Pin 7] ----------------------------- [DATA]   DS18B20


RPi     [GND - Pin 9] ----------------------------- [GND]    DS18B20
```

https://pinout.xyz/#

**Comment by theyosh** [comment]
Hmm, I think this something you can find with DuckDuckGo (Or Google).  Also, my BME280 is on I2C bus 4, and that are different numbers :P

And writing documentation is always an issue ;)

So, I can't do much with this.. And, if we need to make schemes, use Fritzing to draw them. https://fritzing.org/
