### ISSUE TITLE
Cant add sensors on the sensors page 

### ISSUE THREAD

**Issue by pewi81** [theyosh/TerrariumPI#5]
I don't get the option to add sensors on the sensors page, all I can see is the Help-information and the "Submit" button.

**Comment by theyosh** [comment]
Clear browser cache? After pulling the latest version from github you need to restart the software to load the new templates.
There should be a blue add (+) button the right side of the page next to the title

**Comment by pewi81** [comment]
Clearing the cache fixed the problem, thanks!
