### ISSUE TITLE
Having Trouble Setting up Temperature and Humidity in Environment page

### ISSUE THREAD

**Issue by Zlo98** [theyosh/TerrariumPI#506]
I am currently trying to regulate my temperature based on a sensor and humidity with a sprayer based on a timer. I have attached screenshots of how I have it setup if anyone notices what I have wrong. I cant get the temperature dashboard readings to show anything other than zeros.
![terrariu pi dashboard](https://user-images.githubusercontent.com/67603213/103819949-6acb5300-5039-11eb-89fb-5c52ddbd0eca.PNG)
![terrarium pi temp low](https://user-images.githubusercontent.com/67603213/103819960-6dc64380-5039-11eb-9d3b-1d04da2a6fb5.PNG)
![terrarium pi temp high](https://user-images.githubusercontent.com/67603213/103819962-6ef77080-5039-11eb-8176-1368025c41a6.PNG)
![terrarium pi himudity](https://user-images.githubusercontent.com/67603213/103819972-7159ca80-5039-11eb-866c-3ee6e6f8efe4.PNG)

**Comment by Zlo98** [comment]
I am a dummy and hadn't had the Lights setup

**Comment by theyosh** [comment]
Do not use the same power switch for both low and high alarm.

Your heater should only kick in when low alarm is triggered. For high temp alarm you could use fans or something to cool it down.
Now it will work both day and night. Is that what you want?
