### ISSUE TITLE
Updating notification settings failes

### ISSUE THREAD

**Issue by kahuwi14** [theyosh/TerrariumPI#518]
Dear yosh,

I hope, you're doing great!
Yesterday, I reinstalled my Pi3b, because the update process to 3.9.9.
That wasn't a big deal, because it forced me to do what I wanted to do for a long time. ;)

Now, everything is fresh and up-to-date, without errors and strange behaviour, except the issue, that I can't make any setting for the notification!

Without a notifications.cfg, I'm able to fill the form with all needed information, but after saving, all values in the messages-section "jump" one box to the left. That happens after every saving. It doesn't make any difference, if I change a value in this section, or not.

![nachAenderung](https://user-images.githubusercontent.com/36901881/107116717-82366f80-6875-11eb-880e-9ea48403007e.png)

I tested this Issue of course in the incognito-mode as well.

It wouldn't be a problem, if I would be able to activate push-notifications over the config-file, but that's not working.. :-/

cya
Karsten

**Comment by theyosh** [comment]
Sorry for the late reply. I have no clue. I have to look into this. I think I get the issue here. But I need to do some testing. I will get back on it

**Comment by theyosh** [comment]
Found it. Do a `git pull` and restart. It should be fixed.

**Comment by kahuwi14** [comment]
Great, it works!
Thanks a lot!
