### ISSUE TITLE
[FEATURE]: NeoPixel Support

### ISSUE THREAD

**Issue by Blacky2812** [theyosh/TerrariumPI#525]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by theyosh** [comment]
Sorry, but I do not see how to support a NeoPixel, as I will not make a color system to control colors.

**Comment by Blacky2812** [comment]
Okay, how i can access top external Scripts? so i can write my own Python top Control ws2812b

**Comment by theyosh** [comment]
An example can be found here: https://github.com/theyosh/TerrariumPI/blob/master/contrib/external_switch.py

**Comment by theyosh** [comment]
Hi, is the example script enough for you to get started?

**Comment by Blacky2812** [comment]
Yep, i got it running.
