### ISSUE TITLE
[Question] Problems to setup a Time(Tp-link kasa plug HS100)

### ISSUE THREAD

**Issue by 17Trust09** [theyosh/TerrariumPI#526]
Hey there :) 
not sure if thats the right way to ask for help.

im trying to setup a timer (power plug) but its totally freaking out at the moment (going  on/off again).
any idea why?  my intent is to have it 12h off and 12h on....

![Licht2](https://user-images.githubusercontent.com/43847077/110945517-10eb5000-833e-11eb-83d8-fd7f20d9539d.png)
![Licht1](https://user-images.githubusercontent.com/43847077/110945521-1183e680-833e-11eb-9f05-6705befa8276.png)
![Schalter](https://user-images.githubusercontent.com/43847077/110945523-1183e680-833e-11eb-8f33-870f33d0d8a9.png)

**Comment by theyosh** [comment]
Only fill in the Tag/Nacht part when it needs to be on. I guess that for you it is the easiest to clear the Nacht (night) part. That should fix it.

**Comment by theyosh** [comment]
Any updates? Did the change work?

**Comment by 17Trust09** [comment]
well I totally forgot to answer  :) 
it's working fine now! I did the timer setup over the timer setup in the Switch tab :) 


love the app so far! next thing that I will try is to setup a temp and humidity sensor.

**Comment by theyosh** [comment]
Nice, then I close this issue now. Have fun! And do not forget #210
