### ISSUE TITLE
Using the same switch for low and high alarm

### ISSUE THREAD

**Issue by fabi2803** [theyosh/TerrariumPI#527]
Hello,
first of all, thanks for working on this great project, I love it and I'm going to use it for my mushroom grow room. I'll send you pictures in a few weeks when I put them in the tent.

Now to my little problem:
I'm using a ultrasonic humidifier with a fan to control the humidity, both with their own switches.
With low alarm both should power up, with high alarm I want just the fan to blow.
<img width="1162" alt="Bildschirmfoto 2021-03-12 um 17 15 20" src="https://user-images.githubusercontent.com/28477592/110968384-bced6500-8357-11eb-8a03-aa9544f4118e.png">

<img width="1162" alt="Bildschirmfoto 2021-03-12 um 17 15 40" src="https://user-images.githubusercontent.com/28477592/110968390-bf4fbf00-8357-11eb-94c9-9c46c130b766.png">

At first I didn't have a high alarm and it worked fine as you see at the middle of the graph.
As I added the Fan at the high alarm, it turned on and off all the time when humidity was to low.

<img width="1423" alt="Bildschirmfoto 2021-03-12 um 17 16 23" src="https://user-images.githubusercontent.com/28477592/110968391-bfe85580-8357-11eb-8214-751091fdc70e.png">

I could minimize the problem with a settle timeout at the high alarm setting but I don't think that's a solution.
I don't know how much sense my high alarm strategy makes but maybe there is a scenario where a switch is used at high and low alarm. 

Best regards

**Comment by theyosh** [comment]
Hi,
at the moment it is not possible to use a relay twice. So if a relay is selected in the low part, you cannot use it in the high part. That will not work.

In my new version it will work. So for now, you could add a second fan and use that for the high alarm settings.

**Comment by fabi2803** [comment]
Do you want to reveal when the new version might go online?

**Comment by theyosh** [comment]
The new version will be online (I hope) this month. But it is a major rewrite, so I call it beta. And it can have (new) bugs.

**Comment by fabi2803** [comment]
Nice!
I am looking forward testing it.
