### ISSUE TITLE
[BUG]: Can't update login credentials using RaspberryPi Zero. (No sound card selected) 

### ISSUE THREAD

**Issue by Sagi313** [theyosh/TerrariumPI#531]
Using Python3, and Raspberry Pi Zero W+ ( I know it's not supported, But it works!)

When i go into the setting menu, and want to change the default credentials from "admin/password", I get requested to select a sound card to continue. The problem is I don't have any sound card.

![image](https://user-images.githubusercontent.com/23437763/112349598-89a0c380-8cd1-11eb-8e56-47b6e009a1aa.png)

**Comment by theyosh** [comment]
If you do a git pull, you should be able to select 'None' for soundcard. Make sure your browser cache is cleared.

**Comment by Sagi313** [comment]
Thank you!
by the way- I really enjoy TerrariumPi

**Comment by theyosh** [comment]
Nice! Did you post some pictures at #210 ?

**Comment by Sagi313** [comment]
Not yet.
Going to post some as soon as i'll finish my makeover!
