### ISSUE TITLE
translation issues

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#55]
Unfortunately, I am unable to translate everything.
![unbenannt](https://user-images.githubusercontent.com/31970192/33225395-eae4afcc-d176-11e7-9b8d-a6161f12bf13.png)

**Comment by theyosh** [comment]
I have added German translation for the audio file listing.

But, I have also introduced 5 new sentences. The are in the dropzone part. If you could translate those as well, that would be very nice

**Comment by vanessa2013** [comment]
Hi, ok here are the files, but everything is still not translated ...


[Translate.zip](https://github.com/theyosh/TerrariumPI/files/1503394/Translate.zip)

**Comment by theyosh** [comment]
What part is now still not translated? I do know that not all parts of the weather page is translated. But that is impossible due to external terminology. So I cannot translate that.

**Comment by vanessa2013** [comment]
The picture I sent you yesterday ...


![grafik](https://user-images.githubusercontent.com/31970192/33235804-595583bc-d241-11e7-9bfa-c1580718badd.png)

**Comment by theyosh** [comment]
After latest pull, clear browser cache. This translation is done client site in the browser

**Comment by vanessa2013** [comment]
Nop sorry, 

![grafik](https://user-images.githubusercontent.com/31970192/33235838-2c6913fe-d242-11e7-8009-8e9a15d3908c.png)

**Comment by theyosh** [comment]
Hmm, turns out that the German translation is not valid JSON:

https://cdn.datatables.net/plug-ins/1.10.16/i18n/German.json

So this is also a problem I cannot fix. It is a bug in an external plugin. https://datatables.net/

**Comment by vanessa2013** [comment]
Ok you can not do anything, then this topic is done :-)
