### ISSUE TITLE
Virtualbox virtualbox raspberry pi installation

### ISSUE THREAD

**Issue by LuisMoraes132** [theyosh/TerrariumPI#557]
Hey how is everything.  I would like to know if this system works in VirtualBox, simulating a breath for me, I did the installation correctly, but it's not opening the external IP through VirtualBox, can you tell me or if there is a video teaching how to install.

**Comment by LuisMoraes132** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/40615408/122960250-9dec6f00-d359-11eb-8ceb-a2a88344cd0a.png)

**Comment by LuisMoraes132** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/40615408/122960298-a9d83100-d359-11eb-98f7-fc82b6fe2dd7.png)

**Comment by theyosh** [comment]
Hi,

sorry to say, but VirtualBox is not supported. Therefore I cannot support this. You are on you own with this.

you can try to stat manully to see what is happening:

`cd /home/pi/TerrariumPI`
`python3 terrariumPI.py`

And see what happens... But I am afraid that this is where the support stops...

**Comment by theyosh** [comment]
Closing as this is not supported.
