### ISSUE TITLE
[BUG]: V4 JS Gauge issue "Uncaught TypeError: e.toFixed is not a function"

### ISSUE THREAD

**Issue by chrRtg** [theyosh/TerrariumPI#563]
**More info**
After logging out on the next reload a JS error shows up. On the dashboard at least one gauge is not shown. If I switch to any sensor the gauge is in a disabled or not initalized state and the line chart shows loading spinner. 
To resolve this situation a new login is sufficient.

To illustrate the problem I had attached three screenshots.

@theyosh if you have something I should try to locate the problem please send me a message, happy to support such great product.

**Setup:**
 - TerrariumPI version: 4.x.y.z
 - Python version:3
 - Raspberry PI: 3B

**Screenshots**
The problem in debug console
![grafik](https://user-images.githubusercontent.com/16746944/125131713-7b9d7400-e103-11eb-894e-f2f0a0533420.png)

The missing Gauge
![grafik](https://user-images.githubusercontent.com/16746944/125131806-9c65c980-e103-11eb-8386-4a34ba7fd289.png)

A typical Sensor View
![grafik](https://user-images.githubusercontent.com/16746944/125131876-c6b78700-e103-11eb-8cac-e5e4123835d8.png)

**Comment by theyosh** [comment]
Hi,

I see this sometimes, and a reload fixes it. So for now it is a low priority issue.

**Comment by theyosh** [comment]
Hmm, I think I found this  by accident. Could it be that you had also the option to show the min and max values set to on in the settings page? If so, then this should be fixed now.

Do a `git pull` and refresh your internet browser.

**Comment by chrRtg** [comment]
Sorry for the late reply @theyosh, had to build the terrarium first.

With the newest V4 the problem is no longer appearing. I'll close the tickets while I consider the issue solved.

Thanks mate!
