### ISSUE TITLE
[BUG]: Incorrect Average Temperature

### ISSUE THREAD

**Issue by PhoenixNP** [theyosh/TerrariumPI#572]
**Setup:**
 - Software Version 4
 - Raspberry PI: 3B

**Describe the bug**
The average temperature calculated is "incorrect".
While testing the setup and excluding one of the sensors from the average, it still get's used for the caculation.

**To Reproduce / Installation steps**
![image](https://user-images.githubusercontent.com/67959379/127327471-5320262f-3211-458a-ad37-44e8dc472978.png)

**Expected behavior**
The sensor that has the "Exclude Average" set to be excluded from calculations

**Comment by theyosh** [comment]
Strange, I really thought this has worked.

But it is fixed now. Do a `git pull` and restart TerrariumPI. That should fix this.

**Comment by PhoenixNP** [comment]
The average is working now, but the "All Sensors" page doesn't show the temperatures anymore.

**Comment by theyosh** [comment]
> The average is working now, but the "All Sensors" page doesn't show the temperatures anymore.

It is unclear what you mean with "doesn't show the temperatures anymore"

**Comment by PhoenixNP** [comment]
It works right now =)
Apparently it was a matter of waiting for the sensors to update a few times =)
