### ISSUE TITLE
How cool terrarium with high temperature

### ISSUE THREAD

**Issue by vikrilow** [theyosh/TerrariumPI#586]
Hello again

Anyone can tell me how down temperature when it up a lot?
My problem is that I've a HID lamp (this lamp give UVB and hot) so I can't stop this lamp.

I've installed fans but this isn't enough to down temperature correctly.

Thanks in advanced

**Comment by theyosh** [comment]
Hmm, some suggestions. Not sure if they help

- Lower wattage HID lamp? Lower watt, is lower temp
- Depending on your enclosure, have a the top open with a metal mash. So the hot air can move up
- Adding a mister system like https://www.amazon.com/Coospider-Terrariums-Humidifier-Paludarium-Amphibians/dp/B07VVNP7F3/ref=sr_1_6?dchild=1&keywords=reptile+automatic+mister&qid=1629113249&sr=8-6 . The wet air can cool down a bit. Will raise humidity levels


This is what I can come up with. But I think that the easiest is to go with a lower WATT HID lamp.

**Comment by vikrilow** [comment]
Hi
Thanks for your reply

Actually I've a humidifier. And 5 fans.
I can't up hid lamp because my enclosure is closed.
My hid lamp is only 35w, I think there isn't smaller that I have

For that, I've decided change hid lamp for I Arcadia lamp. I think there better option for me.

Tanks  for your comments!!

**Comment by theyosh** [comment]
Hi, 35W is the lowest value. I have those also. But for me, the environment is big enough.

**Comment by theyosh** [comment]
Found a solution? I would like to close this issue, as I cannot do much about this. You could also start a discussion about this. Maybe more luck. <https://github.com/theyosh/TerrariumPI/discussions>

**Comment by vikrilow** [comment]
Yes, you can close it.
Really I've change Hid lamp for 1 Arcadia fluorescent and parameters has improved a lot.
Maybe, for my enclosure and weather from my location, hid lamps aren't best option.
