### ISSUE TITLE
TP v4 - no dashboard available

### ISSUE THREAD

**Issue by jornobe** [theyosh/TerrariumPI#600]
v4 installed nicely today, well done on the multi enclosure and areas component! 👍

In the sidebar, when expanding <home> and then clicking on <dashboard>, nothing happens. I have the <all sensors> page opening just fine but no dashboard.

Anything I can do to activate a dashboard as we had it in the previous version?

**Comment by theyosh** [comment]
Hi, I am not sure what you mean? I guess you do not have sensors that are auto-detected. So it could be that the dashboard is empty, or not showing up. I will try to test this.

But could you post a screenshot in the mean time? That makes it easier to understand.

**Comment by theyosh** [comment]
If I have zero hardware connected, I get this empty dashboard:
![image](https://user-images.githubusercontent.com/8080177/131349018-a621c2d9-264e-4717-8566-c17209498fb0.png)
So it should work. If you post a screenshot we can compare

**Comment by captainboto** [comment]
I have this issue yesterday 
you try Clear cached browsing data. it's fixed for me

**Comment by jornobe** [comment]
> I have this issue yesterday you try Clear cached browsing data. it's fixed for me

Should have been my first attempt to resolution, awesome! Works great now!

@theyosh , solved by clearing cache

**Comment by theyosh** [comment]
Yeah, there is some heavy caching in the code. This to reduce the load on the Pi. But it has it downsides. So I am currently working on a caching fix.

**Comment by theyosh** [comment]
I will close it for now. As I also have updated the code. So to make sure you have the latest code that should tackle about 80% of the caching issues after adding/updating/deleting data.

So do a `git pull` and restart TerrariumPI: `sudo service terrariumpi restart`
