### ISSUE TITLE
Problem since update

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#61]
![grafik](https://user-images.githubusercontent.com/31970192/33240421-021262bc-d2b6-11e7-8c60-88826e3220d3.png)

**Comment by theyosh** [comment]
Your pi is not able to resolve DNS. Please restart your PI

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/33240729-1bd47a78-d2bb-11e7-9084-82b7e2c0cb98.png)

I do not understand it my sensors always show correct values on the Pi only in the interface

**Comment by vanessa2013** [comment]
Your interface has a lot of problems with DHT22 and DS18B20

**Comment by vanessa2013** [comment]
Can it be on my port?

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/33240918-deb3030e-d2be-11e7-9e08-aad64439aa9d.png)

**Comment by theyosh** [comment]
Close this. Same as https://github.com/theyosh/TerrariumPI/issues/52
