### ISSUE TITLE
[BUG]: Dashboard is empty

### ISSUE THREAD

**Issue by kaju666** [theyosh/TerrariumPI#610]
**Setup:**
 - TerrariumPI version: 4
 - Python version: 3
 - Raspberry PI: 4

**Describe the bug**
Dashboard is Empty, but everything else works.

**To Reproduce / Installation steps**
As in instruction.
Stopped old.
mv /home/pi/TerrariumPI /home/pi/TerrariumPI.old
git clone --branch 4.x.y.z --depth 1 https://github.com/theyosh/TerrariumPI.git
cd TerrariumPI
sudo ./install.sh
Restarted Pi

**Screenshots**
![image](https://user-images.githubusercontent.com/12675680/134584374-7572f21f-af73-47ac-8aee-58e05b47d24c.png)

**Comment by theyosh** [comment]
Hmm, I am not sure what is causing this. But I think the easiest solution now is to stop TP4, and remove the database and restart TP4.

So remove the file `/home/pi/TerrariumPI/terrariumpi.db` and restart.

Else, try to if there are javascript errors in the browser. But I can't reproduce this.

**Comment by kaju666** [comment]
it's chrome issue but i can't figure it out. deleting webpage data and cache didn't help.
on edge is working

**Comment by theyosh** [comment]
Hmm, with Chromium I do not have any issues. I use Firefox normally. But does Chrome not give an error in the developer console?

**Comment by kaju666** [comment]
for no reason it started to work... :)
