### ISSUE TITLE
[BUG]: API on version 4 not fully working.

### ISSUE THREAD

**Issue by kaju666** [theyosh/TerrariumPI#611]
****Setup:**
 - TerrariumPI version:  4
 - Python version: 3
 - Raspberry PI: 4

**Describe the bug**
Some API's are not working on version 4.
for example: /api/uptime/ giving 404 also on your site terrarium.theyosh.nl
other like api/sensors/; /api/relays/; /api/enclosures/ are working.

Also i found that on verion 4 there must be "/" on the end. On version 3 api link was without last "/"

**Comment by theyosh** [comment]
The API is different. I did not make the new documentation for this. The urls are changed. Long story....

**Comment by kaju666** [comment]
ok :) will be waiting for some docs :)

**Comment by theyosh** [comment]
Here is an update. Not fully up to date... but working on it: https://terrarium.theyosh.nl/api/doc/
