### ISSUE TITLE
[BUG]: DC Dimmer Relay turns on, then immediately off.

### ISSUE THREAD

**Issue by Artaesius** [theyosh/TerrariumPI#613]
**Setup:**
 - TerrariumPI version: 4.0.0
 - Python version: 3
 - Raspberry PI: 4B

**Describe the bug**
DC Dimmer Relay is changed to on with a % value as connected temp probe is registering a low alarm. Within the same second, the enclosure updates and toggles the Relay state to off and changes the value to 0. The temp probe notes no change in temperature. 

**To Reproduce / Installation steps**
Fresh install on PI following instructions provided. Temp probes are recognized. I update localization settings on the system. Then I change the settings for the temp probe as shown in the screenshot below. I add the DC Dimmer relay with the settings shown in the screenshot. I create the enclosure and area with the settings shown. I then ensure that the temp probe is triggering a low alarm to observe the behavior of the relays. 

**Expected behavior**
I expect that since the temp probe is triggering the low alarm that the DC dimmer will start to ramp up to to bring temperature within value and remain on for at least the 120 sec that area is set to. When temperature is near the average of the high/low range, I expect the dimmer to decrease as the average is approached. If the high alarm is triggered, I expect that the dimmer will be at 0.

**Screenshots**
Temp Sensor Settings:
![image](https://user-images.githubusercontent.com/39136664/137427141-1770b740-4c09-4fff-85a5-f5f0795bedd4.png)

Local Settings:
![image](https://user-images.githubusercontent.com/39136664/137428998-5d577320-a374-4963-9bcd-fe5ff4798419.png)

DC Dimmer Relay Settings:
![image](https://user-images.githubusercontent.com/39136664/137427242-96a2098c-7493-4dae-9675-7458aa499ce5.png)

Area Settings (Low Alarm):
![image](https://user-images.githubusercontent.com/39136664/137427308-aecaccdb-d5ee-49cb-a832-1f4e6334f6a1.png)

Area Settings (High Alarm):
![image](https://user-images.githubusercontent.com/39136664/137427388-d6ed95ea-11ba-477a-beab-9c39b19e3b4f.png)

Log showing relay triggering off immediately:
![image](https://user-images.githubusercontent.com/39136664/137427074-0ec93a26-ae85-411d-b19a-e81d2f78663d.png)

Log showing relay on for a short period before turning off:
![image](https://user-images.githubusercontent.com/39136664/137428461-1f0645f0-2df8-43f4-9d96-5c3170b17678.png)

**Additional context**
Occasionally I will get a maximum of 30-ish seconds of the relay being on, but then it cycles back off before turning back on without any change registered by the temp probe (Last screenshot).

**Comment by theyosh** [comment]
Also, use the 60 secs settle time of the high tab, in the low tab and change the power on time to zero. Because you are using a dimmer, that will try to stay at the average of the min and max alarm values.

Then you get the following logic:

When to cold, turn on the dimmer, with an update value of 60 seconds (settle time). So every 60 seconds the dimmer will change to get to the average value.

This documentation is lacking right now. It is the last thing that I need to documentate
