### ISSUE TITLE
[BUG]: Energenie USB Socket 2 does not turn off anymore

### ISSUE THREAD

**Issue by wolli1234** [theyosh/TerrariumPI#619]
Hello Yosh,

The relay Socket 2 of Energenie USB with address 2,01:01:51:44:b7 does not turn off anymore. I encountered this bug several times now. It runs as expected for several days, and suddenly the problem appears. It is turned on and off by the humidity sensor.

Switching to manual mode does not help. If I manually turn the relay on I can hear a clicking sound, but when turning it off, no clicking sound in the Energenie USB plug happens. So the turning off signal is not forwared to the USB power socket. The Log file does not output any errors.

I also set the relay to ignore. Now it is gone and I can't get it back. When scanning for new relays: "0 new relays were found".  When I try to add the relay manually again an error appears: "Cannot be stored in database."

I'm not sure how I got rid of this problem last time. I did several reboots, deleting the relay etc. and at one point it was back in working condition. I think maybe I had to remove the whole terrariumpi.db file.

**Setup:**
 - TerrariumPI version: 4
 - Python version: 3
 - Raspberry PI: 3B

1. How can I get an "ignored" relay back?
2. The Bug is very strange, maybe a hardware issue of the Energenie USB? If it is a software bug, this could get really bad if a heater or something is connected. Unfortunately there is no output showing an error.

Is there something I can try except for deleting the db and start again? Right now I changed to a different socket, to check if it happens again.

Cheers,
Wolli

**Comment by theyosh** [comment]
Any updates on this?

**Comment by theyosh** [comment]
Any updates?

**Comment by wolli1234** [comment]
Not really, but I think it was a hardware issue. I have switched to script relays in the meanwhile and don't use the usb socket anymore, so I can't continue testing.

**Comment by theyosh** [comment]
Then I close this issue. Thanks for the feedback.
