### ISSUE TITLE
Multiple cam's

### ISSUE THREAD

**Issue by stevoace** [theyosh/TerrariumPI#63]
Hey, so i have added 2 cameras to the pi, one using the on board interface, one though USB.
Under the webcam settings it shows the 2 active feeds, however under "Show" only the most recently added camera will appear.

**Comment by theyosh** [comment]
This is probably browser cache. Clear it and try again. Else, restart terrariumpi and try again.

It is somewhat known that adding and changing settings will 'not work' due to browser cache
