### ISSUE TITLE
[BUG]: Relays not switching through TerrariumPI but do through python script in console

### ISSUE THREAD

**Issue by mink8mink** [theyosh/TerrariumPI#649]
**Setup:**
 - TerrariumPI version: Version: 4.1.0
 - Python version: Python 2.7.16 
 - Raspberry PI: Pi4 Model B

**Describe the bug**
 Relays not switching through TerrariumPI but do through python script in console

here is the relay I am working with:

JBtek 8 Channel DC 5V Relay Module for Arduino Raspberry Pi DSP AVR PIC ARM 

https://www.amazon.com/dp/B00KTELP3I/ref=cm_sw_r_cp_api_glt_i_QT8K54XW6TSPQ7YPYXTG?_encoding=UTF8&psc=1

I have tried everything under the sun. TerrariumPI will install the relay but will not switch them???? I can switch them through a test script in python though. I am desperate. I've googled to the ends of the earth and cannot get this to work. I did get it to work with TP v3.......

PLEASE HELP!

****UPDATE****

I put my SD card in my old PI 2B and got the same results. Relays do not switch on TPI.

Also, here is the script that will operate the relays outside of TPI. Kudos to #skiwithpete
https://www.youtube.com/channel/UCuwFJkahErfhbroefg12lzA

```
#!/usr/bin/python
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)

# init list with pin numbers

pinList = [2, 3, 4, 17, 27, 22, 10, 9]

# loop through pins and set mode and state to 'low'

for i in pinList:
    GPIO.setup(i, GPIO.OUT)
    GPIO.output(i, GPIO.HIGH)

# time to sleep between operations in the main loop

SleepTimeL = 2

# main loop

try:
  GPIO.output(2, GPIO.LOW)
  print ("ONE")
  time.sleep(SleepTimeL);
  GPIO.output(3, GPIO.LOW)
  print ("TWO")
  time.sleep(SleepTimeL);
  GPIO.output(4, GPIO.LOW)
  print ("THREE")
  time.sleep(SleepTimeL);
  GPIO.output(17, GPIO.LOW)
  print ("FOUR")
  time.sleep(SleepTimeL);
  GPIO.output(27, GPIO.LOW)
  print ("FIVE")
  time.sleep(SleepTimeL);
  GPIO.output(22, GPIO.LOW)
  print ("SIX")
  time.sleep(SleepTimeL);
  GPIO.output(10, GPIO.LOW)
  print ("SEVEN")
  time.sleep(SleepTimeL);
  GPIO.output(9, GPIO.LOW)
  print ("EIGHT")
  time.sleep(SleepTimeL);
  GPIO.cleanup()
  print ("Good bye!")

# End program cleanly with keyboard
except KeyboardInterrupt:
  print ("  Quit")

  # Reset GPIO settings
  GPIO.cleanup()


# find more information on this script at
# http://youtu.be/oaf_zQcrg7g
```

**Comment by theyosh** [comment]
This is just a simple GPIO relay. But in your script you have BCM port numbering. That needs to be translated to physical numbers. https://pinout.xyz/

So, based on:

`pinList = [2, 3, 4, 17, 27, 22, 10, 9]`

You should use the translated number as address at a GPIO relay.

2 = address 3
3 = address 5
4 = address 7
17 = address 11
27 = address 13
22 = address 15
10 = address 19
9 = address 21

The above script will never work, as it runs in a loop and does not give the correct output.

So I would suggest to add a GPIO relay with address 3, and see if that works. Then just add all the other relays as GPIO relay type with the translated address in the list above.

**Comment by mink8mink** [comment]
Yosh, 

You are the man! Thank you so much...Something so simple. I did what you said and am now getting it to recognize the relay..One more thing...After I added them I tried to set them up in an area with a timer and get an error when i save...

**SAVE ERROR 
Area could not be added. Invalid isoformat string:"**

It then shows this under status of the area:

**Day: Invalid date - 9:46:46 PM (Invalid date)**

Thank you for creating this awesome piece of software and for supporting it's users as well as you do. We appreciate you man :)

**Comment by mink8mink** [comment]
Ok, I think I got it. I believe it was the safari on Mac that was causing the save issue. I got no issue when using the phone browser or Firefox. 

I also noticed that setting up areas are touchy. If you mess up delete everything, reboot and try again. I also had to setup my relays as GPIO inverse as they were doing the opposite from what they were supposed to do. Hope this helps someone!

**Comment by theyosh** [comment]
Hi, the deleting of areas did have a bug #652 . That will be fixed in the next release. And the area part is pretty new, and complex, so there could be still some bugs... 

Ah, crap, yes, I use the browser locale to translate the date and time to a timestamp. I am unable to test Safari, but it was working for Chrome, which is almost... almost the same engine.. But lately, Apple and Safari are doing strange stuff...

About the GPIO relays. Somehow there are two version, or you can connect them differently, so I do not know why sometimes the inverse version is needed. But as I have had this in the past, I just added an inverse option to it.

**Comment by mink8mink** [comment]
Thanks Yosh! Its been running perfect ever since. 

The great thingabout it is that regardless of the internet connection the relays will stay on schedule....This is the opposite of all the "smart" switches out there which won't turn on or off if the connection drops connected. My setup is in the garage and wireless is spotty but TPI works regardless.

**Comment by mink8mink** [comment]
Yes. Sir!

 

From: TheYOSH ***@***.***>
Reply-To: theyosh/TerrariumPI ***@***.***>
Date: Friday, January 28, 2022 at 4:17 PM
To: theyosh/TerrariumPI ***@***.***>
Cc: mink8mink ***@***.***>, Author ***@***.***>
Subject: Re: [theyosh/TerrariumPI] [BUG]: Relays not switching through TerrariumPI but do through python script in console (Issue #649)

 

So can we close this issue?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by theyosh** [comment]
Thanks!
