### ISSUE TITLE
[BUG]: TerrariumPi does not install on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by vlreinier** [theyosh/TerrariumPI#650]
**Setup:**
 - TerrariumPI version: Latest
 - Python version: 3.9.2
 - Raspberry PI: 3B+

**Describe the bug**
During installation the following error code appears and TerrariumPi can not be started:
100 cannot access 'venv/lib/python*      packages/bluepy/bluepy-helper' No such file or directory.
Line 204: bc: command not found ./install.sh

**To Reproduce / Installation steps**
Clean install of Raspberry Lite on Raspberry Pi 3B+ no desktop version, SSH enabled.

I tried:
- update and full upgrade
- `sudo ./install.sh 3`

**Expected behavior**
A working TerrariumPi webserver :)

**Screenshots**
![20220125_142844](https://user-images.githubusercontent.com/43336873/150986835-0d8fb699-8bd1-4e5e-a8bf-37a45695a692.jpg)

**UPDATE**
I ran the following commands to manually install bluepy:
```
sudo apt-get install python3-pip libglib2.0-dev
$ sudo pip3 install bluepy
```
Then i ran `sudo ./install.sh 3`
I sam stilling getting a bunch of errors but it does seem to progress, but it is now for at least 3 hours stuck at installing opencv-python-headless...

Also tried different Python versions, did not work.

**Comment by vlreinier** [comment]
It works on the Raspberry Lite Legacy image, awesome! :)

**Comment by theyosh** [comment]
Hmm, yeah, the latest image is not working. I thought I made some fixes for that, but it can be that I did not release that code..

So I am happy you figured it out. For now, stick with the old legacy image.

**Comment by vlreinier** [comment]
Ah so it was not me, good to know!

Is there support for creating custom lighting schemes with leds?

**Comment by theyosh** [comment]
For now, I think I close this issue. There are some code fixes in the queue for the next release: https://github.com/theyosh/TerrariumPI/commits/4.x.y.z

**Comment by timmakken** [comment]
Hi Yosh, im having the same issue with latest TerrariumPi. any thoughts on how i should fix this i installed bc manually so no issues there but the open-csv-headless is just stuck without any errors. ( same specs as @vlreinier )

**Comment by vlreinier** [comment]
Easiest way to fix this is using the legacy 32bit no desktop version. That one works for sure. Dont forget a correct networking interfaces file, or you will encounter sleep mode issues.

**Comment by theyosh** [comment]
If it does not work please follow the installation instructions: https://theyosh.github.io/TerrariumPI/install/#raspberry-pi
