### ISSUE TITLE
[BUG]: (V4, x.y.z) - Header door status incorrect

### ISSUE THREAD

**Issue by Swiftnesses** [theyosh/TerrariumPI#659]
Please see attachedbelow image :)

<img width="1653" alt="Screenshot 2022-02-07 at 08 19 58" src="https://user-images.githubusercontent.com/1001877/152750640-1b7cdc7d-a54e-4ba5-93f0-60b9ec858cc3.png">

**Comment by theyosh** [comment]
Is this door also a door in an enclosure? Else I do not know if it is a active door. So I guess when you add this to an enclosure it will change the all door status

**Comment by theyosh** [comment]
Does it work better when you have created an enclosure with doors? Here it does work. Sometimes a bit slow in the GUI

**Comment by theyosh** [comment]
Closing due to no reponse
