### ISSUE TITLE
Cant add sensor

### ISSUE THREAD

**Issue by badner** [theyosh/TerrariumPI#66]
Hey, I really like your project and was able to get everything done so far. But now I'm stuck at adding a am2302 temp/hum sensor. I wired everything like explained in your program. But somehow it doesn't want to recognize the sensor. Would be nice if you could held. 
Thanks

**Comment by theyosh** [comment]
Have you tried: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-test-a-dht11-dht22-or-am2303-sensor

Pay attention to the pin numbering. For testing with the link above, use BCM numbering. See for translation the pinout.xyz page. When the tests are working, you know the hardware is ok. Then you should be able to add it to my software.

Also you can try:
https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi

**Comment by Barbara1984** [comment]
Can it be that there are problems with the Pi3 Bitbang when connecting two DHT22?

**Comment by theyosh** [comment]
Not that I know off. But I can't judge without debug logging. So try debugging according the links in the first message. And post outcome here.

**Comment by theyosh** [comment]
Make sure you use different GPIO pins for each DHT sensor. They can't share GPIO

**Comment by badner** [comment]
U Legend!
