### ISSUE TITLE
[FEATURE]: Area actuation No alarm

### ISSUE THREAD

**Issue by cmonicob** [theyosh/TerrariumPI#669]
Would it be possible to incorporate an action in the areas when there is no alarm?

I have a waterfall that I would like to be on only while the water level in the tank is between the minimum and maximum values

**Comment by cmonicob** [comment]
Thank you very much.

I was also thinking if there would be the possibility of integrating the reverse mode of the Ralays.

For example: I have a fogger and I would be interested in turning it on as long as it does not exceed the maximum humidity of a sensor.

I think it would be an interesting option that would give much more flexibility when programming the microclimate

**Comment by theyosh** [comment]
Hmm, I think your not correct. It can be already done. Specify the min and max alarm values of the sensor close to each other. So low alarm is 79% and high alarm is 80%. Then the fogger will run until the 79%, which is close to the 80%.

Why add more logic to ignore the lower alarm value. Just put it close to the max alarm value and you got your setting. Using 2 alarm values give always more flexibility then using only 1 alarm value. So I have to disagree on that.

**Comment by cmonicob** [comment]
I explain my casuistry or what I have in mind,

To raise the humidity status I have 2 methods (foggers, and rain sprinklers) my intention is with the same humidity sensor to control 2 areas:
- Area 1 for the rain sprinklers that would raise the high humidity to the minimum point
- Area 2 for the foggers that would maintain the humidity until the maximum alarm

**Comment by theyosh** [comment]
Hmm, I see your case. I have to think about this. I think this will add an extra option in the area setup. But not sure how yet.

As you wish is to ignore the lower alarm value. But there could also be people that want to ignore the high alarm value. So I want it to make a generic option for it.

**Comment by cmonicob** [comment]
I had thought of having a field to add the relays that work inversel
![Area_Settings_Type](https://user-images.githubusercontent.com/6905923/158234288-1da7ce89-c68e-4e5d-abab-8d4983795b77.png)
y

**Comment by theyosh** [comment]
So, I used a different approach. If you select sensors, you will get an extra option in front of the relay in order to ignore either the low alarm value at the low alarm part, or vise versa with high alarm.

This will result in the scenario for your mister.

This code is only in the 4.x.y.z branch if you want to test it.

**Comment by cmonicob** [comment]
I think there is some error in the filters, or am I misunderstanding how it works?

![image](https://user-images.githubusercontent.com/6905923/160928885-2cdf8067-1bcc-45da-aa4d-feae554c54f7.png)

**Comment by theyosh** [comment]
Hmm, this is strange. I have to look into this.

**Comment by theyosh** [comment]
Found the problem and fixed it. Do a `git pull` and rerun the installer `sudo ./install.sh`. As there are new libraries in use for new sensors.

Then you should be able to save the new area without any errors.

**Comment by cmonicob** [comment]
is ok
