### ISSUE TITLE
Feature Request: CSV / XLS export

### ISSUE THREAD

**Issue by jprjr** [theyosh/TerrariumPI#69]
AFAICT, sensor data, weather data, etc is stored in a Sqlite database.

It would be really convenient to be able to download CSV/XLSX data via the web front-end.

**Comment by theyosh** [comment]
I agree. So a CSV export will be added.

**Comment by theyosh** [comment]
If you check out the new code, there will be an export option in the settings menu in each graph

**Comment by Aapjes94** [comment]
After the update for this feature I've been getting these errors:

2018-01-04 16:01:56,019 - ERROR - terrariumCollector - TerrariumPI Collecter exception! (DatabaseError('database disk image is malformed',),)

2018-01-04 16:01:56,024 - WARNING - terrariumCollector - TerrariumPI Collecter recovery mode is starting! (True,)

Is this related to this update or have I messed up somewhere else?

**Comment by theyosh** [comment]
No, this is the result of my bad programming. I did not make a clean shutdown. So it could be that you terminated the software while writing to sqlite. But the recovery should take care of it.

If not, the only solution is to delete the history.db file. It will then be recreated with a new restart

**Comment by theyosh** [comment]
So, for now I close this. Export is rather simple, but effective for now
