### ISSUE TITLE
Timer functionality per switch

### ISSUE THREAD

**Issue by theyosh** [theyosh/TerrariumPI#72]
Add an option to created separated timers for switches. This will allow the switch to turn off and on on a time based schedule.

Needed input per switch:

- Timer start time - ex: 09:00
- Timer stop time - ex: 22:00 or 10:00 PM
- Timer on duration - ex: 180
- Timer off duration - ex: 90

In this example the timer will run between 9 AM and 10 PM. In that period the power will be on for 180 minutes and then off for 90 minutes. This repeats till 10 PM.

If this timer is enabled on the switch, it **cannot be used** on the environment page. Because the switch has its own timer logic and not using the central logic anymore.

The on and off durations are in minutes.

The power switch will be checked every 30 seconds if a power switch change is needed.

The power switch indicator will have a clock icon to it to show that it is timer based.

![timerswitch](https://user-images.githubusercontent.com/8080177/35471440-3bf6478c-0353-11e8-8cc3-3258813f3383.png)

**Comment by Aapjes94** [comment]
I tried to update but things got messed up. From the TerrariumPi folder, I ran sudo git pull, but got the message that it was already up to date. Not sure if what I did next was stupid but I ran ./install anyway and now corrupted the whole thing. 

Can you confirm that it was stupidity on my part? Or did something strange happen due to the code?

**Comment by theyosh** [comment]
Please reopen new issue. Your problem is not related to this issue

**Comment by Barbara1984** [comment]
Nothing has been uploaded in the code here :-)

**Comment by Barbara1984** [comment]
Hi, I do not want to be silly but when will this update come about? :-)

**Comment by theyosh** [comment]
Updates for this feature can be tested in branch https://github.com/theyosh/TerrariumPI/tree/feature/switch_timers. So update with `git pull`. Then use `git checkout feature/switch_timers`. Then restart TerrariumPI and clean your browser cache.

Also keep a copy of your settings files before testing this.

**Comment by Barbara1984** [comment]
Ok, thanks, I'll tell you how it works

**Comment by Aapjes94** [comment]
From my end, this branch seems to work. The update worked and it's installed. The 'translations' are still missing, so it isn't exactly clear how this function work. Especially the interactions with the environment settings.  I'd assume timed switches won't be controllable with the environment settings, which wouldn't make much sense.

**Comment by theyosh** [comment]
At this point I think I got it working. So it could be fully tested now.

**Comment by Barbara1984** [comment]
Very cool thanks for your work I will test it tomorrow.

**Comment by theyosh** [comment]
Clear browser cache, and select active at the timer pull down when editing the switches.

**Comment by Barbara1984** [comment]
Sorry maybe I'm too stupid but I think nothing has done the update and emptied cache. But I can not find the timer mode.

**Comment by Aapjes94** [comment]
It worked for me so something went wrong during your install. Are you sure you used `git checkout feature/switch_timers` after `git pull`


`cd TerrariumPi`
`git pull`
`git checkout feature/switch_timers`
`sudo ./install.sh`
probably a `sudo reboot` is needed after this as well to get everything set up properly

**Comment by Barbara1984** [comment]
Thanks for the help now it works :-)

**Comment by theyosh** [comment]
Cool, I have it also merged to master branch. So everybody can use it now :+1:

**Comment by Barbara1984** [comment]
Can you please # 82 again open the subject is unfortunately not done :-(

**Comment by theyosh** [comment]
Update the code that timer functionality is also in all the environment parts. Same logic.
