### ISSUE TITLE
Heater config window 

### ISSUE THREAD

**Issue by 19Crotalus74** [theyosh/TerrariumPI#73]
Hi !
Is it possible to become more than one Heater config windows? 
I have 3 terrarien so i need 3 different heaters with 3 different Sensors.
Sorry my english is not the best

**Comment by Aapjes94** [comment]
No, that is not possible at the moment.

**Comment by theyosh** [comment]
Not at the moment. The easiest way now is using multiple Raspberry Pi's.

Because if this will be added, then also the possibility for multiple sprayers and light systems. etc.. So that will totally change how the software will work...
