### ISSUE TITLE
Update yesterday?

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#74]
Hi, sorry but I'm too stupid or I just do not think so, but in the code was not changed, right?

**Comment by Aapjes94** [comment]
Doesn't seem that way. If you go to the main project page, it says the last commit was 9 days ago. Just above all the files and folders on the right side.

**Comment by theyosh** [comment]
No, no changes.

I created a feature so that we will not forget about it. But at this time, I do not have much time to develop. Also I have other things to do.

So no, there is no code change. But it will be, and then I reference to the requested feature for tracking.

**Comment by Barbara1984** [comment]
Ah ok then I know myself :-)
