### ISSUE TITLE
[BUG]: Daylight savings?

### ISSUE THREAD

**Issue by G4KCM** [theyosh/TerrariumPI#745]
Hi,
U.K. daylight savings ended last night…
Sunday, 30 October 2022, 02:00:00 clocks were turned backward 1 hour to Sunday, 30 October 2022, 01:00:00 to local standard time instead.  Around that time the heaters have caused quite a large temperature excursion.  I can’t see anything else happening around that time so thought I would mention it.[
![32F91B4A-FB0A-4E37-AA6A-5193D7F88D00](https://user-images.githubusercontent.com/17541578/198900850-2da8b82d-c362-4ed8-b0c8-c3653e053848.png)
![2EBD1D3E-6C75-4DE6-850A-F9B05C77834C](https://user-images.githubusercontent.com/17541578/198900852-4d4ec5fe-dc44-4261-bf7a-bcf31354fa52.png)
](url)

**Comment by theyosh** [comment]
I guess it is. I was a bit less effected as for me the relays did not toggle on. And we shift at 3 o'clock to 2 o'clock back. 

![image](https://user-images.githubusercontent.com/8080177/198903727-4a9b32d1-a7ff-470e-bceb-6fe2bee3fa5b.png)

But the strange thing with your issue, is that it did not toggled down the relay based on temperature. The only thing I can think of is that there was a negative difference value, as you go back 1 hour. And that would case some triggers not to fire for 1 hour...

I can have a look at that difference calculation. But it is hard to test, and it only happens once 1 year... So not sure if I can fix this.

**Comment by G4KCM** [comment]
Yes, what you say appears to be what happened.  Just thought I would mention it as it looks like the control loop cycle is linked to real time which might explain it.  Not a major issue for me either but if someone was pumping water it might be a bit more of an issue!

**Comment by theyosh** [comment]
Made small adjustment in de settle time calculation. That is the only thing I can think off. Thanks for reporting.
