### ISSUE TITLE
My relay accepts the On/Off backwards ? 

### ISSUE THREAD

**Issue by jbrooks4** [theyosh/TerrariumPI#75]
what did I do wrong, when I set the timer on my relay and have a light plugged in it I have the On time set to 7:00am and off time 5:00pm and it does the opposite, it turns it off at 7 and on at 5. It is a GPIO relay

**Comment by Barbara1984** [comment]
I think you have to take GPIO reverse.

**Comment by jbrooks4** [comment]
Cheers that did it !

**Comment by Aapjes94** [comment]
Either you have selected the GPIO reverse hardware type in the switch settings, or you have a wire connected incorrectly.
