### ISSUE TITLE
[BUG]: Notification Setup 

### ISSUE THREAD

**Issue by sni89** [theyosh/TerrariumPI#758]
**Setup:**
 - TerrariumPI version: 4.6.0
 - Python version: [e.g. 2 or 3]
 - Raspberry PI: 4

**Describe the bug**
It’s not possible to setup A new display or other notification due the setup area itself is missing 

**To Reproduce / Installation steps**
Went to notifications, wanted to setup a display. The setup area directly leads me to notification settings not to the setup itself. Ends with an error message that setup is missing. 

**Expected behavior**
Add of a display and messages on it 🙂

**Screenshots**

![0A347151-A8B7-4531-A56A-82126D3E9AA0](https://user-images.githubusercontent.com/56272047/207960043-647bb1fb-4ed5-4dc5-a033-6f0d467f5335.jpeg)

**Comment by theyosh** [comment]
Hmm, this I need to look into it. But a bit of warning, the display functionality is not that good :(. It is difficult to make it all variable on a small screen.

So most people will end up creating their own script to display information in the way they want.

Nevertheless I will look this issue.

**Comment by theyosh** [comment]
Ok, found the problem. Do a `git pull` and reload the GUI. That should fix this problem.

In the screenshot I miss some fields. This is due to a javascript error. That should now be fixed. For a display, you need to specify the hardware type and the I2C address.

**Comment by theyosh** [comment]
Did you had time to test the fix? For me it is working.

**Comment by sni89** [comment]
At least I have options like address and displaytype back. But when I want to set up the message it’s trapped in loading the page. I see the page behind the loading symbol but it won’t let me go on. This could be a „mobile user“ problem did not try on a desktop so far. 

![50A344C1-2490-4CAA-830A-2A7DA616578C](https://user-images.githubusercontent.com/56272047/209324116-55dfaeb4-8d67-475f-a927-044dc434935f.png)

**Comment by theyosh** [comment]
Hmm, this is now fixed. Do a `git pull` and restart TP4. Than it should work again.
