### ISSUE TITLE
[BUG]: Dimming not working

### ISSUE THREAD

**Issue by Jexkin** [theyosh/TerrariumPI#764]
**More info**
Hey, this morning I noticed that my LED lights were fully on after about a minute or two. (Seems like it did the same last night as well)
Normally they dimm to 100% (or 0%) within 80 minutes just like I set it up in the Area settings.
A few days earlier it still did dimm just like it should so I'm not sure why there's a problem now, I already checked my hardware.

**Setup:**
 - TerrariumPI version: 4.6.0
 - Raspberry PI: 4
 - LED Warrior 18 Dimmer

**Describe the bug**
LED lights are dimming to 100% (or 0%) within a minute or so, check picture below.

**Expected behavior**
Lights slowly dimm from 0% to 100% (and vice versa) within 80 minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/67230363/209780486-ede7aa38-93ad-4b91-821d-aaf9ea7f067f.png)

**Additional context**
Just a side note: When clicking the "?" in the Area settings, it says that the max duration for the "Dimmer duration" is 180 minutes but the sliders only go to 100 minutes.

**Comment by theyosh** [comment]
Hi, there was a bug with the dimmer duration. Could you do a `git pull` to make sure you have the latest version. And then I think it should work again after a restart of TerrariumPI.

About the 100 min. vs. 180 min. I have to look into it...

**Comment by Jexkin** [comment]
Did a `git pull` and restarted TPi. Will give you an update in about 8 hours when the lights should dimm down :)

**Comment by theyosh** [comment]
Haha, I thought already of that :). So lets see if it works like expected tomorrow.

**Comment by theyosh** [comment]
Now I have also fixed the GUI. If you do another `git pull` but than just reload your GUI, you should be able to delay till 180 minutes again if needed.

**Comment by Jexkin** [comment]
Did another `git pull` but it seems like that fix didn't work. Also did another restart just to be sure but that didn't do anything either
![image](https://user-images.githubusercontent.com/67230363/209805140-e8047152-11b5-4d19-bc34-65966d12b73f.png)
Created another enclosure and area just to see if my existing enclosure/area was causing the fix not to work but seems like that's not the case.

**Comment by theyosh** [comment]
Than you did not refresh the GUI. Make sure you hold the shift key while reloading. I just tested and I have 180 minutes.

**Comment by Jexkin** [comment]
Yep, I just found the issue on my side. I never switched back to the main branch after the LED Warrior 18 testings.
Works now, thanks!
Lights should dimm down in roughly an hour so I'll update later on that one.

**Comment by theyosh** [comment]
And still working? Than we can close this issue?

**Comment by Jexkin** [comment]
Yes, thank you!
