### ISSUE TITLE
[BUG]: 4.5.0 -to- 4.6.0 - Main web page now blank (white)

### ISSUE THREAD

**Issue by shane64** [theyosh/TerrariumPI#773]
**Setup:**
 - TerrariumPI version: 4.6.1
 - Python version: Python 3.7.3
 - Raspberry PI: Raspberry Pi 2 Model B Rev 1.1

**Describe the bug**
Following update from 4.5.0 to 4.6.0, the main page is now a blank white screen.  There is HTML source code on the page generated from the webserver noted below. 

**To Reproduce / Installation steps**
I had been upgrading (manual method) through the 4.x versions with no issues and when going from 4.5.0 to 4.6.0, the main page now appears completely white.  I upgraded today from 4.6.0 to 4.6.1 and there was no change.  

**Expected behavior**
See the TerrariumPi home page that I was used to seeing so that I could manage the TerrariumPI.

**Screenshots**
Web page source code:

![image](https://user-images.githubusercontent.com/45738667/210823016-2db3b756-984b-4ae0-9429-eeeaed9789a6.png)

**Additional context**
This TerrariumPI install is not running a terrarium yet - I just have a few sensors and a relay hooked up to it for testing (so very "vanilla" at the moment).

I have run in debug mode and there are no errors (though this line appears when I first try and load the main page, but not on subsequent loads):

```
/home/pi/TerrariumPI/venv/lib/python3.7/site-packages/bottle.py:3380: DeprecationWarning: Absolute template path names are deprecated.
  fname = self.search(name, self.lookup)
```
I have reloaded in the browser with the shift key and it loads the same way on multiple browsers and multiple machines.

What else should I be checking?

Thank you.

**Comment by theyosh** [comment]
Did you try to hold the shift key and then reload the page? Else there should be a javascript error in the browser console. Without that, I cannot see what is happening.

**Comment by shane64** [comment]
Right!  Thank you.

Console output here:

```
Uncaught SyntaxError: missing } after property list 10.10.10.15:8090:32:28
note: { opened at line 29, column 2210.10.10.15:8090:29:22
Uncaught TypeError: gw.available_sensor_types is undefined
    app http://10.10.10.15:8090/main.js:483
    <anonymous> http://10.10.10.15:8090/main.js:556
main.js:483:1789
```
Thanks again.

**Comment by theyosh** [comment]
Strange... could do a `git pull` to make sure you are on the latest version... I am updating some code.. but this should not happen

**Comment by shane64** [comment]
Just did one now.  I get the same JavaScript error.  Thank you.

**Comment by theyosh** [comment]
Oh wait... you have a clean setup without any sensors.... Hmm, I need to test that...

**Comment by shane64** [comment]
There are three sensors hooked up to it yet (one enclosure, one area) but beyond confirming the sensors work (and show graphs), I have not created any other logic.

**Comment by theyosh** [comment]
Do a `git pull` and reload in the browser. I think I found the issue.

**Comment by shane64** [comment]
I am sorry to report that I'm getting exactly the same error in the browser console after doing the `git pull` (and reloading with the shift key down).  Thank you.

**Comment by theyosh** [comment]
Ok, found the bug. Do another `git pull` and reload the GUI. I think it should work now.

**Comment by shane64** [comment]
That worked!  Thank you!

**Comment by theyosh** [comment]
Nice, thanks for the feedback.
