### ISSUE TITLE
[BUG]: TerrariumPi crashing on startup

### ISSUE THREAD

**Issue by 1ucket** [theyosh/TerrariumPI#781]
**Setup:**
 - TerrariumPI version: 4.6.1
 - Install: Manual
 - Raspberry PI: 4b 2Gb

**Describe the bug**
On startup Terrariumpi is crashing when loading the enclosures.

**To Reproduce / Installation steps**
I can only give clues how this issue might have been produced. I was turning off the Raspberry Pi by disconnecting it from the power source, so it might be that it didn't save everything properly. Other than that I connected a relay in between turning it off and on (on pin 12) but it wasn't yet added in the software. But I've disconnected said relay again and restarted TerrariumPi and the issue is still there.

**Expected behavior**
TerrariumPi starts up properly.

**Screenshots**
I've uploaded the logs [here](https://pastebin.com/9Ayq9C98). You can ignore the 1-wire sensors. I've not gotten them to work yet, but this hasn't been an issue in the past.

**Comment by theyosh** [comment]
I have added some extra checks. Do a `git pull` and restart. I think it should startup again.

**Comment by 1ucket** [comment]
I've already restored a backup (so that my loved beardie doesn't sit in the dark/ cold). So I won't be able to test it. But thank you very much for the quick response, and the fix so that it won't happen again!
