### ISSUE TITLE
Energenie WLAN

### ISSUE THREAD

**Issue by OlivierVanEenoo** [theyosh/TerrariumPI#785]
Using Energenie WLAN relay (EG-PMS2-WLAN).
I can toggle the relay using Python but the example code in de TerrariumPI help does not work posting a http request with password. The example is for the LAN relay and not the WLAN , so maybe they are different.

Do you have any experience or working config for the WLAN relay?

**Comment by theyosh** [comment]
I do not have tested it on a WLAN. But the only difference is the way they are connected. Cable of wireless. But I assumed that the device react the same.

If you can post your Python code here, I can have a look into it.

**Comment by theyosh** [comment]
Any updates? Is this still an issue?
