### ISSUE TITLE
AM2302 readout in dashbord

### ISSUE THREAD

**Issue by vankomicin** [theyosh/TerrariumPI#79]
Hi,
in terminal I can correctly read the AM2302 with
pi@raspberrypi:~/Adafruit_Python_DHT/examples $ sudo ./AdafruitDHT.py 2302 25
Temp=29.3*  Humidity=39.7%
but when I add the temperature and humidity sensor in web interface, there is no readout.
Any ideas?
I'm on pi zero.
![screen shot 2018-01-15 at 17 14 40](https://user-images.githubusercontent.com/35461942/34951953-4e97184c-fa18-11e7-8829-c3ad2751a80c.png)

**Comment by theyosh** [comment]
Ah, that should be easy to fix:

https://github.com/theyosh/TerrariumPI#gpio-numbering

So you have tested number BCM 25, which is 22 in Physical pin numbering. So changing to 22 should fix it. You have to that for both types for the AM2302 (Temp and Humidity).

I will also update the FAQ about this

**Comment by vankomicin** [comment]
Thanks! Now it works. Should have read the FAQs really carefully because this physical and BCM relationship in software. One thing I noted however is the latency before the readings show up in web interface...
Keep up the good work!
Rok
