### ISSUE TITLE
[BUG]: terrarium PCF8574/PCF8575 IOExpander on button

### ISSUE THREAD

**Issue by cmonicob** [theyosh/TerrariumPI#799]
- TerrariumPI version: 4.6.2
 - Install: Manual
 - Raspberry PI: 4

**Describe the bug**
Add new button Magnetic (door) error:
Button could not be added: 'terrariumPCF8574IOExpander' object has no attribute 'set_pin'

**Comment by theyosh** [comment]
Hi, sorry for the late relay. I totally forgot to answer. I have changed the code, which I hope, will now work.

So, do a `git pull` and restart. The above error should be fixed.

**Comment by cmonicob** [comment]
Is Ok

**Comment by theyosh** [comment]
And does it work?

**Comment by cmonicob** [comment]
yes, it works again

**Comment by theyosh** [comment]
Nice, thanks for the confirmation!
