### ISSUE TITLE
Total power (kWh, L) and total price

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#80]
Hi, is it somehow possible to reset the overall performance + total price and get it back to zero?

**Comment by Aapjes94** [comment]
That data seems to be logged in the history.db file. The contents of that file looks like gibberish from Terminal, so I couldn't tell you what that file looks like at a fresh install. If you could find that out you could replace your current file with a 'blanc' history.db file.

**Comment by theyosh** [comment]
The history.db is a sqlite3 file. So use sqlite3 and sql command to read the history.db file if needed.

But the fastest way to 'reset' the data is:

- stop the TerrariumPI software ( https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-stop-terrariumpi )
- remove the history.db file ( rm history.db )
- start TerrariumPI software ( https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-start-terrariumpi 
- )

This will recreate the history.db file with empty values. This will also delete all the existing graph data of the sensors and power switches.

**Comment by Barbara1984** [comment]
Thanks, theyosh, I'll do it that way.
