### ISSUE TITLE
[BUG]: invalid ELF header

### ISSUE THREAD

**Issue by kaju666** [theyosh/TerrariumPI#800]
**Setup:**
 - TerrariumPI version: 4.6.1
 - Install: Manual]
 - Raspberry PI: Raspberry Pi 2 Model B Rev 1.1

**Describe the bug**
For unknow reason terrarium pi stopped to work, error on screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/12675680/234177028-0492fe1f-caef-421e-a197-8182f3ce57cb.png)

**Additional context**
Didnt find similar problem on closed tickets, i think its something with python?
Or it could be next sd card damaged :(?

**Comment by theyosh** [comment]
I am afraid that this could be a broken SD card.

If you have made [backups](https://theyosh.github.io/TerrariumPI/faq/which-files-to-backup/), you can just try to reformat the SD card with a clean OS. Maybe that could solve it.

**Comment by kaju666** [comment]
i still can connect using winscp. so i made backup as you write.
buyed new sdcard, installed, restored backup and everything work.
