### ISSUE TITLE
Placeholders and notification syntax - distance alarm

### ISSUE THREAD

**Issue by jezzalencko** [theyosh/TerrariumPI#805]
Hi @theyosh. Hoping you can assist with how we can use the placeholder syntax for notification of a low water level alarm?
I have a distance measurement for a water tank with a high distance (low water level).
If I set up a 'sensor_alarm', how do I write the syntax to send me a notification to indicate the alarm_max for that particular sensor has been triggered? Can you please send me example syntax for this?
I've been trying to piece it together from the instructions (e.g. the button one) but am struggling.
Thanks.
![Screen Shot 2023-05-29 at 11 27 33 am](https://github.com/theyosh/TerrariumPI/assets/47110714/4daf906d-8041-4fbc-a1cb-0512b460732a)

**Comment by theyosh** [comment]
Hi, my documentation was wrong. You have to add a `$` in front of the placeholder. https://theyosh.github.io/TerrariumPI/notifications/#messages

Only use `{[placoholders]}` from the list on the right side. Self named placeholders will not work.

**Comment by theyosh** [comment]
But as you also have issue #802 I was wondering if you could give an update on that...

**Comment by theyosh** [comment]
And is the documentation clear now? It is not possible to get a message for a single sensor. The alarm message is sent for every sensor that is in alarm state.

**Comment by theyosh** [comment]
Is it clear how to use the placeholders? I would like to close this issue.

**Comment by theyosh** [comment]
Closing due to no response
