### ISSUE TITLE
[BUG]: Timer area

### ISSUE THREAD

**Issue by cjhudlin** [theyosh/TerrariumPI#818]
Setup:
- TerrariumPI version: 4.6.3
- Install: Docker
- Raspberry PI: 3a
-
**Describe the bug**
When setting start and end time of 00:00 and 23:59 (24hrs) respctively, th dashboard shows the timer being aftive only from 12:00am to 8:01pm, and not the full 24hrs
it also isnt very clear if the timer will work, as the timer settings allow for high and low alarm, but timers dont need any alarm, it should work at the set time, or at se intervals

**To Reproduce / Installation steps**
create timer area

**Expected behavior**
to show the timer, and when the next scheduled activation of the area is

**Screenshots**
![image](https://github.com/theyosh/TerrariumPI/assets/10757247/39837ed2-c547-41f7-8ee8-8214a142bc26)
![image](https://github.com/theyosh/TerrariumPI/assets/10757247/a2184413-6999-4b43-b124-9667874de9d6)

**Comment by theyosh** [comment]
I do not know why you have the strange times, but you can use both `00:00` as time in the begin and end time fields. This will trigger a 24 hour operating window.

**Comment by cjhudlin** [comment]
thank you, i did that. no change in the view, but i will assume it will work

**Comment by theyosh** [comment]
hmm, I hope / think it will update when the next day starts, or when the current period is ended.

**Comment by theyosh** [comment]
I am looking into this, and it looks like it is a GUI problem. The system should just do what you expect. Only the visual representation in the GUI is wrong. I am trying to fix this.

**Comment by theyosh** [comment]
Found the bug. So if you do a `git pull` where you have installed the software on the Pi, you should get some updates. After that, just reload the page in the browser. Make sure you have cleared your browser cache. Or hold down the shift key while reloading.

**Comment by theyosh** [comment]
Ah wait, you have a Docker setup... I just pushed a new `development` image to Docker.  There it should be fixed.

**Comment by cjhudlin** [comment]
thank you, yes, i realised that fter i changed the timer to 1 time every 60 minues the timer changed and shows the last time that the timer will be operational, not the operation window! but i test the new image as you mentioned. well done

**Comment by cjhudlin** [comment]
i have pulled the latest dev image but it doesnt seem to be working with the update you made, i bileave

**Comment by theyosh** [comment]
just to be sure I uploaded a new development image. So pull the image and restart. Make sure your browser cache is cleared. Else it could be that the browser is not loading the new code.

**Comment by theyosh** [comment]
Any updates on this? The latest dev image should show the correct timer times.

**Comment by cjhudlin** [comment]
> Any updates on this? The latest dev image should show the correct timer times.

I'm sorry I didn't come back to you, I haven't had much time to make any checks, I'll for sure test and let you know

**Comment by theyosh** [comment]
Hmm, I would like to close this issue. As I am sure it is fixed. And it is only a GUI issue.

**Comment by cjhudlin** [comment]
its working now, i just tested it, thank you
