### ISSUE TITLE
[BUG]: Cannot Save Area

### ISSUE THREAD

**Issue by biohazard827** [theyosh/TerrariumPI#821]
I did a clean install of 4.6.3 and cannot seem to save a simple timer light relay. I am given an error that my enclosure, type, and mode are not set. I have setup many instances of the software and have never seen this issue. I have included a screen capture of me setting the values along with the error. I checked network traffic to see if there was some issue in the JSON being passed to be saved, but I'm not seeing anything so this must be JS form validations.

![image](https://github.com/theyosh/TerrariumPI/assets/3673252/5dcc9795-c734-491b-8c70-f16ceff48d03)

![AreaSaveIssue01](https://github.com/theyosh/TerrariumPI/assets/3673252/ce621a5e-5f57-46ad-b800-ae31ee16218a)

**Comment by theyosh** [comment]
Strange. But did you save your old database? You can restore the database if needed.

But what kind of browser are you using?

I have to look into this. This is pretty strange...

**Comment by biohazard827** [comment]
I do not have a backup, in fact my issue previously was that the DB just gave up or became corrupt. I was getting "sqlite3.operationalerror: disk i/o error" when looking at the service logs or when accessing the DB directly via console using sqlite3. I figured since there was a new update I would just start fresh.

**Comment by theyosh** [comment]
I can add new areas without any issues. Using Firefox browser. So I get the feeling that clearing the browser cache should do the trick.

**Comment by theyosh** [comment]
Also, there is a fix for corrupted databases: https://theyosh.github.io/TerrariumPI/faq/sqlite3-databaseerror-database-disk-image-is-malformed/

**Comment by biohazard827** [comment]
It was a caching issue. Thanks for the help!

**Comment by theyosh** [comment]
No problem.
