### ISSUE TITLE
[BUG]:  TP wont bootup since Sensor has been deleted

### ISSUE THREAD

**Issue by sni89** [theyosh/TerrariumPI#827]
I changed some sensors and deleted the old ones. I guess i forgot that i have some dependencies going with relays/areas and the deleted sensors. TP is now traped in loading during bootup.

could you please take a look at my output during debug mode? :) 

<img width="522" alt="Screenshot 2023-09-04 184042" src="https://github.com/theyosh/TerrariumPI/assets/56272047/def73308-2b58-4d28-8d1a-21c549de9dff">
<img width="1276" alt="Screenshot 2023-09-04 184510" src="https://github.com/theyosh/TerrariumPI/assets/56272047/8678170c-9a0d-419c-b034-12600924a6ab">

**Comment by theyosh** [comment]
I made an update which should skip this error. But I am afraid a lot will happen still.. I can't tell what will happen when sensors are deleted when they are still being used.

So you can do now a `git pull` and run in debug again. See if it continues further.

**Comment by sni89** [comment]
well its up and i can delete the areas ! ty a LOT!

**Comment by theyosh** [comment]
Nice, so we where very **lucky** :P
