### ISSUE TITLE
[BUG]: Database Clean-Up script appears to be broken

### ISSUE THREAD

**Issue by G4KCM** [theyosh/TerrariumPI#829]
Hi,

Just upgraded to v4.7.0 this morning all went fine. Thank you.
I decided to try the database clean-up script, after stopping TerrariumPI I followed the instructions and the script failed, screenshot attached showing output.

Regards 

![IMG_2682](https://github.com/theyosh/TerrariumPI/assets/17541578/98ceeed6-833a-4e0b-b9ed-6a05b99ab386)

**Comment by theyosh** [comment]
Hmm, could you upload your database to: https://cloud.theyosh.nl/s/ZJTj4pAjcKgpe3C
All password are encrypted, so I cannot read them out.

Because I do not get this error. I guess some data is not correct in your database. So with you DB I can do some testing and debugging.

**Comment by G4KCM** [comment]
Hi, just uploaded the terrarium.db file for you.  Rgds Clive

**Comment by theyosh** [comment]
Thanks, got the file, and did the db_cleanup and got the same error. So I can do some testing now. Thanks for uploading.

**Comment by theyosh** [comment]
Damm, that was easy... you do not use buttons, so there is no data.... Never thought about that :P 

So do a `git pull` and you should be able to clean your database.

**Comment by G4KCM** [comment]
Brilliant!  Thank you!!
I will run it again next week when I have time to keep an eye on it.
Rgds
