### ISSUE TITLE
[BUG]: Multiple warnings on startup

### ISSUE THREAD

**Issue by 1ucket** [theyosh/TerrariumPI#840]
**More info**
Please look first at the [FAQ](https://theyosh.github.io/TerrariumPI/faq/) or [Current Issues](https://github.com/theyosh/TerrariumPI/issues) for more information.
Or search in the [closed tickets](https://github.com/theyosh/TerrariumPI/issues?q=is%3Aissue+is%3Aclosed) to see if it should been fixed in the past

**Setup:**
 - TerrariumPI version: 4.7.0
 - Install: Manual
 - Raspberry PI: 4

**Describe the bug**
The following warning messages are written on startup. TerrariumPi was stopped properly before. I am not using docker and have not made any modifications to the code.
```
/home/pi/TerrariumPI/terrariumUtils.py:491: ResourceWarning: unclosed file <_io.TextIOWrapper name='/proc/self/cgroup' mode='r' encoding='UTF-8'>
  return os.path.exists("/.dockerenv") or os.path.isfile(path) and any("docker" in line for line in open(path))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/pi/TerrariumPI/venv/lib/python3.7/site-packages/bottle.py:3383: DeprecationWarning: Absolute template path names are deprecated.
  fname = self.search(name, self.lookup)
```

**To Reproduce / Installation steps**
Start TerrariumPi with debug output, observe messages

**Expected behavior**
No warnings

**Additional context**

**Comment by theyosh** [comment]
Hi,

Some warnings I can't remove. The template warning of bottle is outside my control. The other about a docker check has been fixed. You can update with `git pull` and restart TerrariumPI.

https://theyosh.github.io/TerrariumPI/faq/known-errors/

**Comment by 1ucket** [comment]
Thanks!
