### ISSUE TITLE
[BUG]: Dimmed lamp stays at 1% after ramp down.

### ISSUE THREAD

**Issue by 1ucket** [theyosh/TerrariumPI#849]
**Setup:**
 - TerrariumPI version: 4.7.4
 - Install: Manual
 - Raspberry PI: 4

**Describe the bug**
The lamp is scheduled to turn off. In the relay page it's at 0%, but it's slightly glowing. If I turn it down to 0% manually it goes off, but afterwards will dim to 100% and then back to 1% over the next half hour.

**To Reproduce / Installation steps**
Add dimmable relay to an area with timer and ramp down. Observe.
![grafik](https://github.com/theyosh/TerrariumPI/assets/20580921/3b70f1c1-95b2-4fba-9107-8cc9476840d1)

**Expected behavior**
The lamp shuts off completely.

**Screenshots**
![grafik](https://github.com/theyosh/TerrariumPI/assets/20580921/f9371401-1b91-49a1-a52e-cde0cde3559c)
![grafik](https://github.com/theyosh/TerrariumPI/assets/20580921/e14932ec-763b-4238-b41f-caf246c232bd)

**Comment by theyosh** [comment]
Hmm sorry for the late response, but does it help when you edit the relay and use a frequency of 7500 at the calibration part?

**Comment by 1ucket** [comment]
> Hmm sorry for the late response, but does it help when you edit the relay and use a frequency of 7500 at the calibration part?

I set that value. Will report back later (will be dimmed down in 3 hours)

**Comment by 1ucket** [comment]
Unfortunately it didn't fix the issue, the lamp is still slightly on. :/

**Comment by theyosh** [comment]
Hmm, to bad.

Does it change when you do a restart? As the frequency is changed, it could be that it works after a restart.

Also, what happens when you manually turn the dimmer to zero?

**Comment by theyosh** [comment]
And maybe playing with the offset value of the dimmer. Try adding -1. Not sure what will happen, but maybe it helps.

**Comment by theyosh** [comment]
Any updates?

**Comment by 1ucket** [comment]
Sorry for not responding for a week. I'll try the possible solutions tomorrow and will give feedback afterwards.

**Comment by theyosh** [comment]
Any updates?

**Comment by theyosh** [comment]
Closing due to no response
