### ISSUE TITLE
[BUG]: Can't get mail notifications to work

### ISSUE THREAD

**Issue by duenni** [theyosh/TerrariumPI#851]
**Setup:**
 - TerrariumPI version: 4.7.0
 - Install: Manual
 - Raspberry PI: 3B

**Describe the bug**
I can't get mail notifications to work and have several issues with it.

**To Reproduce / Installation steps**

1. Add a mail notification service and try to edit it afterwards.
No matter what field I try to edit I always get a 404 error. I am logged in as admin.
![SCR-20231021-osf](https://github.com/theyosh/TerrariumPI/assets/4258185/97244c59-411e-46fa-a7e2-5ec45002c582)

2. When adding a notification message and saving it with the mail service enabled I get the folowing:
![SCR-20231021-ox6](https://github.com/theyosh/TerrariumPI/assets/4258185/4cd929fa-51b7-422a-b7c7-676a581f6b28)
I can save the notification with the mail service unticked. After editing this new notification and enabling the mail service I get a 404 again.
![SCR-20231021-oyb](https://github.com/theyosh/TerrariumPI/assets/4258185/6fee27ae-86ff-4ec1-90bb-923cf25b54b0)
Editing a notification throws a slightly different error sometimes:
![SCR-20231021-p3c](https://github.com/theyosh/TerrariumPI/assets/4258185/10ba74e3-ba82-45d6-9704-52c4823e1dc8)

**Expected behavior**
Mail notification entry should be editable.
A notification should be added without error.

**Comment by theyosh** [comment]
Hmm, found this also somewhere else. So I think I have fixed it. Do a git pull and restart. It should than work again,

**Comment by duenni** [comment]
Works like a charm now. 👍 
Thanks for fixing it so fast!
