### ISSUE TITLE
[FEATURE]: Add option to permanently enable dark mode

### ISSUE THREAD

**Issue by duenni** [theyosh/TerrariumPI#852]
**Is your feature request related to a problem? Please describe.**
Dark mode is dependent on weather sunrise/sunset. I'd like to set it permanently.

**Describe the solution you'd like**
I would like to have an option to turn on dark mode permanently and independent from sunrise/sunset.

Thanks for considering.

**Comment by theyosh** [comment]
Added the feature at the settings screen. If you do a `git pull` and restart TP4. you should see more options for the dark mode in the settings screen

**Comment by duenni** [comment]
Great! Thanks, that's awesome. 🥇
