### ISSUE TITLE
[BUG]: Issue with Enclosure Editing...

### ISSUE THREAD

**Issue by AaronNoletPDIT** [theyosh/TerrariumPI#862]
Setup:
 - TerrariumPI version: 4.8.0
 - Install: Manual
 - Raspberry PI: 4

**Describe the bug**
Cannot Edit Settings for Enclosure... Attempted different browsers also...

![image](https://github.com/theyosh/TerrariumPI/assets/50311191/3520a8de-265e-4bb5-82a4-70561ce9000e)

**Comment by theyosh** [comment]
Hmm, found the bug. If you do a `git pull` and reload the page in the browser (holding shift key) it should work again.

**Comment by AaronNoletPDIT** [comment]
Thank you this has resolved the issue.
