### ISSUE TITLE
New fresh install fails to start terrariumpi service

### ISSUE THREAD

**Issue by worzel910** [theyosh/TerrariumPI#870]
**Setup:**
 - TerrariumPI version: 4.6.3
 - Install: [Manual] 
 - Raspberry PI: 4b
**Describe the bug**
Clean install of Pi OS 32 bit (Legacy) Lite  followed be install of terrarium via git.

After installation terrariumpi service fails to start. 

**To Reproduce / Installation steps**
Clean install of Pi os lite then a install of terrariumpi. 

**Expected behavior**
Service to start after boot

**Comment by worzel910** [comment]
After looking through the debug output discovered the libopenblas-dev package  is needed.
After install of the package terrariumpi.service now starts.
Needs to be added as a dependency ?

**Comment by theyosh** [comment]
Please add some more debug information: https://theyosh.github.io/TerrariumPI/faq/how-to-debug-terrariumpi/

**Comment by theyosh** [comment]
ah that was quick :P

Hmm, OS package updates are hard to test. That takes about an hour... So I am always hoping that they stay to work.
I will add the package to the installation list

**Comment by theyosh** [comment]
Added package `libopenblas-dev` to the installer script

**Comment by worzel910** [comment]
> ah that was quick :P
> 
> Hmm, OS package updates are hard to test. That takes about an hour... So I am always hoping that they stay to work. I will add the package to the installation list

Nice to be an easy fix though!

**Comment by theyosh** [comment]
But the strange thing is that I do not need it on my existing systems. So that is a bit strange... but I will just leave it as a dependency to install. But it should be solved now.

**Comment by worzel910** [comment]
Oddly, didn't need it for the desktop image. Issue arose when I went to the lite version.
