### ISSUE TITLE
Unable to delete unused displays

### ISSUE THREAD

**Issue by nikkisstuff** [theyosh/TerrariumPI#878]
I have been trying a few of my oled/lcd  displays and the delete function is not working. I am getting this error:

The service 'oled' could not be deleted!
Error: Error deleting notification service with id Notification service display oled. 'NoneType' object has no attribute 'stop'

**Comment by nikkisstuff** [comment]
I fixed it buy disabling the display then rebooting and then it would allow me to delete it

**Comment by manolof** [comment]
@theyosh I have the same issue:
![Screenshot 2024-03-13 at 12 14 12](https://github.com/theyosh/TerrariumPI/assets/3025620/97b41ba7-a947-4624-acca-576c9303a6c0)

**Comment by theyosh** [comment]
Updated the code. With a `git pull` and a restart should this be fixed
