### ISSUE TITLE
[BUG?]: Button could not be added: No access to /dev/mem. Try running as root!

### ISSUE THREAD

**Issue by Swiftnesses** [theyosh/TerrariumPI#880]
Hello :)

Latest version (clean install) - I'm getting

`Button could not be added: No access to /dev/mem. Try running as root!` when trying to add a magnetic door sensor.

All other aspects work fine, inc webcam, relays.

I've checked permissions and all seems OK.

**Comment by theyosh** [comment]
Did you rebooted the Pi after clean install? It need at least one reboot after a clean install.

**Comment by Swiftnesses** [comment]
I sure did!

**Comment by theyosh** [comment]
What did you enter as GPIO address? I can just add a button without any problems

**Comment by theyosh** [comment]
Keep in mind the address should be the physical number on the Raspberry PI board.

**Comment by Swiftnesses** [comment]
This is just a new install @theyosh, I'm using GPIO14 for the magnetic sensor (I enter 14 like before).

**Comment by theyosh** [comment]
entering [14](https://pinout.xyz/pinout/ground) is NOT possible. That is a ground pin. So if you have connected on GPIO14 according to https://pinout.xyz/ you have to enter [8](https://pinout.xyz/pinout/pin8_gpio14/) as address

**Comment by Swiftnesses** [comment]
Let me check, I simply pulled the values from my old db, so everything was copied across.

**Comment by Swiftnesses** [comment]
Feels like user error, I'm just baffled how this worked before! Or at least that value was in the old db (working).

**Comment by Swiftnesses** [comment]
Sorry, it's on GPIO24, so I entered 18, not 14 :-/

It doesn't accept that.

**Comment by Swiftnesses** [comment]
I fixed it with:

```
sudo chown root.gpio /dev/gpiomem
sudo chmod g+rw /dev/gpiomem
```

**Comment by theyosh** [comment]
Are you on a Pi zero?

**Comment by Swiftnesses** [comment]
Pi 3 +

**Comment by theyosh** [comment]
Ok, but it is al working now? Still strange that you had to change some rights..

But this issue can now be closed?
