### ISSUE TITLE
[BUG]: PCA Dimmer 

### ISSUE THREAD

**Issue by sni89** [theyosh/TerrariumPI#881]
Hey folks, 

After nearly a year of a running system there is an error message popping up since I wanted to replace an old PCA Dimmer for a new one. 

The system won’t let me add a PCA Dimmer relay and gives me the following message: 

`Could not load hardware for relay PCA9685-dimmer dimmer named 'Test123' at address '0,0x40': [Errno 16] Device or resource busy, retrying in 0.5`

The PCA is running fine on another system.

**Comment by theyosh** [comment]
Bus 0 does not exists. So change the address to `1,0x40` or even shorter `0x40` should work

**Comment by theyosh** [comment]
Correct address should be `0x40` or `0x40,1` https://theyosh.github.io/TerrariumPI/hardware/#i2c-bus

**Comment by theyosh** [comment]
Did the address change work? Do you have an update on this?
