### ISSUE TITLE
AM 2302

### ISSUE THREAD

**Issue by nopalpite** [theyosh/TerrariumPI#89]
Hi,
Is it possible to use AM 2302 as a humidity and temperature sensor at the same time ?
Because it's not possible to share GPIO pin.

**Comment by Aapjes94** [comment]
It should be, you just need to add it twice. Once as a temperature and once as a humidity sensor. At least it worked for my DHT11.

**Comment by theyosh** [comment]
Yup, same here for a DHT22.

So just add it as a temperature and as a humidity sensor.

**Comment by nopalpite** [comment]
Hi,
It's working fine, maybe when i added second sensor, i've lost connection, so it failed to add it.
Thanks for your work, it's amazing !
