### ISSUE TITLE
[BUG]: Unprogrammed relays are activating randomly. 

### ISSUE THREAD

**Issue by ThunderClap86** [theyosh/TerrariumPI#890]
**More info**
Please look first at the [FAQ](https://theyosh.github.io/TerrariumPI/faq/) or [Current Issues](https://github.com/theyosh/TerrariumPI/issues) for more information.
Or search in the [closed tickets](https://github.com/theyosh/TerrariumPI/issues?q=is%3Aissue+is%3Aclosed) to see if it should been fixed in the past

**Setup:**
 - TerrariumPI version: 4.8.1 (and 4.8.0)
 - Install: [Manual]
 - Raspberry PI: 3B+ and 4
 - Qwiic Quad Relay module (i2C)

**Describe the bug**
During continued operation of the system, the program triggers relays as intended. I have Relay 1 (R1) configured to weather for main lights, triggers on/off normally. R2 is heater pad via sensors, on/off as-needed. R3 is a cooling ventilation fan, comes on and stays on until manually turned off (Not sure what setting to change). R4, unassigned becomes triggered randomly and unsure as to why. 

**Expected behavior**
I would expect R3 to turn off when the temperature cools below the sensor range specified. I would expect R4 to never activate because it’s unassigned. 

**Screenshots**
![IMG_1107](https://github.com/theyosh/TerrariumPI/assets/105729168/d3dca915-6134-421d-b24f-c24b40b7d23e)
![IMG_1108](https://github.com/theyosh/TerrariumPI/assets/105729168/f9f07118-77f0-4e61-8120-4fc20f99b4ee)
![IMG_1109](https://github.com/theyosh/TerrariumPI/assets/105729168/27357a1b-7cc8-4eb4-a441-c9bf24f16aac)
![IMG_1110](https://github.com/theyosh/TerrariumPI/assets/105729168/efc02cd0-cec3-4586-b421-e935a52ed8ff)
![IMG_1111](https://github.com/theyosh/TerrariumPI/assets/105729168/a7f3529e-d759-4546-853c-e4ce5a77a8e1)
![IMG_1112](https://github.com/theyosh/TerrariumPI/assets/105729168/cbfba751-53ef-42cd-9e73-13c17607df60)
![IMG_1113](https://github.com/theyosh/TerrariumPI/assets/105729168/8059efb0-b44d-44b1-93bc-8d152c32d37b)
![IMG_1114](https://github.com/theyosh/TerrariumPI/assets/105729168/edd57648-c591-4b77-81ad-8f446ada4351)

**Additional context**

**Comment by theyosh** [comment]
Are you also able to upload the logfile in the folder `log`? As far as I know should al sensitive date being stripped from the logfile. So you could upload it here.
Else you can also mail it to github@theyosh.nl Then I can look in the logs to see if I can find something.

The code for this relay is dead simple, so there is not much I can change to it.

Do you have other I2C hardware in use?

**Comment by theyosh** [comment]
I have not received a log file for further debugging. Else it will be hard to say what is causing this.. a log file could help a lot.

**Comment by ThunderClap86** [comment]
I apologize for the lengthy delay, I am away from my Pi at the moment and do not have it on the web to pull the log. I will be back physically at the Pi again this weekend to pull the log and upload here.

**Comment by theyosh** [comment]
Any updates?

**Comment by theyosh** [comment]
Any updates?

**Comment by ThunderClap86** [comment]
> Any updates?

Having trouble with this... can't get in to pull the logs. https://github.com/theyosh/TerrariumPI/assets/105729168/153bc640-1c62-4448-8d09-57970d1fcd7e

**Comment by theyosh** [comment]
Strange. Does this also happen on a desktop browser? I guess the image was of a Android with Chrome?
And did you enter the credentials, or does the error occur before you can enter the credentials.

You can also download the logfile through ssh. It is located at `/home/pi/TerrariumPI/log/terrariumpi.log` WinSCP is a tool that can do it. Or FileZilla

**Comment by theyosh** [comment]
Is this still happening? I do not have other people with login errors. Without a log file I can't do anything.

Is would like to close this issue if there are no updates anymore.

**Comment by ThunderClap86** [comment]
Yes, there are issues with the login still. The relays are also still doing the activation despite being unprogrammed. My next step is to reinstall everything and start over from scratch. Perhaps this will solve it.

**Comment by theyosh** [comment]
Have a look at https://theyosh.github.io/TerrariumPI/faq/which-files-to-backup/ and https://theyosh.github.io/TerrariumPI/faq/restoring-backup-files/ for backup and restoring your database and calendar.

**Comment by ThunderClap86** [comment]
> Any updates?

Do I really want to back it all up and "import" the relays acting the way they are if it's somehow a config setting I messed up? Genuine question.

**Comment by theyosh** [comment]
Good point. Than make at least a backup. So you can use a SQlite editor to read out the old values from the backup database when you reconfigure your setup.
