### ISSUE TITLE
[BUG]: Low/High alarm deviation values not showing

### ISSUE THREAD

**Issue by manolof** [theyosh/TerrariumPI#895]
**Setup:**
 - TerrariumPI version: 4.8.3
 - Install: Docker
 - Raspberry PI: 4B

**Describe the bug**
The Low/High alarm deviation values inside the Area Settings show empty values after the user saves them and reloads the page.

**To Reproduce / Installation steps**
![Kapture 2024-02-21 at 10 09 17](https://github.com/theyosh/TerrariumPI/assets/3025620/e7c52fe3-a594-4a69-bfb0-2f4a56c08b0a)

**Expected behavior**
The saved values of Low/High alarm deviation should show and persist after the user closes the modal window or reloads the page.

EDIT: same thing for Webcam's
Motion delta threshold
Motion minimum area

**Comment by theyosh** [comment]
Hmm, so some fields are not posted correctly or not loaded.... I have to look into this.

**Comment by theyosh** [comment]
The form fields are working again. Thanks for noticing

**Comment by theyosh** [comment]
Also build a new docker containers with all the fixes

**Comment by manolof** [comment]
Thanks! seems to work now.
