### ISSUE TITLE
[BUG]: Camera and Relays not working after Upgrade and Titles of Sensors erased 

### ISSUE THREAD

**Issue by Konrad84** [theyosh/TerrariumPI#924]
Hi there now after you solved my issue with telegram after the upgrade Camera isn´t working and there are no relais found anymore. Titles of sensores are erased. I upgraded again to 4.9.3 but still doesnt work. Have you got any solution or hint where to search ? Here ist the log ... 

                  |_   _|        | | | |     | ___ \_   _|
                     | |_   _ _ __| |_| | ___ | |_/ / | |
                     | | | | | '__| __| |/ _ \|  __/  | |
                     | | |_| | |  | |_| |  __/| |    _| |_
                     \_/\__,_|_|   \__|_|\___|\_|    \___/

                                                Version: 4.9.3

  Durchschnitt temperatur: 25.12 C  Betriebszeit:     11 days, 9:13:27
                                    Systemauslastung: 0.47, 0.53, 0.48
                                    CPU Temperatur:   60.148 C
                                    Speicher:         7.1 GiB(24.60%) used of total 29.0 GiB
                                    RAM:              247.5 MiB(28.42%) used of total 870.8 MiB

  Aktuelle Tätigkeit (0/0)  0/0.00 Watt, 0/0.00 L/m

      Letztes update: Thursday, 20-06-2024 22:02:43

Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Jun 20 21:15:05 2024 from 192.168.178.24
pi@raspberrypi:~ $ sudo service terrariumpi stop
pi@raspberrypi:~ $ cd TerrariumPI
pi@raspberrypi:~/TerrariumPI $ source venv/bin/activate
(venv) pi@raspberrypi:~/TerrariumPI $ python terrariumPI.py
2024-06-20 22:04:41,737 - INFO    - terrariumEngine       - Starting up TerrariumPI 4.9.3 on a Raspberry Pi 3 Model B Rev 1.2 ...
2024-06-20 22:04:41,773 - INFO    - terrariumEngine       - Loaded 32 settings in 0.03 seconds.
2024-06-20 22:04:42,916 - INFO    - terrariumEngine       - Start loading total power and water usage
2024-06-20 22:04:43,954 - INFO    - terrariumEngine       - Loaded total power and water usage in 1.04 seconds.
2024-06-20 22:04:43,955 - INFO    - terrariumEngine       - Loading existing sensors from database.
2024-06-20 22:04:44,984 - INFO    - terrariumSensor       - Loaded sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3c01f09637c2' with value 25.50C in 1.00 seconds.
2024-06-20 22:04:45,910 - INFO    - terrariumSensor       - Loaded sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3c01f096b371' with value 24.69C in 0.92 seconds.
2024-06-20 22:04:46,867 - INFO    - terrariumSensor       - Loaded sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3c01f096fb7e' with value 24.88C in 0.96 seconds.
2024-06-20 22:04:47,827 - INFO    - terrariumSensor       - Loaded sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3de104572f5c' with value 24.81C in 0.96 seconds.
2024-06-20 22:04:48,787 - INFO    - terrariumSensor       - Loaded sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3de10457f6b5' with value 25.25C in 0.96 seconds.
2024-06-20 22:04:48,791 - INFO    - terrariumEngine       - Scanning for new sensors ...
2024-06-20 22:05:02,887 - INFO    - terrariumEngine       - Loaded 5 sensors in 18.93 seconds.
2024-06-20 22:05:02,889 - INFO    - terrariumEngine       - Loading existing relays from database.
2024-06-20 22:05:02,912 - INFO    - terrariumEngine       - Scanning for new relays ...
No GEMBIRD SiS-PM found. Check USB connections, please!
2024-06-20 22:05:19,886 - INFO    - terrariumEngine       - Loaded 0 relays in 17.00 seconds.
2024-06-20 22:05:19,888 - INFO    - terrariumEngine       - Loading existing buttons from database.
2024-06-20 22:05:19,910 - INFO    - terrariumEngine       - Loaded 0 buttons in 0.02 seconds.
2024-06-20 22:05:19,911 - INFO    - terrariumEngine       - Loading existing webcams from database.
2024-06-20 22:05:30,300 - INFO    - terrariumWebcam       - Loaded rpicam webcam 'Schildkröten Haus' at address 'rpicam' in 10.36 seconds.
2024-06-20 22:05:30,302 - INFO    - terrariumEngine       - Loaded 1 webcams in 10.39 seconds.
2024-06-20 22:05:30,303 - INFO    - terrariumEngine       - Loading existing enclosures from database.
2024-06-20 22:05:30,311 - INFO    - terrariumEngine       - Loaded 0 enclosures in 0.01 seconds.
2024-06-20 22:05:30,468 - INFO    - terrariumEngine       - Message of the Day generated in 0.16 seconds
2024-06-20 22:05:30,475 - INFO    - terrariumEngine       - TerrariumPI 4.9.3 is up and running at address: http://0.0.0.0:8090 in 50.31 seconds.
2024-06-20 22:05:30,000 - INFO    - terrariumWebserver    - Running webserver at 0.0.0.0:8090
2024-06-20 22:05:35,033 - WARNING - hardware.sensor       - Error getting new data from sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3de10457f6b5': no data, retrying in 0.5 seconds...
2024-06-20 22:06:35,056 - WARNING - hardware.sensor       - Error getting new data from sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3de10457f6b5': no data, retrying in 0.5 seconds...
2024-06-20 22:07:35,047 - WARNING - hardware.sensor       - Error getting new data from sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3de10457f6b5': no data, retrying in 0.5 seconds...
2024-06-20 22:08:35,053 - WARNING - hardware.sensor       - Error getting new data from sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3de10457f6b5': no data, retrying in 0.5 seconds...
2024-06-20 22:09:35,047 - WARNING - hardware.sensor       - Error getting new data from sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3de10457f6b5': no data, retrying in 0.5 seconds...
2024-06-20 22:10:35,056 - WARNING - hardware.sensor       - Error getting new data from sensor 1-Wire sensor temperature named '1-Wire sensor measuring temperature' at address '28-3de10457f6b5': no data, retrying in 0.5 seconds...

Now there is a Error from 1-Wire too but this worked and i changed nothing only updated ... hmm

greets Konrad 

Thank You

**Comment by theyosh** [comment]
Hi sorry for the slow response. But this is strange, and hard to debug/fix. But it looks like only 1 sensor is complaining: '28-3de10457f6b5'

I have seen this also with my setup. That 1 1-wire sensor is broken. This is probably due to a bad connection. In my case. I know that I made a bad solder joint between two cables, and that joint is now laying on the bottom of my terrarium, probably in water. So for me, that means, 1 sensor just does not work, due to a broken cable. And I can't fix it, as I need to rebuild my terrarium.

About the 1-wire sensors, I am depending on OS support / integration. So I guess that there are some messages from the 1-wire system. You can check this by running: `grep w1 /var/log/kern.log`
This will probably produce some output. Paste it here.

And you should see some directories at '/sys/bus/w1/devices/' So when you list the contents of that folder what do you see?:
`ls -l /sys/bus/w1/devices/` What kind of list do you get?

It can also be, that somehow the Pi is overloaded, and therefore dropping some power resources. As I have seen that Bluetooth become a bit more unstable when the CPU is doing a lot of stuff.

And if the sensor is broken for what ever reason, you can put it on the ignore list in TerrariumPI, and that sensor will not be used anymore. You will lose a sensor, but the system will just continue without errors.

About the camera issues, I see nothing wrong in the log file. There it looks like the camera is working.

**Comment by Konrad84** [comment]
Hi there thank you for the help. I set up a new Raspian Legacy and new SD Card now it all works :)

Can you just help with the rtsp stream? I got an Onvif camera, an rtsp camera and an usb camera.

i tried few links but no response like :

rtsp://[ipadress:port]/stream 
rtsp://[ipadress:port]/onvif/stream 
rtsp://[ipadress]/stream 

and how do i get the adress of de usb camera ?

Soon i will do some pictures of the turtles :)

**Comment by theyosh** [comment]
I am not familiar with Onvif camera's. I see some information here about getting an RTSP url, but that is rather complicated when you are not that experienced on Linux: https://superuser.com/a/1711576
Also, I see this app: https://www.ipcent.com/mobile/onvifer Maybe that can show your camera in your network, and can give an RTSP url back. Not sure.
If you have found the RTSP stream, you can test it by using VLC https://www.thewindowsclub.com/how-to-play-rtsp-stream-in-vlc-media-player

For the USB camera, there should be something like `/dev/videoX` where X is a number. You can list them with `ls -l /dev/video*`
/dev/video0 is the Raspberry PI camera when added. Else I expect that you only have /dev/video1X devices, which are not camera devices TP can use. So the usb address should be something like: `/dev/video0` or `/dev/video1` I guess.

**Comment by theyosh** [comment]
Any updates? Did you get the cameras working?

**Comment by manolof** [comment]
> Did you get the cameras working?

Not sure if related, but my rpicam_live is crashing and not working. In fact, it just shows a live feed from the time that it last worked, which is around 8 days ago.
In the logs it shows:
```
2024-07-15 18:17:46,697 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Camera1' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-07-15 18:17:40,983 - WARNING - hardware.webcam       - Webcam Live Raspberry PI camera named 'Camera1' at address 'rpicam_live' is crashed. Restarting the webcam.
2024-07-15 18:17:27,577 - INFO    - terrariumWebcam       - Updated webcam rpicam-live webcam 'Camera1' at address 'rpicam_live' in 16.63 seconds.
```

and here's the live feed:
![Screenshot 2024-07-15 at 18 22 33](https://github.com/user-attachments/assets/aa332984-8233-470d-90b2-578c8c5288f8)

I am using 4.10.0, Raspberry PI 4B

**Comment by theyosh** [comment]
Hmm, could you run the following command through ssh on the console:

`ps fax` and show all the output here? I guess that somehow the camera is already being used..

**Comment by manolof** [comment]
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  1.0 168644  9528 ?        Ss   Jul07   0:57 /sbin/init
root           2  0.0  0.0      0     0 ?        S    Jul07   0:01 [kthreadd]
root           3  0.0  0.0      0     0 ?        I<   Jul07   0:00 [rcu_gp]
root           4  0.0  0.0      0     0 ?        I<   Jul07   0:00 [rcu_par_gp]
root           5  0.0  0.0      0     0 ?        I<   Jul07   0:00 [slub_flushwq]
root           6  0.0  0.0      0     0 ?        I<   Jul07   0:00 [netns]
root          10  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mm_percpu_wq]
root          11  0.0  0.0      0     0 ?        I    Jul07   0:00 [rcu_tasks_kthread]
root          12  0.0  0.0      0     0 ?        I    Jul07   0:00 [rcu_tasks_rude_kthread]
root          13  0.0  0.0      0     0 ?        I    Jul07   0:00 [rcu_tasks_trace_kthread]
root          14  0.0  0.0      0     0 ?        S    Jul07   0:28 [ksoftirqd/0]
root          15  0.0  0.0      0     0 ?        I    Jul07   1:47 [rcu_preempt]
root          16  0.0  0.0      0     0 ?        S    Jul07   0:00 [migration/0]
root          17  0.0  0.0      0     0 ?        S    Jul07   0:00 [cpuhp/0]
root          18  0.0  0.0      0     0 ?        S    Jul07   0:00 [cpuhp/1]
root          19  0.0  0.0      0     0 ?        S    Jul07   0:00 [migration/1]
root          20  0.0  0.0      0     0 ?        S    Jul07   0:30 [ksoftirqd/1]
root          23  0.0  0.0      0     0 ?        S    Jul07   0:00 [cpuhp/2]
root          24  0.0  0.0      0     0 ?        S    Jul07   0:00 [migration/2]
root          25  0.0  0.0      0     0 ?        S    Jul07   0:30 [ksoftirqd/2]
root          28  0.0  0.0      0     0 ?        S    Jul07   0:00 [cpuhp/3]
root          29  0.0  0.0      0     0 ?        S    Jul07   0:00 [migration/3]
root          30  0.0  0.0      0     0 ?        S    Jul07   0:25 [ksoftirqd/3]
root          33  0.0  0.0      0     0 ?        S    Jul07   0:00 [kdevtmpfs]
root          34  0.0  0.0      0     0 ?        I<   Jul07   0:00 [inet_frag_wq]
root          36  0.0  0.0      0     0 ?        S    Jul07   0:00 [kauditd]
root          38  0.0  0.0      0     0 ?        S    Jul07   0:00 [khungtaskd]
root          40  0.0  0.0      0     0 ?        S    Jul07   0:00 [oom_reaper]
root          41  0.0  0.0      0     0 ?        I<   Jul07   0:00 [writeback]
root          42  0.0  0.0      0     0 ?        S    Jul07   0:19 [kcompactd0]
root          43  0.0  0.0      0     0 ?        I<   Jul07   0:00 [kintegrityd]
root          44  0.0  0.0      0     0 ?        I<   Jul07   0:00 [kblockd]
root          45  0.0  0.0      0     0 ?        I<   Jul07   0:00 [blkcg_punt_bio]
root          46  0.0  0.0      0     0 ?        S    Jul07   0:00 [watchdogd]
root          50  0.0  0.0      0     0 ?        I<   Jul07   0:00 [rpciod]
root          51  0.0  0.0      0     0 ?        I<   Jul07   0:00 [xprtiod]
root          55  0.0  0.0      0     0 ?        S    Jul07   0:02 [kswapd0]
root          56  0.0  0.0      0     0 ?        I<   Jul07   0:00 [nfsiod]
root          57  0.0  0.0      0     0 ?        I<   Jul07   0:00 [kthrotld]
root          63  0.0  0.0      0     0 ?        S    Jul07   0:00 [irq/30-aerdrv]
root          65  0.0  0.0      0     0 ?        S    Jul07   0:00 [hwrng]
root          66  0.0  0.0      0     0 ?        I<   Jul07   0:00 [iscsi_conn_clea]
root          67  0.0  0.0      0     0 ?        I<   Jul07   0:00 [nvme-wq]
root          68  0.0  0.0      0     0 ?        I<   Jul07   0:00 [nvme-reset-wq]
root          69  0.0  0.0      0     0 ?        I<   Jul07   0:00 [nvme-delete-wq]
root          71  0.0  0.0      0     0 ?        I<   Jul07   0:00 [DWC Notificatio]
root          72  0.0  0.0      0     0 ?        I<   Jul07   0:00 [uas]
root          73  0.0  0.0      0     0 ?        S<   Jul07   0:32 [vchiq-slot/0]
root          74  0.0  0.0      0     0 ?        S<   Jul07   0:00 [vchiq-recy/0]
root          75  0.0  0.0      0     0 ?        S<   Jul07   0:00 [vchiq-sync/0]
root          82  0.0  0.0      0     0 ?        I<   Jul07   0:00 [zswap-shrink]
root         103  0.0  0.0      0     0 ?        I<   Jul07   0:00 [sdhci]
root         104  0.0  0.0      0     0 ?        S    Jul07   0:00 [irq/37-mmc0]
root         129  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mmc_complete]
root         133  0.0  0.0      0     0 ?        I<   Jul07   0:07 [kworker/3:1H-kblockd]
root         146  0.0  0.0      0     0 ?        I<   Jul07   0:08 [kworker/1:2H-kblockd]
root         193  0.0  0.0      0     0 ?        S    Jul07   0:25 [jbd2/mmcblk0p2-8]
root         194  0.0  0.0      0     0 ?        I<   Jul07   0:00 [ext4-rsv-conver]
root         208  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mld]
root         209  0.0  0.0      0     0 ?        I<   Jul07   0:00 [ipv6_addrconf]
root         248  0.0  8.2 115416 72356 ?        Ss   Jul07   0:50 /lib/systemd/systemd-journald
root         273  0.0  0.6  25848  5880 ?        Ss   Jul07   7:34 /lib/systemd/systemd-udevd
root         312  8.0  0.0      0     0 ?        S    Jul07 958:34 [w1_bus_master1]
root         315  0.0  0.0      0     0 ?        S    Jul07   0:00 [vchiq-keep/0]
root         319  0.0  0.0      0     0 ?        S<   Jul07   0:00 [SMIO]
root         338  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mmal-vchiq]
root         348  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mmal-vchiq]
root         351  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mmal-vchiq]
root         352  0.0  0.0      0     0 ?        S    Jul07   0:00 [irq/39-feb10000.codec]
root         377  0.0  0.0      0     0 ?        I<   Jul07   0:00 [cfg80211]
root         393  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mmal-vchiq]
root         395  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mmal-vchiq]
root         396  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mmal-vchiq]
root         397  0.0  0.0      0     0 ?        I<   Jul07   0:00 [brcmf_wq/mmc1:0]
root         399  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mmal-vchiq]
root         400  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mmal-vchiq]
root         401  0.0  0.0      0     0 ?        S    Jul07   0:37 [brcmf_wdog/mmc1:0001:1]
root         403  0.0  0.0      0     0 ?        I<   Jul07   0:00 [mmal-vchiq]
systemd+     408  0.0  0.6  90580  5468 ?        Ssl  Jul07   0:04 /lib/systemd/systemd-timesyncd
avahi        452  0.0  0.3   7360  2972 ?        Ss   Jul07   0:07 avahi-daemon: running [terrariumpi.local]
root         453  0.0  0.2   6692  2372 ?        Ss   Jul07   0:06 /usr/sbin/cron -f
message+     454  0.0  0.3   8832  3476 ?        Ss   Jul07   0:49 /usr/bin/dbus-daemon --system --address=systemd:
polkitd      457  0.0  0.4 235312  3776 ?        Ssl  Jul07   0:00 /usr/lib/polkit-1/polkitd --no-debug
root         468  0.0  0.6  17176  5956 ?        Ss   Jul07   0:10 /lib/systemd/systemd-logind
nobody       470  0.0  0.2   5828  2112 ?        Ss   Jul07   0:03 /usr/sbin/thd --triggers /etc/triggerhappy/trigge
avahi        475  0.0  0.0   7180    40 ?        S    Jul07   0:00 avahi-daemon: chroot helper
root         525  0.0  1.3 262604 11436 ?        Ssl  Jul07   1:39 /usr/sbin/NetworkManager --no-daemon
root         536  0.0  0.7  17168  6960 ?        Ss   Jul07   0:05 /sbin/wpa_supplicant -u -s -O DIR=/run/wpa_suppli
root         540  0.0  0.4 249648  3768 ?        Ssl  Jul07   0:00 /usr/sbin/ModemManager
root         615  0.0  0.3  13276  2952 ?        Ss   Jul07   0:00 /usr/libexec/bluetooth/bluetoothd
root         629  0.0  3.8 1141472 33540 ?       Ssl  Jul07   7:06 /usr/bin/python3 /usr/bin/fail2ban-server -xf sta
root         636  0.0  2.0 1418144 18448 ?       Ssl  Jul07   6:00 /usr/bin/containerd
root         660  0.0  0.4  16336  3980 ?        Ss   Jul07   0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 st
root         682  0.0  0.0   2752   744 ?        S<   Jul07   0:00 /usr/local/lib/tunnel_client/monitor_device --deb
root         683  0.0  0.0   2620   740 ?        S    Jul07   0:00 /usr/local/lib/tunnel_client/tunnel_log 20480 /va
root         684  0.0  0.0   2752   728 ?        S<   Jul07   0:00 /usr/local/lib/tunnel_client/terminal_monitor
root         685  0.0  0.0   2620   740 ?        S    Jul07   0:00 /usr/local/lib/tunnel_client/tunnel_log 20480 /va
root         688  0.0  0.0   2620   740 ?        S    Jul07   0:00 /usr/local/lib/tunnel_client/persistent_tunnel_ma
root         689  0.0  0.3   6800  2836 ?        S    Jul07   0:01 bash /usr/local/lib/tunnel_client/watchdog.sh
root         690  0.0  0.4  11840  4356 ?        S    Jul07   0:00 /usr/local/lib/tunnel_client/tunnel_log 20480 /va
root         691  0.0  0.4  11840  4296 ?        S    Jul07   0:02 /usr/local/lib/tunnel_client/tunnel_log 20480 /va
root         693  0.0  0.5  20972  5268 ?        S    Jul07   1:39 /usr/local/lib/tunnel_client/persistent_tunnel_ma
root         696  0.0  1.3 322792 12032 ?        S<l  Jul07   5:06 /usr/local/lib/tunnel_client/monitor_device --deb
root         697  0.0  1.1 169080 10196 ?        S<l  Jul07   9:20 /usr/local/lib/tunnel_client/terminal_monitor
root         706  0.0  0.0   2604   712 ?        S    Jul07   0:00 pitunnel --port=8090 --name=terrariumpi --http --
root         707  0.0  1.5 538436 13912 ?        Sl   Jul07   2:19 pitunnel --port=8090 --name=terrariumpi --http --
root         708  0.0  0.0   1352   668 ?        S<   Jul07   0:00 /usr/local/bin/pitunnel_terminal -i lo -p 0 login
root         733  0.0  4.5 2321868 39564 ?       Ssl  Jul07   6:56 /usr/bin/dockerd -H fd:// --containerd=/run/conta
root         739  0.0  0.0   5620   484 tty1     Ss+  Jul07   0:00 /sbin/agetty -o -p -- \u --noclear - linux
root         748  0.0  1.0  78824  8896 ?        Ss   Jul07   0:18 /usr/sbin/nmbd --foreground --no-process-group
root         881  0.0  1.3  94268 12184 ?        Ss   Jul07   0:02 /usr/sbin/smbd --foreground --no-process-group
root         919  0.0  0.5  92484  4592 ?        S    Jul07   0:00 /usr/sbin/smbd --foreground --no-process-group
root         920  0.0  0.3  92492  2816 ?        S    Jul07   0:00 /usr/sbin/smbd --foreground --no-process-group
root        4126  0.0  0.0      0     0 ?        I<   Jul07   2:31 [kworker/u9:1-brcmf_wq/mmc1:0001:1]
root        7239  0.0  0.0      0     0 ?        I<   Jul07   1:42 [kworker/u9:2-brcmf_wq/mmc1:0001:1]
root      282333  0.0  0.0      0     0 ?        I<   Jul08   0:07 [kworker/2:2H-kblockd]
root     1725337  0.0  0.0      0     0 ?        I<   10:19   0:01 [kworker/0:0H-mmc_complete]
root     1795762  0.0  0.0      0     0 ?        I    18:05   0:00 [kworker/2:0-mm_percpu_wq]
root     1795860  0.0  0.0      0     0 ?        I    18:06   0:00 [kworker/3:1-mm_percpu_wq]
root     1795887  0.0  1.1 719640 10040 ?        Sl   18:06   0:00 /usr/bin/containerd-shim-runc-v2 -namespace moby
root     1795908  0.0  0.0    860     4 ?        Ss   18:06   0:00 /sbin/docker-init -- /bin/bash /TerrariumPI/run.s
root     1795921  3.4 12.5 246288 110436 ?       SL   18:06   3:13 /opt/venv/bin/python /TerrariumPI/terrariumPI.py
root     1795928  4.0  0.1  13500  1628 ?        SLsl 18:06   3:45 pigpiod -l
root     1796112  0.0  0.0   3564   356 ?        S    18:07   0:00 tail -F /TerrariumPI/log/terrariumpi.log
root     1797208  0.0  0.0      0     0 ?        I    18:15   0:00 [kworker/1:2-events]
root     1800612  0.0  0.0      0     0 ?        I    18:37   0:00 [kworker/u8:1-events_unbound]
root     1806409  0.0  0.0      0     0 ?        I    19:15   0:00 [kworker/3:2-mm_percpu_wq]
root     1806516  0.0  0.0      0     0 ?        I    19:16   0:00 [kworker/u8:0-events_unbound]
root     1807029  0.0  0.0      0     0 ?        I<   19:20   0:00 [kworker/3:0H]
root     1807549  0.0  0.0      0     0 ?        I    19:23   0:00 [kworker/0:2-mm_percpu_wq]
root     1808343  0.0  0.0      0     0 ?        I    19:28   0:00 [kworker/0:0-events]
root     1808512  0.0  0.0      0     0 ?        I    19:29   0:00 [kworker/1:0-cgroup_destroy]
root     1808538  0.0  0.0      0     0 ?        I    19:30   0:00 [kworker/2:1-mm_percpu_wq]
root     1808566  0.0  0.0      0     0 ?        I<   19:30   0:00 [kworker/1:0H]
root     1808842  0.0  0.0      0     0 ?        I<   19:32   0:00 [kworker/2:1H]
root     1808936  0.0  0.0      0     0 ?        I<   19:32   0:00 [kworker/0:2H]
root     1809073  0.0  0.0      0     0 ?        I    19:33   0:00 [kworker/u8:2-events_unbound]
root     1809146  0.0  0.0      0     0 ?        I<   19:34   0:00 [kworker/3:2H]
root     1809176  0.0  0.0      0     0 ?        I    19:34   0:00 [kworker/0:1-events]
root     1809183  0.0  0.0   5200   780 ?        S    19:34   0:00 sleep 1800
root     1809369  0.0  0.0      0     0 ?        I    19:35   0:00 [kworker/2:2-events]
root     1809385  0.0  0.0      0     0 ?        I    19:35   0:00 [kworker/1:1-cgroup_destroy]
root     1809410  0.0  0.0      0     0 ?        I<   19:35   0:00 [kworker/1:1H]
root     1809695  0.0  0.0      0     0 ?        I<   19:37   0:00 [kworker/2:0H]
manos    1809797  0.5  1.1  19448 10200 ?        Ss   19:38   0:00 /lib/systemd/systemd --user
root     1809798  0.0  0.0      0     0 ?        I    19:38   0:00 [kworker/1:3-events_freezable_power_]
manos    1809799  0.0  0.4 170404  4172 ?        S    19:38   0:00 (sd-pam)
root     1809807  0.0  0.0      0     0 ?        I<   19:38   0:00 [kworker/0:1H]
root     1809979  0.4  0.3  10640  3316 pts/0    S<s  19:38   0:00 login
manos    1809997  3.2  0.5   8104  4804 pts/0    S<   19:38   0:00 -bash
manos    1810016  0.0  0.4  11148  4072 pts/0    R<+  19:38   0:00 ps aux
```

**Comment by theyosh** [comment]
@manolof you are running in Docker. For how long do you have this issue? And what was the last Docker image which worked? 

As the code for the live webcam is updated 5 months ago, and that should not produce the black box with name and timestamp anymore. So it is a bit unclear from which version you are upgrading from.

**Comment by manolof** [comment]
@theyosh last working version was 4.8.4, and I have the issue since last time I upgraded due to https://github.com/theyosh/TerrariumPI/issues/911, which was around July 7 (same time the cameras last recorded).

**Comment by Konrad84** [comment]
Hi there and sorry for the late answer. I now get a new SD Card with the latest Version of TerrariumPI installed.

Temperatur, Humidity and Relais are there. Rasperry Live Cam stays Blackscreen and Failure Message camera is offline. I think i have to check the connection first.

Till now i get my Telegram not working because bot says i have no rights if i want to test it . Maybe i have to set up it new.

For the Cam i check connection and then i can say if it is solved.

:)

**Comment by theyosh** [comment]
The Live RPI camera software is broken. So leave you hardware. I am working on a fix.

**Comment by theyosh** [comment]
@Konrad84 and @manolof There is a new release, which should fix the live webcam for docker and non docker setups.

So update your setup, and I guess that the webcam will start up again.

**Comment by theyosh** [comment]
@Konrad84 About telegram, you need yo enter your account handle, I am not sure if that includes an '@' in the name.
https://theyosh.github.io/TerrariumPI/notifications/#telegram

**Comment by Konrad84** [comment]
Hi there now everything works fine :-D

Tank You

**Comment by Konrad84** [comment]
Telegram is name without @ was wrong 👀

**Comment by theyosh** [comment]
Just to be sure: My documentation is wrong. You do **not** enter the `@` of your username

**Comment by Konrad84** [comment]
Yes just the telegram handle without @

**Comment by theyosh** [comment]
Any updates on this from either of you? Can I close this issue?

**Comment by manolof** [comment]
@theyosh the camera issue is fixed; thanks!
