### ISSUE TITLE
[BUG]: Clear the screen between messages for 20x4 LCD display

### ISSUE THREAD

**Issue by MakoShark2** [theyosh/TerrariumPI#925]
**Setup:**
 - TerrariumPI version: 4.10.2
 - Install: [Docker]
 - Raspberry PI: 4B
 - OS: Bookworm

**Describe the bug**
20x4 I2C LCD attached to the PI which receives notifications for sensor_update of 4 sensors (2 temperature + 2 humidity). Everything works fine except it seems the LCD screen is not cleared between messages. So for example if one message spans to the second line but the next one fits in one, the remaining second line of the previous message will still show.

**To Reproduce / Installation steps**
4 sensors connected (2 temperature + 2 humidity) connected to the PI 4B.
20x4 I2C LCD connected to the PI 4B.
20x4 LCD I2C display added to the notification service.
One notification message added,sensor_update, unlimited rate, message: ${name} ${value:.1f}${unit}

**Expected behavior**
LCD screen cleared before printing the notification message.
Or better, being this LCD 4 lines it would be nice if the message would scroll instead of printing every message always in the first line.

**Screenshots**
Don't have but I can get some if needed.

**Logfiles**
Don't have.

**Additional context**
None.

**Comment by theyosh** [comment]
Hmm, as far I can judge, the screen should be cleared for every message. At the moment I do not have my display connected. So I can't test right now.

So it can take a bit more time to look into this.

**Comment by MakoShark2** [comment]
OK, thanks.

I've record a video and made it available here: https://drive.google.com/file/d/1jQT8IiuSHqNTu3My4-diE4d0XW0J6hvp/view?usp=drive_link

At this time I have 4 sensors added named:
IN Temperature
IN Humidity
OUT Temperature
OUT Humidity

Hope this helps.

**Comment by theyosh** [comment]
I think I have fixed this. If you try a development image, it should work now better. https://hub.docker.com/r/theyosh/terrariumpi/tags?page=&page_size=&ordering=&name=development

Could you try it out and see if it works better now.

**Comment by MakoShark2** [comment]
Sure will do and let you know. Thanks!

**Comment by MakoShark2** [comment]
Not sure if it's me or anything else but the image is not starting, stuck on:

ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "/TerrariumPI/terrariumPI.py", line 24, in <module>
    from terrariumEngine import terrariumEngine
  File "/TerrariumPI/terrariumEngine.py", line 2, in <module>
    from hardware.webcam.rpilive_webcam import terrariumRPILiveWebcam
  File "/TerrariumPI/hardware/webcam/__init__.py", line 25, in <module>
    import cv2

**Comment by theyosh** [comment]
which development image did you use?

**Comment by MakoShark2** [comment]
development-bookworm

I'm running a RPI 4B with:
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

**Comment by theyosh** [comment]
But the 4.10.2 bookworm does work? That is strange...  there should not be that big changes that could cause this.

But for how long are you running on Bookworm? Because I did not fully test it... so I do not know how stable that is.

In the mean time I am thinking on how to test this. I suggest to go back to the latest working version for now.

**Comment by MakoShark2** [comment]
I've been running 4.10.2 bookworm it since it's release with no issues.

The development branch just kept restarting and outputing that error on the log.

I've run the development branch just by replacing the version :**latest** with :**development-bookworm** in the yaml file, is that the correct way to do it?

Meanwhile I went back to 4.10.2.

**Comment by theyosh** [comment]
Hmm, the `:latest` is not bookworm, but buster image. So than you can use `:development-buster` as image. 
I think that should do the trick.

**Comment by MakoShark2** [comment]
Ah... of course you are right, my mistake... Up and running and it works beautifully, thanks :)

I'll record a video tomorrow and will post it here.

**Comment by MakoShark2** [comment]
Here's the video. I've shortened the sensor names so it can fit on one line and it just looks perfect now, thanks.
https://drive.google.com/file/d/1udSrz46v_GnaDimJYdu4dqNIQbBVodGo/view?usp=drive_link

**Comment by theyosh** [comment]
Looks better! Cool

**Comment by theyosh** [comment]
You can now go back to the `:latest` tag, and the display should stay the same. I created a new release.
