### ISSUE TITLE
[FEATURE]: support for Meross MS100FH

### ISSUE THREAD

**Issue by rossisbudda** [theyosh/TerrariumPI#927]
Hello.
You kindly added support for Meross MS100H thermo-hygrometer.
https://www.meross.com/en-gc/smart-sensor/wifi-temperature-sensor/51
Would you know if the same support will work for this variant, the MS100**F**H?
https://www.meross.com/en-gc/smart-sensor/smart-humidity-sensor/143
This one seems much nicer as it charges by light source, so no battery worries :) Also ms100H seems rare compared to ms100FH (at least in UK).
Many thanks.

**Comment by theyosh** [comment]
Just did :)

If you are running from source, you can use it by doing a git pull.

For docker, wait a bit more when the development builds are ready

**Comment by theyosh** [comment]
Are you able to test this? Do you already have this sensor at home? Would like to know for sure that it works. I cannot test it.

**Comment by rossisbudda** [comment]
No, but I was wondering if you might like to leave this ticket open so that we can confirm it. I’ll buy one now as I wanted one anyway, especially now that you’ve confirmed it should work with terrariumPi.

**Comment by rossisbudda** [comment]
Hello. It works! No problem whatsoever. Thanks!!!

**Comment by theyosh** [comment]
Thanks for the feedback!
