### ISSUE TITLE
point and comma in system parameters kwh

### ISSUE THREAD

**Issue by nke69** [theyosh/TerrariumPI#93]
Good evening,

just for info I just had the small "misadventure" to crash the system using the comma "by habit" for the price of energy in the parameters.
This had the effect of crashing the server :(
So, I had to go change the value "power_price =" in the file settings.cfg and put the point for it to restart properly.

Sincerely.

**Comment by theyosh** [comment]
hmm that should not be possible. I have some input validation code in place. Apparently it does not work :(.

I will look into it. 
Thanks

**Comment by theyosh** [comment]
Found the bug.... and is fixed.

Do a git pull and clear browser cache. No need for a reboot for this fix
