### ISSUE TITLE
Is this a typo? Should it read increase OR decrease rather than OF?

### ISSUE THREAD

**Issue by rossisbudda** [theyosh/TerrariumPI#930]
I found this really confusing as it could just be strange english, but also becuase theres nothing in the docs to confirm.

I think it's so we can offset the alarm value for an area, therefore increase _or_ decrease would be clear and make sense. Sorry if that one is too picky!

https://github.com/theyosh/TerrariumPI/blob/2e9b8399f2a4a6817b1b8d61319489a9f939d854/gui/modals/AreaFormModal.svelte#L768

**Comment by theyosh** [comment]
Yup, that is a typo. Should just be `or`. Updated the code.

If you using a manual installation, you can do a git pull, and reload the browser holding down shift key. Than the new text and translation should be there. No need to restart TerrariumPI
