### ISSUE TITLE
[BUG]: Relais reversed after updating 

### ISSUE THREAD

**Issue by sni89** [theyosh/TerrariumPI#938]
Hey, 

I just updated and now the state of my Relais is reversed. It shows off but is on and on but it’s off… 

I already rebooted but it does not change to correct status. 🥲 

the shown status is correct but the relais itself is wrong 😑 

what else can I do???

**Comment by theyosh** [comment]
GPIO relays? Edit them, click on the calibrate option, and toggle inverse.

**Comment by sni89** [comment]
![IMG_4833](https://github.com/user-attachments/assets/02a71417-aec1-4dbe-8912-1e1427b419f2)

guess I have to set it on my pc right?

**Comment by theyosh** [comment]
Euh, I do not use mobile GUI. So please use laptop/desktop. Also may sure you have cleared your browser cache.

**Comment by sni89** [comment]
Worked on my pc. Thanks 🙏
