### ISSUE TITLE
[BUG]: day/night confusion

### ISSUE THREAD

**Issue by rossisbudda** [theyosh/TerrariumPI#948]
**Setup:**
 - TerrariumPI version: 4.10.2
 - Install: manual
 - Raspberry PI: 3B+
 - OS: raspbian 12 bookworm

**Describe the bug**
Day switched to night at midnight, even though day was scheduled to switch to night after 18 hours 09:30:-06:30
**To Reproduce / Installation steps**
I think that setting a day set to >12 hours that spans midnight will yield unexpected relay times. In the screen grabs you can see that 09:30 to 06:30 is in fact 18 hours, yet at midnight a state alteration occurs although not prescribed.

**Expected behavior**
I would expect the lighting toggle to flip at the prescribed absolute time rather than using midnight as marker. There is no mention of midnight in my config.

![image](https://github.com/user-attachments/assets/eef0faae-7212-44bd-be1a-3699729882f7)
I struggle to see why this relay toggled at midnight rather than 3.30am as requested.

**Logfiles**
[terrariumpi.log](https://github.com/user-attachments/files/16921887/terrariumpi.log)

**Comment by theyosh** [comment]
Sorry, but the issue has no information. Could you please put your question in the issue?

**Comment by rossisbudda** [comment]
Apologies, I misfired then forgot to submit the edit.

**Comment by rossisbudda** [comment]
I include the day/night period settings screen also.
<img width="914" alt="Screenshot 2024-09-08 at 09 53 10" src="https://github.com/user-attachments/assets/76d9e775-ed86-4f1a-ae7b-75dd23bc7af4">

**Comment by rossisbudda** [comment]
sorry about the messy ticket, all the original post has been cleaned up now 🧽

**Comment by theyosh** [comment]
On the other hand, this is a nice test case. I think I fixed this issue in code. Do a `git pull` and restart TerrariumPI.

Keep the restarting crontab in place, and lets see what happens tonight. It should stay on after a reboot just after 00:00.

**Comment by theyosh** [comment]
Did you had time to test the latest code with your timer setting? I think the issue should be fixed. A specially with you 30 min crontab restart.

**Comment by rossisbudda** [comment]
Hi sorry for the delay.

I tried a gitpull but it said I had changed a bunch of files and I couldn’t
figure it out. I’m a bit of a noob and I didn’t want to upset the cycle of
my environment or lose my config as it’s all live and I don’t want to
affect the lighting cycle.

Completely accept my hack is awful and tbh my extra hack was to disable the
crontab during the “post midnight” daytime 12-3.30. Definitely sucks but it
worked this far.

If I can swap to manual analogue timer soon I would find time do
confidently make a fresh install and reconfigure identically, then test.

Any advice welcome. Thanks for your patience.

**Comment by theyosh** [comment]
If you reinstall it, make some backups: https://theyosh.github.io/TerrariumPI/faq/which-files-to-backup/
And restore it like this: https://theyosh.github.io/TerrariumPI/faq/restoring-backup-files/

That should save some time setting it all up.

**Comment by rossisbudda** [comment]
Ok thanks I did see this but I was a bit hesitant.

I’ll try to update better or install fresh tomorrow. Please save the ticket!

Thx

**Comment by theyosh** [comment]
And you do not have to reset your SD card. Just move the existing `TerrariumPI` folder to a temporary name, and just start the TerrariumPI installation with the `git pull`.

You do not have to complete reinstall the OS. Just re-install TerrariumPI only. Saves a lot of time.

Will keep this issue open. No problem

**Comment by rossisbudda** [comment]
I have done a manual backup, gitpull, reinstall (4.11.1)  and removed my bi hourly crontab. Will report back if the midnight glitch happens or not!

**Comment by theyosh** [comment]
Ok, but without the crontab, the bug will not happen. But that is OK. As long it is stable for you. That is the most important.

The bug will only happen when you restart TerrariumPI after 00:00 and before 03:00 hours.

**Comment by rossisbudda** [comment]
I will be watching, then try a manual restart after midnight to see if it can reproduce. You're the best!

**Comment by rossisbudda** [comment]
Hi, I tried it. Restarting the service between 00:00 and 03:30 resumed the
day cycle as normal and the lights stayed on :)
Thanks again! I think you can close this.

**Comment by theyosh** [comment]
Thanks for testing. And good to hear the bug is fixed!
