### ISSUE TITLE
[BUG]: fresh install won't work

### ISSUE THREAD

**Issue by Snertjong** [theyosh/TerrariumPI#966]
**Setup:**
 - TerrariumPI version: 4.12.0
 - Install: [Manual] 
 - Raspberry PI: 4b
 - OS: Latest version and the July version  Raspberry pi os legacy 32 bit  lite

**Describe the bug**
fresh install TerrariumPI Every installation I do I get an error when starting after installation
tried about 10 times now.
Bought new SD card same problem.

manual start
Job for terrariumpi.service failed because the control process exited with error code.
See "systemctl status terrariumpi.service" and "journalctl -xe" for details.

Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit terrariumpi.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Oct 29 22:22:35 Terrapi systemd[1]: terrariumpi.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit terrariumpi.service has entered the 'failed' state with result 'exit-code'.
Oct 29 22:22:35 Terrapi systemd[1]: Failed to start TerrariumPI.
░░ Subject: A start job for unit terrariumpi.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit terrariumpi.service has finished with a failure.
░░
░░ The job identifier is 5008 and the job result is failed.
Oct 29 22:22:35 Terrapi systemd[1]: terrariumpi.service: Consumed 2.949s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit terrariumpi.service completed and consumed the indicated resources.

rens@Terrapi:~ $ journalctl -xe
░░ Support: https://www.debian.org/support
░░
░░ The unit terrariumpi.service completed and consumed the indicated resources.
Oct 29 22:22:56 Terrapi systemd[1]: Starting TerrariumPI...
░░ Subject: A start job for unit terrariumpi.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit terrariumpi.service has begun execution.
░░
░░ The job identifier is 5194.
Oct 29 22:22:58 Terrapi python[939]: Traceback (most recent call last):
Oct 29 22:22:58 Terrapi python[939]:   File "/home/rens/TerrariumPI/terrariumPI.py", line 20, in <module>
Oct 29 22:22:58 Terrapi python[939]:     from terrariumEngine import terrariumEngine
Oct 29 22:22:58 Terrapi python[939]:   File "/home/rens/TerrariumPI/terrariumEngine.py", line 2, in <module>
Oct 29 22:22:58 Terrapi python[939]:     from hardware.webcam.rpilive_webcam import terrariumRPILiveWebcam
Oct 29 22:22:58 Terrapi python[939]:   File "/home/rens/TerrariumPI/hardware/webcam/__init__.py", line 2, in <module>
Oct 29 22:22:58 Terrapi python[939]:     import terrariumLogging
Oct 29 22:22:58 Terrapi python[939]:   File "/home/rens/TerrariumPI/terrariumLogging.py", line 15, in <module>
Oct 29 22:22:58 Terrapi python[939]:     from terrariumNotification import terrariumNotification
Oct 29 22:22:58 Terrapi python[939]:   File "/home/rens/TerrariumPI/terrariumNotification.py", line 36, in <module>
Oct 29 22:22:58 Terrapi python[939]:     from terrariumDatabase import NotificationMessage, NotificationService, Sensor, Relay, Button
Oct 29 22:22:58 Terrapi python[939]:   File "/home/rens/TerrariumPI/terrariumDatabase.py", line 8, in <module>
Oct 29 22:22:58 Terrapi python[939]:     from terrariumUtils import terrariumUtils
Oct 29 22:22:58 Terrapi python[939]:   File "/home/rens/TerrariumPI/terrariumUtils.py", line 23, in <module>
Oct 29 22:22:58 Terrapi python[939]:     from cryptography.fernet import Fernet
Oct 29 22:22:58 Terrapi python[939]: ModuleNotFoundError: No module named 'cryptography'
Oct 29 22:22:59 Terrapi systemd[1]: terrariumpi.service: Main process exited, code=exited, status=1/FAILURE

(venv) rens@Terrapi:~/TerrariumPI $ python terrariumPI.py
Traceback (most recent call last):
  File "/home/rens/TerrariumPI/terrariumPI.py", line 20, in <module>
    from terrariumEngine import terrariumEngine
  File "/home/rens/TerrariumPI/terrariumEngine.py", line 2, in <module>
    from hardware.webcam.rpilive_webcam import terrariumRPILiveWebcam
  File "/home/rens/TerrariumPI/hardware/webcam/__init__.py", line 2, in <module>
    import terrariumLogging
  File "/home/rens/TerrariumPI/terrariumLogging.py", line 15, in <module>
    from terrariumNotification import terrariumNotification
  File "/home/rens/TerrariumPI/terrariumNotification.py", line 36, in <module>
    from terrariumDatabase import NotificationMessage, NotificationService, Sensor, Relay, Button
  File "/home/rens/TerrariumPI/terrariumDatabase.py", line 8, in <module>
    from terrariumUtils import terrariumUtils
  File "/home/rens/TerrariumPI/terrariumUtils.py", line 23, in <module>
    from cryptography.fernet import Fernet
ModuleNotFoundError: No module named 'cryptography'

**To Reproduce / Installation steps**
manual installation steps

**Comment by theyosh** [comment]
Found the problem. Do a `git pull` and rerun the installer. It should now installer a lower version of the library cryptography which was causing the problem.

**Comment by Snertjong** [comment]
> Found the problem. Do a `git pull` and rerun the installer. It should now installer a lower version of the library cryptography which was causing the problem.

Yes excellent! it's alive! 

I already thought I was doing something wrong..

**Comment by theyosh** [comment]
> I already thought I was doing something wrong..
You did NOTHING wrong... some external code was removed. And I had to downgrade a Pyhton library

**Comment by Snertjong** [comment]
> > I already thought I was doing something wrong..
> 
> You did NOTHING wrong... some external code was removed. And I had to downgrade a Pyhton library

That's what I found out after trying a hundred times!
I'm going to pick up this project again after years and make new paladarium!

thanks!
