### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by MakoShark2** [theyosh/TerrariumPI#967]
**Setup:**
 - TerrariumPI version: 4.12.0
 - Install: [Docker]
 - Raspberry PI: 4B
 - OS: Bookworm

**Describe the bug**
Missing translation under: Area configuration > tab variation.

**To Reproduce / Installation steps**
N/A

**Expected behavior**
N/A

**Screenshots**
![image](https://github.com/user-attachments/assets/aa874c31-53b9-42c1-b901-3b4595f6de86)

**Logfiles**
N/A

**Additional context**
N/A

**Comment by theyosh** [comment]
Translations is a community effort: https://github.com/theyosh/TerrariumPI?tab=readme-ov-file#translations

**Comment by MakoShark2** [comment]
> Translations is a community effort: https://github.com/theyosh/TerrariumPI?tab=readme-ov-file#translations

I know, but translation is marked as complete (100%) for the language I'm using (Portuguese).

**Comment by theyosh** [comment]
Is has not been added to the translation. So that needs some code changes from my side.

But the variation tab is not a stable feature. Also it is not really documented. So not sure if you want to use it...

**Comment by theyosh** [comment]
If you want, you can now add new translations: https://weblate.theyosh.nl/translate/terrariumpi/gui/pt/?q=state:%3Ctranslated

But again, it could not be all clear what it should do. It is a complex part of the system which is not being used I guess. Else there would be lot more questions about it.

**Comment by MakoShark2** [comment]
OK. Was trying to use the variation but it does seem to be not working as it should. I'll leave it then.

**Comment by theyosh** [comment]
Than I close this issue also.
