### ISSUE TITLE
Unable to add new switch

### ISSUE THREAD

**Issue by MichalDuban** [theyosh/TerrariumPI#97]
In the latest version of your app., I am not able to add new switch (source GPIO). I fill all required fields, but add button does not respond.

**Comment by theyosh** [comment]
Clear browser cache? The code has been updated. I guess you have old HTL code in your browser cache

**Comment by Barbara1984** [comment]
In the system environment, the plus symbol is not synonymous top right :-)

**Comment by theyosh** [comment]
Found the bug. Do a git pull and clear browser cache. You should now be able to add switches again.

**Comment by theyosh** [comment]
@Barbara1984 the plus symbol should not be there :) and is removed

**Comment by MichalDuban** [comment]
Hi, it seems add button is working now, but submit button not.

**Comment by theyosh** [comment]
Sorry for that. Do another `git pull` and clear browser cache. Should work now

**Comment by theyosh** [comment]
I have added already new switches, and that is working. So I think it is all ok now?

**Comment by MichalDuban** [comment]
Great! Now it is working properly. Thank you.
