### ISSUE TITLE
[FEATURE]: Embeddable Links for Graphics

### ISSUE THREAD

**Issue by t00thpick1** [theyosh/TerrariumPI#970]
**Is your feature request related to a problem? Please describe.**
Writing an html kiosk dashboard for logging+history on feedings/bowel movements/etc for my lizard and wanted to embed some of the temperature/humidity graphics from my TerrariumPi setup directly in my dashboard for a quick glance at terrarium conditions.    Would be nicer to integrate if I didn't have to render the graphs myself with API data but could instead just iframe/embed the graphs as needed.

**Describe the solution you'd like**
Links such as /api/sensors/{id}/embed to render just the graphic for a given sensor such as below.

![{4429A723-C519-4D9F-83A2-F37298DDB16D}](https://github.com/user-attachments/assets/31dee5ed-6e3f-4f56-a012-9d1cae2a9dac)

**Comment by theyosh** [comment]
I am afraid that this is not easy to make. The GUI is made in a reactive javascript framework, so I cannot just pick out the graphs for embedding in a different page.

And it will take a lot of time to make a the graphs embed-able. So I am afraid you have to make you own graphs.
I used https://bernii.github.io/gauge.js/ for the gauge graph, which is pretty old, but does still work and https://www.chartjs.org/ for the graphs.

Sorry, but this is something that I cannot make. There are API calls to get the sensor data and make your own graphs.

**Comment by t00thpick1** [comment]
Thats fair, I was hoping it would be easy to pull out just the components but I haven't looked too hard into the svelte code as I'm unfamiliar with svelte.

**Comment by t00thpick1** [comment]
If I made some nice re-usable  chart.js scripts for integration would they be welcome somewhere in the codebase as resources for others?
