### ISSUE TITLE
Rugged I2C Moisture Sensor Issue

### ISSUE THREAD

**Issue by KDPPD** [theyosh/TerrariumPI#975]
Been interested in this project for awhile and decided to finally do it but now I'm pretty much stuck on the last sensor.

I purchased this I2C chirp sensor:
https://www.robotshop.com/products/rugged-i2c-soil-moisture-sensor?gad_source=1&gclid=CjwKCAiAgoq7BhBxEiwAVcW0LHC8pwh7UGqfl7dKvULHO3RFbgWzN5LBikgDXBQXCjeQMHVRhxWGIhoCuagQAvD_BwE

I2C moisture sensor is detected on 0x20.
![i2cdetect](https://github.com/user-attachments/assets/f9cd7b95-62c3-4bf0-9c40-fe2c73038c6a)
I2C 0x10 = DockerPI Relay
I2C 0x44 = SHT3XD

I've calibrated utilzing the chirp.py which seems to work on 0x20 but the I2C address reads in decimal.
![chirp](https://github.com/user-attachments/assets/bc888b39-2ac2-4a40-a5c5-ca0c9013245d)

GUI Settings:
![moisture sensor](https://github.com/user-attachments/assets/eddc5710-9a3d-4ba0-914f-9f3974fe08ed)

Log Error:
2024-12-18 17:58:23,928 - ERROR   - hardware.sensor       - Error updating sensor CHIRP sensor moisture named 'Soil Moisture' at address '0x20'. Check your hardware! Error getting new data from sensor CHIRP sensor moisture named 'Soil Moisture' at address '0x20': division by zero

What am I missing here?

Appricate your project and so far it's been a breeze, thanks for all your hardwork.

**Comment by KDPPD** [comment]
It works! Excellent job. I was definitely way off from finding that answer.

**Comment by theyosh** [comment]
Euh, I only fixed the GUI which did not show the min and max moisture calibration values. But that have solved it?

But nice that it works now.
